### ISSUE TITLE
Crash Report -320155265

### ISSUE THREAD

**Issue by Goztrak** [wowsims/sod#1007]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJztVE1IVFEUfufO35ujT8drP2+uRjaUvYbG3rxx1IlgXi5aSIsxWrgKE4yKImlAahFYJNVKa5croaAoC7GVBCUuRKFMJcNFQVQLkawQMrFFnfcz09A2+1l0Fofvfud8551zLu/iZplVMY3p0AAma4Wj0AHjbIDdBuhimV4GjWEVbjMYZGDCHECGtcAg7DsK/Qy4JGaL0J85cfhs++mQT91TFYiew0BockFRP5ajN/RgWaHjFB37UyhZcFFR35YQmCHulQUmibkRoNzpBSv3mSMNhJ4Q6LH4R18U8o9tv7Rq+Q+frcyBblDfl/wAVGFZMcpDoEEDM9mZ4svg6wfPDEi7J734mkn/7bcan4e/3cKfsgUmNZY2AP0iJmSgBVrpn2mqNJK6nojrlo+RS+oJwzoZCT0Zz3hbgm3S8S6fCrgegyKAPnmkWQtEZPSjNxbXsxhGZQjQ5TmkCkLrUD5OWL55N1zAbnTrnD+geSOIFIjV1RjJLKqIgk7y1THQfG6ktqa+INJDEY8bSdiaXLGxZs3vBuK2pBxlYX37ZT9EKAE9sXiWRnDqDD+FKn+e5hUijCWRYsQhyA2Yn5STwi50cUlwr2C7Jb5JVGBZtFT2ctYmCbtKXXKbnbSyGua1wkAtWi37uW+UMZmJiiGmysCDfcxKufNFFUEkVVzXT2aFS/E6UYs7ott/qCqHWJhU2MesVuY7NSyU5TieEvW4k0dxQ3QdaYOjYBUcpm9QVwi1GIqWEO95A5LDGLZ0kXafn4y2Ya/gp5mSNJMXmarwSiGc/RjW8gbegeYXecSLhbPU55foCeNFwrmQ+4W7+0pryeGHNGxc7MKtPIJKpAiDRu7+7Ab8nDW5DST0bP5uO8ZhhcGE+xrK5rSLUuYcgz6QrjG6G9UTGfEEncAhs8wBNWa477plE+mUw0yltxyx7UXa6PXIcxcULu9v72w/UVWnq+noP/bkalfMNalTfe+X6oTEt7Xpgyxu+45bZurYqU/dEwdn03vdiNkC3wGrNcdV

RNG Seed: 0

Aura label is required!
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:49 +0x10
panic({0xb6bc0, 0x2e69c0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*auraTracker).registerAura(0x2c1c6b8, 0x2c1c000, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/sod/sod/sim/core/aura.go:379 +0x3c
github.com/wowsims...

**Comment by kayla-glick** [comment]
Just pushed a fix!
