### ISSUE TITLE
Crash Report 409573410

### ISSUE THREAD

**Issue by miicka87** [wowsims/sod#1009]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJzjkuVgUmDSYDJgtGB0YEpgLGA8wbSGaQUjYwNTwAQmRidJCcYVTIwbmBgdGG8wMgYwRTBuYHTLYFzAxCjEIDWdnYstICexMrVIgF3CRoFdaw0jF7fAuVe8Eg+5NZasluRiEZj+m5eLXeACUKjbGijX8YNXosdao+WTFJBz4S2vxGM+jZ6LIM4loJK7fBo71oM454Ayi9k1Vn2X4OIQuPiKV2MTkMUtcB5i8tENkkDOGSCnn13jxw+QmqXfeTX6WqSBrL/TGDUmAFksAp9+8QLJd19BDmhp55N4wwdktE8GM1gELn7jNVLhYBZg1wD5nNGDKYKpgqeDkXUBIzPQ9wcYGS8xMikA/cxidY6F6wETwyigKRB6wTjQTqAXeMXE4MRvwQhMZQ6MAYwRjKBM5yVjZGpgYGxoACJ1gYSpgbERiGdkbGBqCFTFnMSQxSTBWHCC8QcT40locuRwuAhlWTrcYGKcxcgwiYlFikmCWekAMydEIs5BEMLQc5CcNRMETtpbQkQu2CumgcE1e6MJzBw3mniFOHxSy1JzFMwMJOy1Blma1+h0oIo5amspMkdA6j913AEEhmCyYLmDZWb+h9aTIVftHaEyDhGMAHIIgSE=

RNG Seed: 1873867222

Aura label is required!
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:124 +0x10
panic({0xb6bc0, 0x2e69c0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*auraTracker).registerAura(0x2c0a6b8, 0x2c0a000, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/sod/sod/sim/core/aura.go:379 +0x3c
github.com/wowsims/sod/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/sod/sod/sim/core/aura.go:413
github.com/wowsims/sod/sim/shaman.glob..func23({0x2f0f10, 0x241f428})
	/home/runner/work/sod/sod/sim/shaman/item_sets_pve.go:255 +0xe
github.com/wowsims/sod/sim/core.(*Character).applyItemSetBonusEffects(0x2c0a000, {0x2f0f10,...

**Comment by kayla-glick** [comment]
Just pushed a fix!
