### ISSUE TITLE
Crash Report -1999082898

### ISSUE THREAD

**Issue by roundchains** [wowsims/sod#1010]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJzjEuRgUmDSYDJgtGB0YCpgmsDE6CQowejAeIORMYJxA6NbBuMPRkYhBqmXbFxsATmJlalFAqwSNgrsWmsYubgFzr3ilXjIrbFktSQXi8DZX7xc7AIXgELd1kC5+T94JXqsNVo+SQE5p4Gij/k0NnyXAHIuATl3+TTaNoBkOr7wSixm19gNlOEQuPiKV2MTWE37F7DJb/6COGeAGvrZNX78AKnZ951X40+zNJC1H8ia0CINtPoT0GoWgXdfQQ5Y08oo8YYPwWARuPiN10iCg1mD0YLJA+irCp4ORtYVjIwHGBkvMTJYnWPhesDEMApoCoReMA60E+gFXjExOLE4MAYweskYmRoYGBsagEhdIGFqYGwE4hkZG5gaBjBGcCQxZDFJMBacYPzBxDiLkWESE4sUkwSz0gFmTohRfg6CEIaIg+SsmSBw0t4SInLBXjENDK7ZG01g5rjRxCvE4ZNalpqjYGYgYa81yFK0RqcDVcxRW0uROQJS/6njDiAwBJMFyx0sM/M/tJ4MuWrvCJVxiGAEADHtdmg=

RNG Seed: 2215304656

Aura label is required!
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:49 +0x10
panic({0xb6bc0, 0x2e69c0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*auraTracker).registerAura(0x2c746b8, 0x2c74000, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/sod/sod/sim/core/aura.go:379 +0x3c
github.com/wowsims/sod/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/sod/sod/sim/core/aura.go:413
github.com/wowsims/sod/sim/shaman.glob..func23({0x2f0f10, 0x241f720})
	/home/runner/work/sod/sod/sim/shaman/item_sets_pve.go:255 +0xe
github.com/wowsims/sod/sim/core.(*Character).applyItemSetBonusEffects(0x2c74000, {0x2f0f10, 0x241f720})
	/home/runner/work/sod/sod/sim/core/item_sets.go:159 +0x6...

**Comment by kayla-glick** [comment]
Just pushed a fix!
