### ISSUE TITLE
Crash Report -40278359

### ISSUE THREAD

**Issue by Masstachief** [wowsims/sod#1011]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJzjkuVgUmDSYDJgtGB0YEpgLGA8wbSGaQUjYwNTwAQmRidJCcYVTIwbmBgdGG8wMgYwRTBuYHTLYFzAxCjEIDWBnYstICexMrVIgF3CRoFdaykjF7fAuVe8Eu+FNZasluRiEZj+m5eLXeACUKjbGijX8YNXosdao+WTFJBzGij6mE+j5yKIcwnIucun0bYBxOn4wiuxmF1j1XcJLg6Bi694NTYBWdwC7UDhh9wab/6COGeAGvrZNX78AKlZ+p1Xo7FFGsj68JVXYwKQxSLw6RcvkHz3FeSAx594Jd7wcTEABS5+4zVS4WAWYNcAeZnRgymCqYKng5F1ASMz0NsHGBkvMTIpAD3LYnWOhesBE8MooCkQesE40E6gF3jFxODEb8EITGUOjAGMEYyg3OYlY2RqYGBsaAAidYGEqYGxEYhnZGxgaghUxZzEkMUkwVhwgvEHE+NJaHLkcLgIZVk63GBinMXIMImJRYpJglnpADMnRCLOQRDC0HOQnDUTBE7aW0JELtgrpoHBNXujCcwcN5p4hTh8UstScxTMDCTstQZZmtfodKCKOWprKTJHQOo/ddwBBIZgsmC5g2Vm/ofWkyFX7R2hMg4RjADEc3+v

RNG Seed: 1198235446

Aura label is required!
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:124 +0x10
panic({0xb6bc0, 0x2e69c0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*auraTracker).registerAura(0x27ee6b8, 0x27ee000, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/sod/sod/sim/core/aura.go:379 +0x3c
github.com/wowsims/sod/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/sod/sod/sim/core/aura.go:413
github.com/wowsims/sod/sim/shaman.glob..func23({0x2f0f10, 0x2cd2c68})
	/home/runner/work/sod/sod/sim/shaman/item_sets_pve.go:255 +0xe
github.com/wowsims/sod/sim/core.(*Character).applyItemSetBonusEffects(0x27ee000, {0x2f0f10, 0x2cd2c68...

**Comment by kayla-glick** [comment]
Just pushed a fix!
