### ISSUE TITLE
Missing items: Rage of Mugamba

### ISSUE THREAD

**Issue by shaugen** [wowsims/sod#1019]
Links to [WOTLK Wowhead](https://wowhead.com/classic/items "https://wowhead.com/classic/items") for each item:
https://www.wowhead.com/classic/item=231350/rage-of-mugamba

**Comment by kayla-glick** [comment]
Hey @shaugen I'm seeing this item in the warrior sim.
![Image](https://github.com/user-attachments/assets/ddc09ae9-45a4-431d-93aa-0d2830783e5c)

Double check your settings and if that doesn't work, try clicking the ⚙ in the top right then "Restore Defaults"

**Comment by shaugen** [comment]
Found it now, thanks!

**Comment by kayla-glick** [comment]
Awesome glad you were able to get it resolved!
