### ISSUE TITLE
Crash Report -489862906

### ISSUE THREAD

**Issue by OobieWoobies** [wowsims/sod#1057]
Link:
https://wowsims.github.io/sod/warrior/#eJzNVmFsFFUQvnm713s3x263r2ezvNq0tFaWVZq9a6+2VO2CfwgS0wQ0pImxNtQAom1oYvSfqSGgkNhg0kiTxmo0YhPQkEilCqkGEuoPAkagpmo0/kHhh/WHNEKC8/Z2S+/sPxrq/Hg3872ZN9/Mm91bTHNmMZ91wX4Ggww+YzAJsKHMBh++YGwHnAPYCKMMREzOlmFJx+7nX+vZY2n2ozVJ9xPAlPXlkGlfaHOm9knUrZuHTExYJwk6lqa9iQOmfbHE+XBWknGa0N9MZ2ZoJRnjZPxkOl/tUzu3Dpr2ewnn7IhEbs0dNJ0zI8rn1O+GOvnMzcCggLcTzq8Uza3zb5nOqTcqSfvohuHcIk23PhgBWv/6xyACR+cM+7pJ5ucH1Hr2byNbbSUcaKGqdsCrif3AR0GjQr8DnYMF06CvO6/jLyxWII/7sf+H+OHv5DJyWBIRV2G5Kdwr+YPFNogWOAI0cxuhA94F6KLh21SV9Rq9nEdrY3ZtTimeMnNehn4zHWyb3h3b9T3aGpYjlyWoc5r52gTGUVvb3I8CE5JUPlweYk39izhmF3HM3HG8dhrmQVHHQVZjhZvmukhOgNr/Ya5SxSI0hUcs5jRd6HS4XLwDchBwL8gBwIfEGlwt67FOrELLNSmM7Ymp5MgaPTRqU5g8HhwzO3Y/tolWrHIruSbMCUgJZsUxzk90OgkZsMw25DA5pitv9fZYEDwzVxmQ0v5DKhN1RFwDeRXwZ5AzgI+JNmyVjyzKKlfMqsghm8Mn5Hr0RENhyus3KOU3jHGGaVcU4tohiC08ljB8WmwJitUXLzZTWKzqYVHBBVkICLJEF1UlK1G4FgeR5yTjAzrjmtq2hraIFXSP+Rn4cRSEIVPIRD72dlr0yZdxu+jGalmF/DgodNzAMreUxwVbFwv5ZT0sdY0QyvcaG+TDWO6WEa2AC0fK4DV4GbzPLScwpDIPBwTo3S965Uv3KKOqf2CnyEoP60Xdwg6HQ70rEV1DkMGTkS2SMv8kHemaV8cN8QB1sgYrZDpoN83JppBFpinXP9/h7bIbnxFbMf4t8QHMycZgrEoK5q5aVBWjNGwLJlHduB7VFE5Js8rGT7wPTlz0EpcX8Tnx7F3myVcSDY5qQzbapidpQcJ6WYe2W1HYt2h8g8593enoQl1rcUJPJjHBP+2sAYeLlEze8V4hMUhxeQLIapZNuEaujvJfoU8C6dp0tTjMVMglConuN9MvI0hgON/0NSFM6kv+zMkr4Gh952COwVT4L8/9i6HW6k8zGIbYGCuVRjKAXn/St6FFq53U8nbsKb8sr6T9lcOHlUy1t+aRC+2rXgjkcnt2UOPTA4bgm3te6dld0+zZ7W7xV8Uyi/OmvyTnPHj0rs6x5O2l4UGSCda+j/3Wnb1/7p3aeql9fbjjb4N/AVx6OEg=

RNG Seed: 967421944

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	...

**Comment by kayla-glick** [comment]
Sent out a fix for this! The code was trying to apply a modifier to Quick Strike without the ability being available because the sim used dual-wield. I changed it so that quick strike is available but not usable when not using a 2her
