### ISSUE TITLE
Missing Strength of Earth Buff? (ele sim)

### ISSUE THREAD

**Issue by t-mccawley** [wowsims/sod#108]
**Describe the bug**
Strength of Earth totem is placed in "precast" but when reviewing the "results" tab, there is no Strength of Earth buff. If true, this also means the strength might not be properly applied to SR.

**To Reproduce**
Add SoE to pre-cast, sim, review buffs in results.

**Expected behavior**
Strength of earth should be displayed in the "buffs" section (and also apply properly to actual stats during encounter).

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/sod/elemental_shaman/#eJzj4uVgMmC0YExgzGCcwMToxKLA6MAoxCA1h52LLSAnsTK1SIBdQkOBXauJkYtF4NQEXiD5sAlEbgeTa+bwcnELHG7ilXjEpvHtmwQXu0DvTEaJy6xAxmI/jVXfJbg4BM408Wr8WSUJZF0Dsn78kgRquQXU8p1RY9J/SaApi8FmHZgBsuMxmP3rMw+QXNQMYjd8AbF7JvMa8QkwezBGMFVwNjByLmBktJrLzPWCiWEU0AUIGZCq4xUTgxODF7+xqYGBsaGBqZGxgZGhqWEARwRzEkPWbCYJZi5xLk4pdi5Wjv+BGkxKXFwcXGy6ZnoGpsVwiYf2GsxQCVMUibuGGixQCWM9UySJ6YEa7FAJI5AOIVkpaS5BLX4OFiGmJAaQEi5mcwNVKTYuFg5gUhRSllLkEtMSAUpzZoH0nw/UYJECquFiNJGC8YWUpBTAitgwFBmBDQKmcyGg9SAhjmV1QuIcjFLCXBybGCF8sDmL2DWYhKSkJLh4lbi5OI1gfoB7RohbCuGBghOMnYyQQDRxmMXI0MXEI8UlxcHBKMAowaTApHSKmRMi6+cgCGGIOEjOmgkCJ+0tISIX7BXTwOCavdEsZg5g1hPi8EktS81RMDGQ0FLg0BpkWedDowNVzOFaQJE5AlL/qeMOJGAIJh36HSwz8z+0ngy5au8IlXGIYAQA5DB/AQ==)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rosenrusinov** [comment]
Selecting a horde race from the race selection properly shows SotE buff input

![image](https://github.com/wowsims/sod/assets/5707996/07055589-d10d-4fcb-8c10-a814e8562fc0)

I'm not sure how it works when its not selected as a raid buff and is used as part of apl on the Shaman sim tho

**Comment by t-mccawley** [comment]
@rosenrusinov was it added last night? Yesterday this buff was not available on the ele sim:
![image](https://github.com/wowsims/sod/assets/29646748/e22b1ebf-a3df-4450-9dc3-2700eb0d7c97)

**Comment by t-mccawley** [comment]
Also note that now even when the sim is run with the SoE totem selected in raid buffs, it does not appear in the Buffs section of Results nor noes it appear to add mana regeneration to Shamanistic Rage (which scales off of Attack Power).
![image](https://github.com/wowsims/sod/assets/29646748/8e55fef8-11d1-459e-af78-2f0d431f2546)

without SoE:
![image](https://github.com/wowsims/sod/assets/29646748/d75294c8-2760-47c9-802e-3cf6ebefb2a4)

with SoE:
![image](https://github.com/wowsims/sod/assets/29646748/2b048aa7-ee29-4bf1-a830-b3a16b5d106d)

**Comment by kayla-glick** [comment]
This PR should fix the issue! https://github.com/wowsims/sod/pull/139
