### ISSUE TITLE
Envenom AP scaling should be affected by DP stacks

### ISSUE THREAD

**Issue by thomgoertz** [wowsims/sod#1082]
Simmed Envenom damage does not align with in-game numbers.
I discussed this with Ra. This issue serves as a reminder.

The sim uses the formula: (if I'm not mistaken)
`dmg = 0.8*(107.96215*min(DP,CP) + 0.09*CP*AP)`
But in-game numbers suggest:
`dmg = 0.8*(107.96215*min(DP,CP) + 0.09*min(DP,CP)*AP)`
Where: DP = deadly poison stacks on the target, CP = combo points spent.

In other words, the sim disregards DP stacks in the AP scaling part of the damage calculation.
However, in-game testing suggests that DP stacks also matter in the AP scaling part.

**To Reproduce**
You'll need to compare in-game data to sim data. The most telling test case is a 5 combo point Envenom on a target with 1 deadly poison stack. Assuming around 750 AP, the sim predicts around 357 Envenom damage in this case - but in-game I personally observed 141 damage.

[Here](https://wowsims.github.io/sod/rogue/#eJztVl1oHFUUnjszu3v3bGYzOS51ctvKdixlWEicnd1NmyjumtoHq20S9WEJolQSpX9aXBRUBA0VUzXUFhG7KBZECxUfuqQVAkoJCG1RaqSWQltU9CWShz41UVvqvXdnNpNNqg+tPw+eh+Xcc8/5vvM3swNKr4IKO4MQ7d+x5fnhZ0xq3ZWOZj4hkDDHZgzr54QzeoSBbn79mwEx881pwzrYze8+mDOsqajz7lWLH/Zy609J5+K4OLzODxeTzl4elTD38MP3SecMv6Hm6LThvH9U+IxNS+TzMqA6I32uzAmfL2YN57Xdy7n2Edfe4ppmju3k/OdPC/4Ts4a1O8WVo3VFN9+bNTztW6L0nNXhB1X5X/5WwUvk307hn5ZfVP6MbFzpuoWcl8u62UIh6+Y7XC+Xcwuey6XgZvtJWX9c2XY1YWnQBrFtEdDo74YdBR1UtwK3AmVcpxcOEjsOMYh0ZDsLFYtACqITRENSsClwhw5pxRRDSNotADXCfTmQo/co2M82wwa2HrowD/HDusCbutwOKzKMatg6SVpQNSMQFcb0EOMZAClA3OYIp3SVpuZVEJfmlTvxfnYflPDuZq5Av5x3VEiz28CwEwHj2/ypNmoEJJc8SrB3HsJBVr5xMC9V75T58j7D16b2ETxN2FcEjhP8nIRjX2IvQpvd2oQBLnZCskYS0hShb5SdqN+l5MQCK5PzyVYgjx6gbV4nqmWCxKVVowfKTA5KjA/MTJJGURshSr3beWmJoLpRqSOvq4Sr5XNhMR8ZByhhm6AXS8GteF2GWifb1UyQhbZMK7cIAu4EWtatsMAbH+WQg9CHm8KkAtbKLONVwEQDuFH30hVE5yvw3Hn8e1kvdOPaAHn01/Y6UY0ERxFMQnB8/arykr/nhYUeT+KzrAKP4CCsYCwcGkr5r5BgZWY5vzQniSGnEqMXyukhR/c9vVsgJsl+fMp/6ngMDrA+2IDrJbC2APjP0WSAjuoLfkPWFiTk+Fy7rGQrPrkgdd7txT0VjUue0hN05povJNw5UdKyTIqzxA8THzyYt+9y6BXSqGQn2w5b8LEw5YOsf4mOrUZ7iWSaE7kOc4POYy6swdVBH4LFyC1eHq8R8yVhkwQ+IzhOwml+TNiHxAcKL/UA9kEPW7coNUFLq7qY5bHtQGvE16TfuXk/8VDwme7XlcZiZ9DhG9NYp6YdDdPn/JVoVNZVkXXwLxa8g3XA7bhqqQkvgAgCdp0gcyqpEmVE5a2iQ/akFq//h2wutdWVzlJ79YCQk8XuuuWb4qonpJwtevs1em7EQPrA8HPDO9JdrlVMa5n/2EeNs6d0U3DWfHpDOCa7dnPy4JKVv7sOlbq3Pn3p1ZMPf1e8x78plckfOUVnYw==) is a quick example setup that uses no talents, runes or effects that impact envenom damage. Make sure the player race isn't Orc.

**Additional context**
In the early parts of a fight, DP isn't stacked fully yet. Especially the backstab build can struggle building up DP stacks. This can lead to Evenom simming for too much damage in the first 5-10s of a fight.

**Comment by kayla-glick** [comment]
Hey @sanguinerarogue could you verify this?

**Comment by sanguinerarogue** [comment]
Verified in game
![image](https://github.com/user-attachments/assets/b43193ed-69aa-44f8-9143-19e741062edb)


I will get a PR up to adjust tomorrow (hopefully) and will leave this open until then.
