### ISSUE TITLE
Balefire Debuff

### ISSUE THREAD

**Issue by AberrationIV** [wowsims/sod#1084]
Hello,
I wanna report a bug in all my mage-sims.
The Balefire Stacks never get higher than 5 i think. Maybe less.
So my rotation is off, and the sim casts balefirebolts too much.
Best Regards, Aberration

https://wowsims.github.io/sod/mage/#eJztVV1IFFEUnjsz6uzRHcfrKuO1Yt2wpq2t2Vk3/Cl28iWTQqECnyIlo8JQFKLeJOxHxJQsIUksX4pACJ+qhxLL0oQoKbEEiaSHepIKsqc6Mzu7ipUI2c9D52HvOd8997vnnj3nDKRJvE7yySEyzGuNPLTzpNh9nSc3eaITk8wSQjn2UobE8prKE9X1iqRu8Qr+XgLJyqNWWR0r0u5fZCAql9tkSFK622S1z4N7F1pktSdde/ORodGD6LSsnbmjojGKpyZl7UknA0l52CprjQhLygPUPnVmocNwlHbKNobQaEvSJm2fjs9urbUpG7V7qLWhJipdLTL+Tp+2bn/eJKvD6cAh0D3rNjIkQRFL+Ap+PznuOUsSrhBhjHCF4yK85rn/8luFzpC/HcKflvc8Vwz52DPlpILUkVKvEdDDYSOo67qh66GAoYfCqIUQCIWDejhYnlwhVHFHRpNUATLBxZIgQXpXrYk+F6AayNsQboB0kFgiiBK2iw9BEAKhhrjzUJkGjrOBznQFY5DmT5VEyldxzHYPhnMZLlLHPgosSoU9SWvZUdhLd4PrhmhBVmdm+j0Soa5B4gDWMSBBUP2ZSJg8SCRItMLwkuhOfuyw1cmOeve2aniciFGfi50eYFVQSkuW68L4LfYYid9SxnZBHjWWcovblxxzw7FjZMxLqUOIc42WshLQ6calEM4jiwVnzbM5rh1sO2ylReA6L1jQK+RyzkzOqdZ7fpqA+Ds3sQCspjmLU00NqMxZl3YAw42FTVeybEijqdE09dtvvfoluo1rvJYsPYOlL3BRPpyTfwTjlKYi4ws5up6tAy9dFaXvjTnNNzFjduHeqqRrWS5k06xYmG+xsFJ8+C8ZjsWclWazLJB9KQD9JNZL8aaiBtNBpZnzHrt41VpZsN/wfXIYUxfUT7x26oZJszP58sxZnow4XxrJfOZoBeYET7oI95hgKiTeNyC4bHyg3kyLenjMrK5LloxECqLI00jOQVvGI0a7IE2cdFNpZ/Wx6hrvZl2N+P+xz5nWbC4Lz5q+X+JR2NfliQMlaP/WXTMLDtfOnBrZ8yKyzdkxK8g3zCMa2w==

**Comment by kayla-glick** [comment]
Hey @AberrationIV 👋 Balefire Bolt was changed on PTR to only stack to 5. I updated the default APLs to only go to 5 but you'll want to update the custom APLs you have or switch to one of the presets

**Comment by AberrationIV** [comment]
Thanks for the info. I will wait for more Information about the new balefire, before I continue writing my own rotations ;)
