### ISSUE TITLE
Totem of Invigorating Flame doesn't work

### ISSUE THREAD

**Issue by Arbatrax** [wowsims/sod#111]
Flame shock is showing as 225 mana which is 250 minus the 10% from Convection but the totem doesn't seem to have any impact.

![image](https://github.com/wowsims/sod/assets/6878382/a9316bf7-4124-441f-9b46-cdf04dd23d8b)

**Comment by kayla-glick** [comment]
Hey @Arbatrax 👋 Thanks for the report! This is one of the many Phase 2 items we haven't had a chance to implement yet. I'll leave this open so we can keep track of it though
