### ISSUE TITLE
Mandokir's Sting is not procing on melee

### ISSUE THREAD

**Issue by Hansson921** [wowsims/sod#1116]
Mondokir's Sting has a Chance on hit "Chance on hit: [Unleash a poisonous sting that deals 200 nature damage, and hits 2 additional nearby targets.]" This does not seem to sim properly when for example the Gurubashi Pits Fighter's Bow has a similar text "[Chance on hit to increase Strength by 75 for 15 sec.]". I believe both of these bows are able to proc of melee attacks

**Comment by kayla-glick** [comment]
Hey @Hansson921 👋 other hunters have confirmed that Mandokir's Sting does not proc from melee attacks in-game
