### ISSUE TITLE
Rogue - Threat modifier for blunderbuss is incorrect

### ISSUE THREAD

**Issue by fynnen** [wowsims/sod#1132]
**Describe the bug**
According to the sims, blunderbuss is assumed to have a 1x threat modifier, and 2x when Just a Flesh Wound, Blade Dance, and 2p tankslayer are active. After some in-game testing with Tiny Threat and Threat Meter, it seemed to have a base threat modifier of 2x, and 4x with JAFW/BB/2P active.

**To Reproduce**
1. Go to [Rogue Tank Sim](https://wowsims.github.io/sod/tank_rogue)
2. Simulate without JAFW equipped
3. Go to result page and compare Blunderbuss damage done with Blunderbuss threat done, it is currently behaving as: Damage * rogue threat modifier * 1, doubled with JAFW + 2P

**Expected behavior**
Blunderbuss should have a 2x threat modifier, doubled to 4x with JAFW + 2P

**Calculations and Screenshots**
## Blunderbuss
Those numbers are generated by hitting the mob with blunderbuss only. JAFW, Blade Dance, and tankslayer is not equipped
| Damage | Threat | Screenshot | Assumed threat modifier |
| ------ | ------ | ------ | ------ |
| 334 | 474 | [Imgur](https://imgur.com/v7m0Qob) | 261 * 0.71 * **2~** |
| 391 | 555 | [Imgur](https://imgur.com/gpktOAl) | 391 * 0.71 * **2~** |
| 356 | 505 | [Imgur](https://imgur.com/z6vHrNI) | 391 * 0.71 * **2~** |
| 703 (critical) | 998 | [Imgur](https://imgur.com/grvCTAh) | 703 * 0.71 * **2~** |
| 644 (critical) | 914 | [Imgur](https://imgur.com/3jYHvum) | 644 * 0.71 * **2~** |

## Blunderbuss + Just a Flesh Wound
Those numbers are generated by hitting the mob with blunderbuss while having the Just a Flesh Wound rune equipped. Blade Dance is not active, and tankslayer is not equipped
| Damage | Threat | Screenshot | Assumed threat modifier |
| ------ | ------ | ------ | ------ |
| 261 | 982 | [Imgur](https://imgur.com/L5xJWct) | 261 * 0.71 * 2.65 * **2~**  |
| 302 | 1100 (rounded by threat meter) | [Imgur](https://imgur.com/d6Bk3O5) | 302 * 0.71 * 2.65 * **2~** |
| 589 (critical) | 2200 (rounded by threat meter) | [Imgur](https://imgur.com/JsvkTtM) | 589 * 0.71 * 2.65 * **2~**  |
| 272 | 1000 (rounded by threat meter) | [Imgur](https://imgur.com/1FjKVwZ) | 272 * 0.71 * 2.65 * **2~**  |
| 222 (39 blocked) | 835 | [Imgur](https://imgur.com/ReW0SiH) | 222 * 0.71 * 2.65 * **2~**  |

## Blunderbuss + Just a Flesh Wound/Blade Dance/Tankslayer
Those numbers are generated by hitting the mob with blunderbuss while having the Just a Flesh Wound rune equipped, while having Blade Dance active and equipping the 2 piece tankslayer set bonus.
| Damage | Threat | Screenshot | Assumed threat modifier |
| ------ | ------ | ------ | ------ |
| 355 | 2700 (rounded by threat meter) | [Imgur](https://imgur.com/txFmXG9) | 355 * 0.71 * 2.65 * **4~** |
| 376 | 2800 (rounded by threat meter) | [Imgur](https://imgur.com/3YvCAUd) | 376 * 0.71 * 2.65 * **4~** |
| 370 | 2800 (rounded by threat meter) | [Imgur](https://imgur.com/BzSERBN) | 370 * 0.71 * 2.65 * **4~** |
| 356 | 2700 (rounded by threat meter) | [Imgur](https://imgur.com/McLNTKG) | 356 * 0.71 * 2.65 * **4~** |

**Comment by sanguinerarogue** [comment]
https://github.com/wowsims/sod/pull/1142
