### ISSUE TITLE
Phase 6 - On-Use and Procs

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#1140]

**Comment by adocoD** [comment]
Following are weapons and armor with special effects that need coding in, or trinkets:

- [ ] + weapon damage refactor (make it a base stat)

Weapon:

- [ ] https://www.wowhead.com/classic/item=234067/manslayer-of-the-qiraji
- [ ] https://www.wowhead.com/classic/item=233509/staff-of-the-qiraji-prophets
- [ ] https://www.wowhead.com/classic/item=233515/hammer-of-jizhi
- [ ] https://www.wowhead.com/classic/item=233621/kalimdors-revenge
- [ ] https://www.wowhead.com/classic/item=233634/deaths-sting

Trinket;

- [ ] https://www.wowhead.com/classic/item=234080/eye-of-moam
- [ ] https://www.wowhead.com/classic/item=234092/fetish-of-chitinous-spikes  (Tank)
- [ ] https://www.wowhead.com/classic/item=233570/petrified-scarab (Tank)
- [ ] https://www.wowhead.com/classic/item=233580/badge-of-the-swarmguard
- [ ] https://www.wowhead.com/classic/item=233627/jom-gabbar
- [ ] https://www.wowhead.com/classic/item=233628/the-burrowers-shell (Tank)
- [ ] https://www.wowhead.com/classic/item=233639/vanquished-tentacle-of-cthun

Neck:

- [ ] https://www.wowhead.com/classic/item=233502/amulet-of-foul-warding (Tank effect)
- [ ] https://www.wowhead.com/classic/item=233572/necklace-of-purity (Tank effect)

Finger:

- [ ] https://www.wowhead.com/classic/item=233507/ring-of-swarming-thought
- [ ] 

Chest:

- [ ] https://www.wowhead.com/classic/item=233575/robes-of-the-battleguard

Legs:

- [ ] https://www.wowhead.com/classic/item=233505/leggings-of-immersion
- [ ]
