### ISSUE TITLE
Add more resistances to Warlock Tank sim (SoD)

### ISSUE THREAD

**Issue by adam-tj** [wowsims/sod#1155]
**Is your feature request related to a problem? Please describe.**
There's only fire resistance in the stats section of the Warlock Tank sim (SoD) when there are other encounters which benefit from resistances such as Huhuran, Twin Emps, Sapphiron.

**Describe the solution you'd like**
I'd like Shadow, Nature and Frost resistance to be visible in the stats section

**Additional context**
Two of the upcoming bosses in the next phase (AQ40) have benefit/requirement of resistance gear so it would be beneficial to have this feature sooner rather than later.

Thank you!

**Comment by kayla-glick** [comment]
These should be added now
