### ISSUE TITLE
Crash Report -1639850081

### ISSUE THREAD

**Issue by DreamingBeast** [wowsims/sod#1162]
Link:
https://wowsims.github.io/sod/retribution_paladin/#eJztVU9IFFEYn29m3J196jCORLMjwXMDe26szO6y4Gqw4wYhESgVIR2CTUd3atuV2VWrWxZhCh0MyQxEEC+BdegmHYKQ9BL+QfFQanmLIBVKCQ+92d3MoFuGHfoOj+/7/X7f7/vg8WYQWw1RRmbUxy7kaEzEbhiWxCknMO8dA1QozQ+IyqtaMj+oIl5afiAipzRLoZEw5Sb6RGXWQVY3VVosUnRNJB82FFrcvS8q70SyNGgzfbQYdZKddQUJ0syASJ7esuE52vC5lEyt2w0LtFgRyThlBGlsq5j03ymj2ZtekezcLqOj1/pFem5+K6YLfOkWlU8iYigw+VAMKJKTQDWrs/Vw3dkDBSPAvQSYA6ZmmUerLPM//mrI23DQKxxUfGSZaHE16FAPjTAIEIfT7pCmhTS/L6QFfaFAIKgFQ/6ApgX9oUa2ibvMXOljFQ4dQoLqQLzwdUPxuJATFfj8VaE0hZEqIIcwOQxE8FAYcb5gWuZVtoaRj6rlqNRbIvAy18sztg7xdlcA5c2eDYPsU4+jMq+bigonYNcqJ9ZscdHeEXKlegy5vYep3DUB+YX2iNHPNWWPipEsS8g1BPlhiOsF5pfp1Dqbv3/i3s3ps5eL1NzQF6NACnYZ+qlon4JtFqbzb1TQZ/NZWF9iYQiYOXCovMBJ4NniXTnqkl6SS6p099AjO6Yj4RwyEylvzcZiJPCaF94ackU0EWu+2mUm2/CZmGnhCzEjEUtnrFj6Js7EDXwyZVkd7RklgjnvP/alIPf0ffGpGP8jn3h3Q92+7EHDnz17nuvhIxdbalcaFiI/rPUmsAZAABmfN68ZONphJe07q2uxjGQsYSYNfNZoNsxOo8Wbqk914USKsmYyk8reYqvZFs/8rslM42Z63TiVzOras3+3KnzKtCiYZagioKUxOWckjOYM1jC1TBqdhoWt3MDK76LG178=

RNG Seed: 2678635758

Tried to add new aura in a finalized environment!
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:56 +0x10
panic({0xc1720, 0x311ed0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*auraTracker).registerAura(0x308a6c0, 0x308a000, {{0x2040f9, 0xd}, {0x0, 0x0}, {0x4efa, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/sod/sod/sim/core/aura.go:376 +0x43
github.com/wowsims/sod/sim...

**Comment by kayla-glick** [comment]
Looks like this is caused by Sanctity Aura not being initialized during the sim's build phase. I'm trying a fix that calls the `ResetCurrentPaladinAura()` method during the initialization
