### ISSUE TITLE
Crash Report 963122919

### ISSUE THREAD

**Issue by Ashram1982** [wowsims/sod#1167]
Link:
https://wowsims.github.io/sod/protection_paladin/#eJztVF1IFFEUnu/OuDt7q2EcrcbRYNsipqWV2V02UoOdfJKI2IcCHys0LIQkIextK6u1wCSQTCIUhUTUBIOkp6Wn9aFSoZCg8KciogcLDB+EOjOzaQ89lWAPfQz3nPOdn3vmcu7lEZmpsHAANjuBBuTYEOtiSLO6DEMHwyh9wDhYDqyHoXqvDBUZxnQMuE6b3HXjjDWghWWAHFADissxVFJdTTCGAtyXajx5sf68KuoHg1J4CHyTutCp6E+rzGddBpfUwV6F+9U5okaKyXetV9GnfOb0V4OMD8QuKObSSgkZ7e2K/kYxJxd1Mt6Rp89vviBDVmc7FfP5SinR817lJTemkxJu+c3hSwbFPOpRzNutpaSN9SvmaGsZbZ3pV2i95zYwckXRPzvK40FFH6si/v0dJbaPfpiZzvmghrX409iRAe+gw4CYBaYhzECaBT4Ci0DlW4nPMsFBOmV70vZk9rgnhXhe/sefQlvGRrewUfjEhGpDZToL0kQOwBlKpNAFOHe3CYf1iJWIWzErHk9YVjSRiJLtWilWK50Szs5DF/lWLhs+LsnfvuihAPfzgki83Grm2zk3ZO6Ts30wxbwjWp5o5kVevJq+roSI5GIk2qxJBqsUtF3GTl4ULpQlTbwhCU46l5ycGF/bQ6Oyrk73dlWfGyzRdhshvi1cTMmBJ3DIgZtlBpXniK01spqx9Es2vQ3aZoP/JurhfTTlkAba8jNSbC8zTHh3UpDtqbxWYc8wdIMFfa9BubKoOmdZEMqKAS/gqF34s0BJ910HE8kKj5lM7jzt4lUy1iHKM5e3aPKR+gv1jcH9lp4M5x+AfwVmm70udfYM/1Ud1fi+Pn0Qou7a9MCuOHNu8erEsZfJQ3mPXYsf06axHg==

RNG Seed: 1080407613

MaxStacks required to set Aura stacks: Holy ShieldPlayer (#1)3
Stack Trace:
goroutine 28 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:126 +0x10
panic({0xc1aa0, 0x281c730})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Aura).SetStacks(0x2966340, 0x28e97c0, 0x4)
	/home/runner/work/sod/sod/sim/core/aura.go:199 +0x33
github.com/wowsims/sod/sim/paladin.glob..func24.1.1(0x2966340, 0x28e97c0)
	/home/runner/work/sod/sod/sim/paladin/item_sets_pve.go:370 +0x2
github.com...

**Comment by kayla-glick** [comment]
This is caused by using the tier set that makes Holy Shield not have charges. Pushing out a fix for it
