### ISSUE TITLE
Crash Report 670021755

### ISSUE THREAD

**Issue by adrianveen** [wowsims/sod#1168]
Link:
https://wowsims.github.io/sod/warrior/#eJztVE1IVFEUnnPfc+bOtfd6XSd53rJssrgIE2/GRtSCebmSiJhFC3FlgaEhJApRuzAiy0VDC0lBsOxHgiiEEsRkgiItCA38gQqLVlYLa9E/2Xkzb0ajdtnPorO47zvnfuc79x7uOyxAiUFsUgftBBIErhNIAlTlmWBDnDTAKEA19BIYJcA9oi+XeeNNe4/UtxiKub3IX3IJGDU+JjR55qHJVKPjtI7r8JzGco2hDt2c8MoLbwQ6I526+UKXsw9MdAbRearL4RPOzu05zezzySc9Bah0770m7yDCbOSMb5P3PztOEjmzunze6XAGO3T55dgaRBeRfQuRapzvAVzfftKYz7iBdV/rCB6fSgHVuPtOiwQNn4RyvFQDHPYdBbUdaC8oeNVHoFIwYAbUyimVPSOe//Zbjc/D3z7Cn7aXxFPFy6Ef8PlVQxzOAtThO9xZGLFKrajlrJEQgqhlWdFoJGqF8RuOkxp1n+fAV8VUGGc+kcMU2pUX9DEEodLWbKw7E4s4MSq8TKWvRiCIX0ZCpSzg8vrrgn6GzFB4S7SV5bNcgS69VlsEkroK4VbuF2n2QiADjbZGzkRaF39ZnktBZBS5KkilJ5s0qHFNLNXlxUguYgHOmVGiUy8nLR6ROliZJSjz0pvnQObwSlHO1vG1jA5A+kY/siP5jC1muNfEgZDKXc8LmX8A3NBPkld/l5zpGy8WwcWa2QpTQyDVJRUc1qJ6VitNy2ptEhuZyfOZv1t1mNM4xdwkhAL7SydrpcqxOynntuNk+pbQsh3GCclXiHSF5DRIpXkUPhAYc+cStSdcVGHPEOgGzxWyUmj+dGyrbUK5Ekwqrr/bXpUG0i7o7nJsLFaRjozHNuxP2VQsklDoTJvG6a76Q/VNRWWWGSv5x+agPGkvi87mq7+kY4iF5TkHWji1Nl+2KxoPzh8f2zMZ2+Hu2DXwDfykwMs=

RNG Seed: 0

runtime error: index out of range [31] with length 30
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:56 +0x10
panic({0x173060, 0x285e3d8})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.NewCharacter(0x295cc60, 0x0, 0x2a50600)
	/home/runner/work/sod/sod/sim/core/character.go:192 +0xba
github.com/wowsims/sod/sim/core.NewAgent(0x295cc60, 0x0, 0x2a50600)
	/home/runner/work/sod/sod/sim/core/agent.go:173 +0x1e...

**Comment by FelixPflaum** [comment]
Seems like cached data that is missing a new stat field. Try to reload the page using shift+F5 (Chrome) or ctrl+F5 (Firefox).
