### ISSUE TITLE
Crash Report 436937365

### ISSUE THREAD

**Issue by rbb121** [wowsims/sod#1169]
Link:
https://wowsims.github.io/sod/warrior/#eJztVE9IFFEYn/d2dvfNt+4wPf80Pgts/cOwoM2ujO1KsJN0iAjy0EE8RAVGipG4EHRVInIL6yK04CEviRCVhIZYWRRldKhAE6KooyVRHcrqYN/MzlhEdMmwQ9/hze997/v93u/Nm/kANGrTy5RME9IscUk8j0CopWv/sfYeLahvrVTi/QSYdnMhasycECBruQEVx6mFKGYf5lTjylsBYe3qbuPZYDmmJgZVYwoLmTaF6O6Qg64hujPkrPYNIPpaDhFttl/VB8LGK5d09pRqXO+rQN17ORUC2unDCD98iaLwcE7VF1WQnJ0/RpNhg6ToEyI1vZDhJZX+x18NvkTW2sJaxWsqNSsjhOwgreQQ2bkxaTaYloljQ7LOcoDpTC0zgc9Ei9JKD0idn2U9ABzCIggBtlwSCwOCOisLxcBECGSGX7uXTGah1Eu+uUFiCmC6LlGPtT4/X+yVJrI8KUyo5dWg5GWHMb9UAevjpUzmyiTxEo4U0Iasvw9PiM0/chY//cTBxAqnsB9XhG/dh1pvh7t5Da8CZdQVcn7zsniJI9SJBtl4m+GWAjGFP19RGtm3AieivFZUgxA6sDFSyEBRDIANezPXOvYOLgvaJPHtohnSfIt/gPejGyAai4AyRvypB50eosVVdER7JO9Mln8mRyXFG3+j4rnJF/9CxH+ZKdEIcW64FaHvFZYFJXGOnOBtShkV7oUl6y3BIMTGzxMjyHVRBopzkw+wggi8aHaprZIYjEeE4r6wW22GzIsEuKS5SYKzGlEFOi/zTT/F3ukZRuiSZh0SUlyH2GW775MlSma8jsjsxx5K2/OU5Ik0SkNC1kkqEJsOKIWlvfa6Aqi3y/PnnJjJpAuZR5lNB92YyyTPBNh8b5SzXe1H27sqG009E//HGq9x0l4VndqLf6SjieXV8YGRcMfuC3a648i74zN7ZjPbvBW7lXwD2mDB9g==

RNG Seed: 0

runtime error: index out of range [31] with length 31
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:56 +0x10
panic({0x173060, 0x285e3d8})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.NewCharacter(0x2a8ea20, 0x0, 0x2a52600)
	/home/runner/work/sod/sod/sim/core/character.go:192 +0xba
github.com/wowsims/sod/sim/core.NewAgent(0x2a8ea20, 0x0, 0x2a52600)
	/home/runner/work/sod/sod/sim/core/agent.go...

**Comment by FelixPflaum** [comment]
Seems like cached data that is missing a new stat field. Try to reload the page using shift+F5 (Chrome) or ctrl+F5 (Firefox).
