### ISSUE TITLE
Crash Report -1158861767

### ISSUE THREAD

**Issue by heck1243** [wowsims/sod#1174]
Link:
https://wowsims.github.io/sod/feral_druid/#eJzjEuZgUmDSYDJgtGB0YEpgLGCcwMToxCfBGMAUwbiB0S2D8QQjoxCD1Hp2LraAnMTK1CIBNgkbBUatlYxc3AJvF/JJXDHX+LlLkotF4PckPi52gdt9fBLrRIByp+bzSVxk07j2UgrIeQ9U+JhPY+VnCSDnLlDJXT6N/8slgZwbQE6LiMZuoAyHwJ0+Po2vu0DC74Aa9ltrbAFr+ADk3OfTmAaU4RA4PZ9P49t1aSBr2UI+jQkt0kCrZy/kA5Jd7SAHnATa+wbEPfKTF0g+Xc5npMLBJMCkwQj2I2MFSwcj6wRGpgWMzAcYGS8xskgwKjDeYGSxesbC9YCJYRTQFAg1jPggfsXE4MRvwbiCEZgYPRgDGCMYExi9ZE0NgMDU2MBQ1xTENDIwNjI2MjAyNDXUNTQN4IhgSWLIYpJgLDjB+IOJ8SQ0EDkcLkJZlg43mBhnMTKsYmSTYhFIUWBUOsjMCZGKcxCEMPQcJGfNBIGT9pYQkQv2imlgcM3eaCIzx51UIQ6f1LLUHAUzAwl7BWatQZYfNDodqGKO2lqKzBGQ+k8ddwCBIZgsWO5gmZn/ofVkyFV7R6iMQwQjAHQKeXE=

RNG Seed: 1677199731

runtime error: index out of range [0] with length 0
Stack Trace:
goroutine 43 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:126 +0x10
panic({0x172e80, 0x3134360})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/encounters.(*VaelastraszTheCorruptAI).Initialize(0x2abdf90, 0x30ad000, 0x3176960)
	/home/runner/work/sod/sod/sim/encounters/blackwing_lair.go:71 +0xd
github.com/wowsims/sod/sim/core.(*Target).initialize(0x30ad000, 0x3176960)
	/home/runner/work/sod/sod/sim/core/target_ai.go:41 +0x2c
github.com/wowsims/sod/sim/core.(*Environment).initialize(0x29b9400, 0x2bd5000, 0x2a96690)
	/home/runner/work/sod/sod/sim/core/environment.go:119 +0xd
github.com/wowsims/sod/sim/core.NewEnvironment(0x2bd5000, 0x2a96690, 0x0)...

**Comment by kayla-glick** [comment]
Caused by selecting the Vael AI without selecting the Vael encounter to input burning adrenaline time. I sent out a fix
