### ISSUE TITLE
Crash Report -74087555

### ISSUE THREAD

**Issue by vileskin** [wowsims/sod#1190]
Link:
https://wowsims.github.io/sod/elemental_shaman/#eJztVVtsDGEUnvPPdHf2yI7pT9vZvyq1qMkmy15M0yJ2kIiISCse+ohkpZqGxibCi9QtcUmq4kHUS4nQuDYVIuJB+tCoJySkwoOIiBCiHqpEUuefna1FPSGRcB5mvvnO/cz5Z7BcZ9UsAXXQDG1wm11g7WxzJ4OlFRb0MOhl4MIQQBP0wvJm6GbAFfEojIGG1vU7slvNoLWoOhg7CqibVzoMe+x8BDVzzymDric7DGLvHDLsj8OC0FXSj4xYhPpfhe3rlyV3ibhzHyTXS+jzuQihPkL9HneT7EZHJRqgKB17Kwl1nzbsTkKa+fYEoGruzmLQvNZjWPunErh/1LCuLCTlo2NGKqqrpiY7c2EFa2LbsR2q9kNJN6g9APdBGYLAghcaPmXKf/mjwtv/+RG/YsrS0jqgxaNlhAY6T+vouK1MOIlEOvFV4k7iW4k7jjQg2nHSSSdJnuoGpaUnYKlYhiERxBL9VqMdjOoYQC2eTOQwguE+QJ/nUF+kKkMU9KQfHgBbjZIvqvG6HFb49BGiS6IhJEW8dq6Tw6l+hl1rbM03J7bcZwca7YBvnS62frnNRt86leNVohJLY5N1jbMNivDoWme2oJL00U8RTpk9vPe94JpgCxQ+U8zAiliZHuDYD4X+BLkh1ElTc7jD4LaowSpeiZiShV94DnYAw9FJGDoFMhp9U6SHfmYnXywWYZLPw1CX5jtjqA8KUCbSeOhGgZAJkKVyXiOX5ABrxCy0YuW6yrFlPFfeLJ0T4wyfLqahGTOobPUZKPl6nSK9nMP3+pSX5g1Nl88Rs7EyFpFdF6UJdbFCO/6dzxLRn49nvOppQkxQjYzxesSasNZUUa0TeafHvZeJJVjL5+fnnZIpH1MH3ksOcLbSf8ly336MUbCeIIhcp++DpP0g2g9Dk9Z8kvi6cbxMTEFvGzeub81lvWqfdEPbbTgA+TM41x1lMOh/inT3no/q3SEGXaAcZEwo0VtqKE+vdksLbpGu41IGM/V55m5mxkZPHmZSnao+tDvM9VXZbdnW6tqElYn9ZT8U+4D7W+LUXPylOKYY+z11kCS9a9tZt37Tlnf7Btc+yCzxNW4TfAF1IOxj

RNG Seed: 3178075124

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 10 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:126 +0x10
panic({0xf7020, 0x14143a0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/shaman.init.0.func10.1(0x2afe000, 0x3023400)
	/home/runner/work/sod/sod/sim...

**Comment by kayla-glick** [comment]
This is caused by using Totem of the Elements without the Elemental Focus talent that provides clearcasting. I pushed up a fix
