### ISSUE TITLE
Crash Report 1927762608

### ISSUE THREAD

**Issue by FrancescoZinnato** [wowsims/sod#1192]
Link:
https://wowsims.github.io/sod/warlock/#eJztVl9oHEUYv292727vO267mYa6maY1nqRur+Sc3XSTS2K5TQSNpeo9+BAJ/gtGW6kYelDiW63xT0ElUiiXItqU1CY2gZKHpkofjFBIRCQVWvKizZOC+NCHqgUFnf1zyd7lKkIjCDoPdzPz++b3/b6Z75tZbFSIRnTCIQf7YYFMk0mAEoEjZHiUQE+DAjpMEjhPBO7AEsB5eH4/nCJAI+ziZowVDj736uAhwfBAk5I5A5jUznyk6l93GfPvMpS1+V9TGNemTqj6TL3APhxX9Uv1xsc3mRhMCMOVLmOu1CAGYwL5ocu45g2mhf3FemPmio6KNj6uGl8ddRec9plv/ebajPurLwkqRbt+VjXeH9kqej9PqMZ7oidrb02o4ve7N1Uh4KeSqi9sxoiYWDmnWk1KQktw6JUL0EeGt78N0VEgp0D+BiLLEL8B0c7vZVwhkf/bP9rokf/8Fv9IIj26AhrJgag7B3qhACWAZ0UtDsHebdzm3GqxWjnndgu3bW5x27QsMTJtsyD1JQciL/2e1CXcggqLoayI+kkjKhhrsbKWXaQdrB3vpy1Yl9mkxCjZG2FxjKJk2kVvSqZkIJhqt5sx+iUhisRkJHqKdrLc31zaxleXipH2ywDNsz3YSk1MfCK7qtwirUtvwtQsICVaVEyV5rZWM7fxoheDgGg3y+NuaoUJaFpDdRaSHkFUme83YjVIXSoPoxbj2EzvxVQ6+Rc0l/sN2VvjdqjMSGeE3s22lUNcjTprM7GrytxxENQ1DFoDg9ffcQ1s1ooG3YE0oykSlWblwCrHOWoZNYhaSEJics/9lCv5cfYodtN8Wa57hQZd98a8jzWjTrcEW+3HNQsu+oVrmI6XD8HVcVMIlWmGGdhIWZgwtB2CNGTbwxzcRXfWcL4kbt/qLODFnjof0sCf4i8XaS97yMuZ2v5uwyNeEeXby2AoYaZPgV0APAd0EsJ74EUIeBzYKOCDtDvsqSFzl9jsxGcQFIIbG8pmNleshKb8sAPoEfpwWKNLxDJ6JVEChS6voCoxl2kNKxcgnQY2BfgB0LH12iUcAfYahJO77DK6zqUQKFwGhyyc3U7s+pVWdrdZrMRCYgXmHfyISFZC25mNu9hOL7dCctcSqjpn3H/xNtNDbAj76ZPVikKnvYd1VS3GDDXCw6pqaCuG/HoZdrUyw4bZYXyGPlXtsyrL7tBvzYw8wF7EAn2s2vMGuLouXMXDrrazRq9QpLU71uTNa/cEstXbfmgBhk/AMfCfkw7nFoHF4FVVnCukPL1M4CRETpMYlcX3npT+XEr40NNOnd/JOg0nx9y2mO/wZ5by97zgtWt5a1RSlo+mqLJv8PDgwaY2rucz/7LvI+OYsyE8O2buiEdjf2yMDtFM73forNNx4JUbbyw+cTXfHSBOH/wJD69sSw==

RNG Seed: 1509260249

runtime error: index out of range [0] with length 0
Stack Trace:
goroutine 46 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work...

**Comment by kayla-glick** [comment]
This was caused by using the Warlock DPS T2.5 2p set bonus without ISB talented. I talked to Niche and he said that the bonus does not work without ISB, so I added a guard to prevent the error
