### ISSUE TITLE
Enhancement shaman sim potential bug/visual bug

### ISSUE THREAD

**Issue by omakaroni** [wowsims/sod#137]
![image](https://github.com/wowsims/sod/assets/28985846/0194879c-8801-4eaa-9c55-e524fdb25589)
a guy posted this picture of his sim on WoWSims discord "shaman enhancement" channel with the following text: "i think we have a bug with searing totem, did dmg but 100% miss chance"

My response and what I think might be the issue: "It might be that Misses% is calculated in sim with Misses/casts. And Casts is just 2 times, meaning you placed totem 2 times over the 60 second period, you only had 2 Misses from your ticks maybe, and then it calculates 2/2 = 100 miss%.
If im correct it would'nt change dps numbers but a visual bug that can be fixed doing miss% calculation with misses/ticks casted instead of totems casted."

If this indeed is a bug, I felt I might aswell report it.

**Comment by kayla-glick** [comment]
I haven't been able to get 100% miss rate but if I run single iterations I can sometimes get it to go up to 50% miss rate. Super weird honestly. I get a feeling it's just something weird with how we have Searing Totem coded because the DPS doesn't really change per se

**Comment by vigo2** [comment]
Currently, summoning the totem counts as a "cast", and totem ticks only count "misses": if e.g. two ticks miss, the displayed miss% is 2 / 1 = 200%.
