### ISSUE TITLE
Crash Report 1487329377

### ISSUE THREAD

**Issue by Artedien** [wowsims/sod#182]
Link:
https://wowsims.github.io/sod/warlock/#eJzjkuRgEmCSYDRgtGB0YPRgTGDMYGxgOsE4gYnRSUCCUQEsfIGRcQOjWwajEIPUJFYutoCcxMrUIgFmCQ0FDq0ORi4OgeMTeDUO9EpxsQg8bOIFklvB5Jo5vFzcAhcn8UqcZ9PYfkECyOmdyShxmVXjKFAtu8BiP421QFEOgaa5jBpnmqSArMuTeDV+/JYEsi4BWXtmSHIxC+zhB5q1GGziYzC5dzYvUPeiZl6J9exA+ZYyoFjXMx4jTgGuCMYK1g5GJqu5zFwvmBhGAV2AkAGpOl4xMTjxApMdkwYw4TkwdjAyegmZmhoYGBkYGxgaGRkY6uqaGpgGsERwJzFkAVNnwQnGimmMnYwQ3ZYOsxgZFjFxCLFxMAowKrAqnWLmhMj4OQhCGCIOkrNmgsBJe0uIyAV7xTQwuGZvNIuZ41oTrxCHT2pZao6CiYGElgK71iBLLx8aHahiDtcCiswRkPpPHXcgAUMw6dDvYJmZ/6H1ZMhVe0eojEMEIwDI3F8x

RNG Seed: 3217929004

Aura Improved Shadow Bolt already registered!
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0x859c0, 0x2276650})
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*auraTracker).registerAura(0x23d2588, 0x23d2000, {{0x17cbb4, 0x14}, {0x0, 0x0}, {0x4588, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/sod/sod/sim/core/aura.go:372 +0x3a
github.com/wowsims/sod/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/sod/sod/sim/core/aura.go:403
github.com/wowsims/sod/sim/core.ImprovedShadowBoltAura(0x23d2000, 0x5)
	/home/runner/work/sod/sod/sim/core/debuffs.go:194 +0x9
github.com/wowsims/sod/sim/warlock.(*Warlock).applyImprovedShadowBolt.func1(0x23d2000, 0x28)
	/home/runner/work/sod/sod/sim/warlock/talents.go:216 +0x6
github.com/wowsims/sod...

**Comment by kakistos153** [comment]
Seeing the same

**Comment by rosenrusinov** [comment]
Happens when you have talents in Improved Shadow Bolt and you have it also selected in the External Debuffs. I will fix it to not error but untill I do that you can just disable the ISB from external debuffs (It's not properly configured right now anyway and is very inflated so better have it off until we fix it)

**Comment by kayla-glick** [comment]
The crashes should be resolved now
