### ISSUE TITLE
Hunter: Damage modifiers (e.g. Sayge's, humanoid slaying, etc.) should not apply to pets

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#263]
https://discord.com/channels/891730968493305867/1030567707948613662/1210446502464462898

**Comment by kayla-glick** [comment]
Hey @rosenrusinov does https://github.com/wowsims/sod/pull/265 cover this or is there more to do?

**Comment by rosenrusinov** [comment]
Didnt notice the issue here but yes that pr fixed it
