### ISSUE TITLE
Items with Random Enchantment not importing correctly

### ISSUE THREAD

**Issue by EvilMerc** [wowsims/sod#299]
**Describe the bug**
When using the WoW Sims Exporter addon, and importing from character, any items with random enchantment have their stats set to none, even though they can be set in the sim.
**To Reproduce**
1. Import using addon
2. Have items equipped e.g of the tiger, of agility

**Expected behavior**
Expect this to be set as per the item.

**Desktop (please complete the following information):**
Windows

**Additional context**
Not sure if a big deal but has tripped me up a few times.

**Comment by kayla-glick** [comment]
Hey @EvilMerc would you mind providing a copy of the input generated from your addon?

**Comment by FelixPflaum** [comment]
The current release does not support random suffixes. A new version will be available soon.

**Comment by EvilMerc** [comment]
@FelixPflaum Understood, I did notice in the import it specifies the item id, not name.
@kayla-glick here is the full import:

{"talents":"0000000000000000-00000000000000-3320202212313151","class":"hunter","bagItems":[],"race":"Orc","name":"Dextra","gear":{"items":[{"id":7719},{"id":19536},{"id":213302},{"id":6745},{"enchant":866,"rune":409580,"id":213314},{"id":9409},{"id":9900,"rune":425711},{"id":10329,"rune":415352},{"id":10330,"rune":415320},{"id":9398,"rune":409687},{"id":19513},{"id":19512},{"id":21567},{"id":4381},{"enchant":7210,"id":19552},{"enchant":7210,"id":10823},{"id":216516}]},"professions":[{"name":"Alchemy","level":225},{"name":"Engineering","level":149}],"level":40,"spec":"","realm":"Shadowstrike(AU)"}

**Comment by kayla-glick** [comment]
@EvilMerc would you mind testing this out with the new addon v2.8 when you get a chance?

**Comment by EvilMerc** [comment]
Apologies for the delay, can confirm this is working as well - thanks for your great work.
