### ISSUE TITLE
Enhancement - Spellcasting not interrupting swing timer or disabling other actions

### ISSUE THREAD

**Issue by Scottfj** [wowsims/sod#316]
Hi,

Please see following image:

![image](https://github.com/wowsims/sod/assets/123885339/5e5446b9-cf54-48bf-b2a1-58bf38b43aa2)

You can see a weapon swing and a Stormstrike cast during a cast of Lava Burst. Confirmed this happens with other cast time spells as well. In fact, if you have multiple hardcasting spells allowed in your priority, things get really funky, with overlapping casts and some casts showing as incredibly long:

![image](https://github.com/wowsims/sod/assets/123885339/b72c620d-2769-4fd1-8033-b2bac4656fcf)

Obviously I'm aware this kind of rotation setup is extremely suboptimal, but just shown as an example. It would be good to be able to test hardcasting in some specific scenarios.

Thanks!

**Comment by kayla-glick** [comment]
Weird 🤔 It looks like it even cast a Flame Shock mid-cast which makes no sense

**Comment by kayla-glick** [comment]
Unless maybe the spell is already cast at that point and is just in travel time? A 2 MW LB cast should be what? About 1.8s?

**Comment by kayla-glick** [comment]
Forgot to close this sooner but I've added logic to stop swings as long as the cast time is greater than 0
