### ISSUE TITLE
how the CritPerAgiAtLevel calculate?

### ISSUE THREAD

**Issue by exolution** [wowsims/sod#323]
**Describe the bug**
Why it different from the character stats panel in the game?

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kayla-glick** [comment]
We used data from in-game at levels 25 and 40 to calculate Crit per Agi/Int and store these in our code.

https://github.com/wowsims/sod/blob/fa1137841e7cef54c6b8471a7351d93078c74205/sim/core/base_stats.go#L126-L152

![Image](https://github.com/wowsims/sod/assets/12898988/8a187b3e-3966-41e0-a77c-e5eaca60653b)
