### ISSUE TITLE
[Enhancement] Stormstrike has an additional entry which erroneously procs MSW

### ISSUE THREAD

**Issue by Scottfj** [wowsims/sod#329]
Hi,

When using Stormstrike, it's represented as 3 entries while dual weilding, and 2 entries while using a 2-handed:

Stormstrike (Rank 1)
Stormstrike (Main Hand) (Rank 1)
Stormstrike (Off Hand) (Rank 1) - when DW only

All of these entries can proc MSW, which is incorrect, and can lead to the sim getting extra MSW stacks. For example, in this situation you can see the sim gains 3 MSW stacks off a single SS cast:

![image](https://github.com/wowsims/sod/assets/123885339/fb8ad5fa-f39c-4b60-9f6e-528d418b13e3)

**Comment by vigo2** [comment]
Stormstrike is still using the TBC/WotLK mechanics, which indeed had two MH proc chances.

Fixed in https://github.com/wowsims/sod/pull/328.
