### ISSUE TITLE
Crash Report 1029495755

### ISSUE THREAD

**Issue by Cobroz22** [wowsims/sod#349]
Link:
https://wowsims.github.io/sod/hunter/#eJzj4uZgEmAyYHRgmsDE6MQqwbiB0U2IQeouKxdbQE5iZWqRAKOEpAKTVicjF4vAvwm8QPLKDBB7RxMvF7vAniZeie+MXNwCh4CMR2waXWslgXJHgXLcAvOAQh3sGu//SnJxCJxt4tX4sQbEugpk3QCyuASmG0lcZNO43iDJxSzQLg4k9noBNT9pAlny8zMP0PiFzbwSqyyAjEMQBovAkdm8RgxWbSxcD5gYRgFNgdACxoF2AiHwionBiUWASYLJi9vU2MDAwMjAwNTAMIAliSGLSYKx4ATjLEaGQ4yCQvwcjBJMSgyaEF0f7JVOMXNC2H4OghCGiIPkrJkgcNLeEiJywV4xDQyu2RvNYua41sQrxOGTWpaao2BkKiGtwKH1YnAlwQ+NDlQxx2EiReYISP2njjuQgCGEqnSwzMz/0Hoy5Kq9I1TGIYIRAALnVkA=

RNG Seed: 747116438

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xc21c0, 0xe1a1b0})
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Aura).Activate(0x0, 0x28f4120)
	/home/runner/work/sod/sod/sim/core/aura.go:550 +0x2
github.com/wowsims/sod/sim/common/sod.init.2.func10.1(0x28f4120, 0x23f6a80, 0x28ca780)
	/home/runner/work/sod/sod/sim/common/sod/melee_items.go:384 +0x15
github.com/wowsims/sod/sim/core.(*Spell).applyEffects(0x28ca780, 0x28f4120, 0x23f6a80)
	/home/runner/work/sod/sod/sim/core/spell.go:563 +0x9
github.com/wowsims/sod/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFuncAutosOrProcs.func3(0x28f4120, 0x23f6a80)
	/home/runner/work/sod/sod/sim/core/cast.go:321 +0x1e
github.com/wowsims/sod/sim/core.(*Spell).Cast(...)
	/home/runner/work/sod/sod...

**Comment by kayla-glick** [comment]
Hey @Cobroz22 👋 it looks like the issue is caused by your character being level 25. I'm guessing whatever hunter APLs we had set up for phase 1 aren't handling your gear/talents well. When I clicked your link then changed the character to level 40 the sim ran. Can you let me know if you're able to get it working?
