### ISSUE TITLE
Deadly Poison Snapshotting Issues - Wild Strikes/PI/Orc Racial

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/sod#357]
**Describe the bug**
Deadly Poison is currently not snapshotting the benefits of orc racial and PI and is currently gaining a benefit from wild strikes that should not exist.  Probably same is shown for all attacks

**To Reproduce**
[Steps to reproduce the behavior:]
Run sim with blood fury/PI activated 1s before pull and observe damage after fade.
Wild strikes see the damage change during aura uptime

**Expected behavior**
AP bonuses from Blood Fury and spell damage coefficient from PI should be carried after both fade.  For Wild Strikes there should be no change when the aura is active.

**Sim Links and Screenshots**

https://wowsims.github.io/sod/rogue/#eJzj4uRgUmByYJzAxOjEL8H4gJExgjGD8QQj4wtGRiEGqa1sXGwBOYmVqUUCrBIaCmxaWVwsAtu+8ADJvicgcs4zEDkBSHII7PjCo3F3iwQXs0CTJBe7wH5LjStAHotAL1Alu8CqQI3bYO52sPbr8xmBCr+KAZk/P/NwMYDMgpgIJmc84zFi0WC1YLZqY+F6wMQwCmgKhBYwDrQTCIFXTAxODF4CBgamxgbGhgbGpqaGuroGpgEsERxJDFmNjBLMXLJcQlkCXHwcZ/wU/sMAoxI7FysXs65hMZcwF0cWGxcLx50FCEEhWylrLkMhfS4BLT4ORiHmJkYGKaAMF6Mpl7SWJFCE7xAjtxCTACsXK0e7mAYjVFIKZA4wOQtxSXGA2cCUXnCCcRYjQxMTkxCD0iFmToir/RwEIQwRB8lZM0HgpL0lROSCvWIaGFyzN5rEzLFyNa8Qh09qWWqOgomBhJYCu9YgS/YfGh2oYg7XAorMOcIj6EgVdwCBIZh06HewzMz/0Hoy5Ko9zGiHCEYAiBNonA==

**Additional context**

**Comment by vigo2** [comment]
Fixed in https://github.com/wowsims/sod/pull/378
