### ISSUE TITLE
Rogue - Rupture and Garrote damage is higher than expected

### ISSUE THREAD

**Issue by Lisonna** [wowsims/sod#359]
**Describe the bug**
Adding Rupture/Garrote into APL - damage listed in results per cast and per tick seem significantly higher than they do in game. 
![image](https://github.com/wowsims/sod/assets/70078996/94648825-f932-496d-b50a-f8b6e0b33c7c)

Looking up high parses with Garrote, for example, on WCL have garrote's ticks of ~93 on mechanical bosses
[Just an arbitrary top 50 log I grabbed to check](https://sod.warcraftlogs.com/reports/Nm1xrFtyW4LcHJvz#boss=-2&wipes=2&start=89862&end=1343740&type=damage-done&source=4&ability=8633&target=42)

**To Reproduce**
Create an APL (linked below) that uses rupture/garrote, Verify the damage numbers make sense. 

**Expected behavior**
Rupture/Garrote damage is higher than expected. 

**Sim Links and Screenshots**
[Sim link](https://wowsims.github.io/sod/rogue/#eJzj4uBgcmBMYMxgdGKRYIxgFGKQesjBxRaQk1iZWiTALKGhwKbVx8jFIrDtCw+QvDKDkYtZYL03F5vAwTSJi2xcXAI7wyUesWnc3SLBxS6wZQajxA2Q4HxviQ52jStAQS6BzgqDuywac7dKcHEIPJnDq3EbKMotsP0Lj0Q/u0bHT0mgge3iQLN3zwDZ8/MzyJ4DKxiBxq1u4pVYZcHFKfBZwmASD4jJIvC6ideIU4PVgrmCvYFR1KqNhesBE8MooCkQWsA40E4gBF4xMTixczBKMHUwMnoJGBiYGhsYGxoYm5oa6uoamAYwRrAmMWT9YZJg5hLh4sxi52Ll+M2rwaIEZHAx6xoWC4lLiXJxbWKESUiBGDudNViEqqQquByE7LgEtPg4GIWYmxgZpIBauBhNuaS1JIEifIcYuYWYBFiB6jvENJhgkrxK3FycmxjZuFg4gEncyIRLpEgIbAabEFMVgxRQnIvJwoCLE2zRAT4NYHIHaeV4mMfFAZLlAOYSoXypXK5koUSoPoTdJvjtNpDSQ7Ibi638WrwcLEJMXlDjzOEW2knZcBkK6eOwkBmHhRA/OGswC8lISYH1MiPrBZsOLAoKTjDOYmRoYmISYlC6wswJiTc/B0EIQ8RBctZMEDhpbwkRuWCvmAYG1+yNljBzrFzNKyTlnpefm1qUmp6Yp+CbmpyRmJeZnJij4JRfXCyhpcCuNciKgg+NDlQxx2E9ReYc4RF0pIo7gMAQTDr0O1hm5n9oPRly1R5mtEMEIwCZU5DM)

**Additional context**

**Comment by joexi** [comment]
seem "total damage" be used as "tick damage"

**Comment by vigo2** [comment]
Fixed in https://github.com/wowsims/sod/pull/364
