### ISSUE TITLE
Preset Encounters do not provide non-mechanical option at level 40

### ISSUE THREAD

**Issue by Lisonna** [wowsims/sod#370]
**Describe the bug**
Encounter list has a special callout for Mechanical/Gnomer bosses. Obviously this enables the bleed/nature/armor for gnomer bosses, but it also implies that the unit type is Mechanical. This is fine. 
![image](https://github.com/wowsims/sod/assets/70078996/a752a9e3-e113-4b71-9b18-0a2b6d0105ff)

However, the other level 40 option does not specify a type. Intuitively, by contrast, because the other option specifically says Mechanical, I would think that the other level 40 option would _not_ be mechanical. However, it is set to Mechanical. This means that testing with this default will continue to treat certain items and effects favorably aside from the above mentioned Gnomer specific effects (Machinist's Gloves, Dismantle, etc). 
![image](https://github.com/wowsims/sod/assets/70078996/6dec4762-2c5c-4f76-81a5-418cbbbe1857)

**To Reproduce**
Look at the Advanced page for the "SoD/Level 40" NPC option on the Settings page. 

**Expected behavior**
I would expect the unit type here to at least be None, though two valid targets in the raid are Grubbis and Viscious, which are Humanoid and Elemental respectively. You could have them as special callouts. 

Either way, at a minimum I think that the unit type of the "SoD/Level 40" NPC option should be None to act as a generic type NPC, as a default. 

Just recommending a change to the presets for usability. Obviously any user of the sim can come in here and change things, but it isn't clear that the fight is against a mechanical when you pick the option which _doesn't_ say mechanical (when there is another one which does say mechanical).

**Comment by kayla-glick** [comment]
Just pushed an update that makes all of the default encounters untyped. I also lowered the Gnomeregan encounter's armor to 3700 to more closely match the newer armor values
