### ISSUE TITLE
Usability Feedback - Class Selection menu flyout covers simulate buttons

### ISSUE THREAD

**Issue by Lisonna** [wowsims/sod#382]
**Is your feature request related to a problem? Please describe.**
This is more a problem I want to report that isn't a bug but is just a usability stumble I've run into a few times. It may just be a Me thing, and that's alright, but I wanted to voice it. 

Sometimes when I am moving my mouse to click simulate after making changes, I'm moving quickly and I'm not using my eyes to direct my mouse cursor, I'm looking elsewhere, and I overshoot. In doing so I have multiple times hit the class menu and then corrected to move to the simulate button, which is now the "Mage" or other class button. 

![firefox_2024-03-10_13-58-17](https://github.com/wowsims/sod/assets/70078996/8412e952-3444-4890-8fb5-13ee793f146d)
See attached Gif of an example. 

**Describe the solution you'd like**
I feel like the choice to swap classes is a fairly deliberate and major one. I could be wrong but I imagine most people doing sims or testing are not going to be changing class sims very frequently, but they very likely _will_ press the simulate button frequently. 

Because of this I don't think the class menu should flyout on mouseover, and should instead flyout on _click_ like a dropdown. I don't think the mouseover flyout is much of efficiency gain because of the low traffic to the interaction. 

Alternatively, you could keep the mouseover behavior but make the mouseover reaction take ~1-2 seconds before flying out rather than being immediately. 

**Additional context**
This may be a Me problem, not sure if others have run into it, I just don't know what value the mouseover flyout provides to the general public, who are likely only simming their personal class at once and don't have need of a rapid-response mouseover flyout to swap to another class. Either way, not a bug or anything, just feedback.

**Comment by kayla-glick** [comment]
Hey @Lisonna I appreciate you reporting this! I've run into this same issue enough that I think it would be worth changing
