### ISSUE TITLE
Crash Report 1814453931

### ISSUE THREAD

**Issue by TheSketchit** [wowsims/sod#398]
Link:
https://wowsims.github.io/sod/mage/#eJzj4uBgMmC0YCxgcmJRYHRgFGKQ+srGxRaQk1iZWiTALqGhwKzVwsjFInBlIS8Xs0B/HJC5eQZIYM0cXi5ugf1NvBKP2DTad0lwsQssBXI62YGMxX4aDUARDoEzC3k17h0AsS5P4tVY+FMSqOX1Ox6J/4wai6ZKAk05ADZr/2xeIPm4CUT++swDNKHhC49EtzCQu6wFJHh8Ia8RrwC3B3MEYwJjBV8HI7NVGwvXAyaGUUBTILSAcaCdQAi8YmJwYu5gZPQS0jUwNdU1MjA2NQAShgYGBqYBzBHcSQxZPYwSzFyiXBxSbFwsHMDkqMTJxc7FqmukZ1oMFwamTWRhcS4uKQ4uNo6dZxkVmJAkhBSk5LhEhYS5BLX4OViEmJIYpIBSXMyGpqpSQIpjcpyQqJQwF+ckZpChwGwBNhyYGYRYpJi8GISYpBgKTjB2QkPVxGEWI8MpRqAUB5PSIWZOiKifgyCEIeIgOWsmCJy0t4SIXLBXTAODa/ZGk5g5Vq7mFeLwSS1LzVEwMZDQUmDXGmRZ4kOjA1XM4VpAkTlHeAQdqeIOIDAEkw79DpaZ+R9aT4ZctYcZ7RDBCAA5JGtV

RNG Seed: 3019433963

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 35 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xc42a0, 0xe420f0})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*APLActionChangeTarget).IsReady(0x200a1f8, 0x20bc120)
	/home/runner/work/sod/sod/sim/core/apl_actions_misc.go:26 +0xd
github.com/wowsims/sod/sim/core.(*APLAction).IsReady(0x23f9440, 0x20bc120)
	/home/runner/work/sod/sod/sim/core/apl_action.go:22 +0xb
github.com/wowsims/sod/sim/core.(*APLRotation).getNextAction(0x2266c60, 0x20bc120)
	/home/runner/work/sod/sod/sim/core/apl.go:238 +0xc
github.com/wowsims/sod/sim/core.(*APLRotation).DoNextAction(0x2266c60, 0x20bc120)
	/home/runner/work/sod/sod/sim/core/apl.go...

**Comment by kayla-glick** [comment]
Seems to be a bug with the `Change target` action
