### ISSUE TITLE
rogue poison scaling with spell damage

### ISSUE THREAD

**Issue by joexi** [wowsims/sod#401]
seems poison damage scaling with spell damage in wowsims but not scaling in fact

**Comment by sanguinerarogue** [comment]
Can you link example sim?  Only envenom should be scaling with spell power.

**Comment by joexi** [comment]
> Can you link example sim? Only envenom should be scaling with spell power.
Maybe I made mistakes while testing.you are right, only envenom will be scaling,poison damage is correct
