### ISSUE TITLE
Degrade Uptime, over 900%!

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/sod#406]
**Describe the bug**
Right clicking the degrade buff from 10->0 and then again brings it to 1000.  Each right click then goes 990 etc.

**To Reproduce**
Go to any sim and right click the faded out degrade button

**Expected behavior**
Go to 0 and stay at 0.

**Sim Links and Screenshots**
![image](https://github.com/wowsims/sod/assets/118020821/bd7ae139-a316-4f5e-803c-4b777b72457f)

**Additional context**

Additionally, I think turning on Degrade should probably go straight to 100% uptime, I am not sure most users will notice first press is 10% uptime.  It appears this bug exists with Demonic Pact as well.

**Comment by kayla-glick** [comment]
Yeah tbh I don't think it's really worth having this an an incremental uptime buff like that in the UI. We should just make it a boolean IMO

**Comment by rosenrusinov** [comment]
@kayla-glick I had this implemented as a boolean and people complined they cant controll the uptime so i changed it to this. Im fine with changing it to just be a boolean again but be ready for someone to ask for an uptime controll 😅

**Comment by kayla-glick** [comment]
Oh 🙄 great lol. Well at the very least we should change it to cap out at 100. It would also be nice if we could "invert" the direction and make it decrement starting at 100 down to 0, that way 100 is the "default" state on the first left click

**Comment by rosenrusinov** [comment]
Hmm i dont like the inverted behaviour in terms of ux but i do agree that a single click putting it to max is probably better.

**Comment by rosenrusinov** [comment]
Also it already caps at 100. We just have a bug when decreasing it from 0 for some reason it ignores the max it has set and goes to a much higher value

**Comment by kayla-glick** [comment]
@rosenrusinov I have a PR up for this https://github.com/wowsims/sod/pull/416. We could do without the part that makes it decrement from 100 instead of incrementing to 100 by 'reversing" the order. I don't feel strongly one way or the other but it would act differently than Demonic Pact in that way.

**Comment by rosenrusinov** [comment]
Demonic pact should definitely start from 0 and go up with every click thats the only strong feeling i have. Degrade can work in reverse if you think its better i still think its a bit confusing in terms of ux but it beats having to click 10 times to get it to 100 for sure

**Comment by kayla-glick** [comment]
> Degrade can work in reverse if you think its better i still think its a bit confusing in terms of ux but it beats having to click 10 times to get it to 100 for sure

Users _can_ technically right click once but I'm not sure many know about that 😅 I definitely wouldn't change Demonic Pact. The only change in my PR is that the "max" value is lowered to 200 down from 2k when right clicking
