### ISSUE TITLE
Battle Chicken Squawk Buff Request

### ISSUE THREAD

**Issue by shnaza** [wowsims/sod#434]
**Feature request**
Can we add the Squawk (Spell ID = 23060) buff from the Gnomer trinket Domesticated Attack Chicken item=(215461)

**Describe the solution you'd like**
An option in the settings tab in the Raid buff section, the buff Squawk provides the party with 5% melee haste. as well as the possibility of having it stack up to five times.

Once the buff is selected, the melee haste option under stats will change to whatever the haste equivalent is. e.g. 25% for five squawks

**Describe alternatives you've considered**
A feature in the rotation settings to have it selected under the "prepull actions"

**Additional context**

**Comment by kayla-glick** [comment]
We've debated how to handle this trinket but I think this is a fair compromise. Do Squawks stack? I don't play melee so I have no idea 😂

**Comment by shnaza** [comment]
Thank you for the reply, Yes they stack up to a maximum of five Squawks.

**Comment by sanguinerarogue** [comment]
implemented in #470
