### ISSUE TITLE
Crash Report 764838600

### ISSUE THREAD

**Issue by Uzuga228** [wowsims/sod#443]
Link:
https://wowsims.github.io/sod/rogue/#eJzjYudgcmCcwMToxCPB+ICRMYIxg/EEI6MQg9R9Vi62gJzEytQiAUYJDQU2rR5GLhaBfxN4geSDJl4uZoH13lxsAp2aEhfZuLgFDjbxSjxi07i7RYKLXaBtJqPEDZDocaBoB7vGFaAoh8DpCbwac7eCWFeaeDVuA8W4Be4CFXxn1Oj4KQk0dscMkBVLmkBW/PzMAySfANnsAquBilZZAC37IgCiWQReN/EacWqwWjBXsDcwilq1sXA9YGIYBTQFQgsYB9oJhMArJgYnJglGLwEDA1NjA2NDA2NTU0NdXQPTAJYIjiSGLKBcwQnGWYwMTUxMQgxK+5k5Ifr8HAQhDBEHyVkzQeCkvSVE5IK9YhoYXLM36mfmOGgpxOGTWpaao2BiIKGlNchS3YdGB6qYw7WAInOO8Ag6UsUdQGAIJh36HSwz8z+0ngy5ag8z2iGCEQBCflja

RNG Seed: 2360944238

using CritMultiplier() for spellID 18107 which has no DefenseType
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0x96560, 0x2387510})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Spell).CritMultiplier(0x23fb180, 0x28008c0)
	/home/runner/work/sod/sod/sim/core/spell_outcome.go:626 +0xf
github.com/wowsims/sod/sim/core.(*SpellResult).applyAttackTableCritSeparateRoll(0x23fb358, 0x23edd40, 0x23fb180, 0x28008c0)
	/home/runner/work/sod/sod/sim/core/spell_outcome.go:472 +0xb
github.com/wowsims/sod/sim/core.(*Spell).OutcomeMeleeSpecialHitAndCrit(0x23fb180, 0x23edd40, 0x23fb358, 0x28008c0)
	/home/runner/work/sod/sod/sim/core/spell_outcome.go:207 +0xb0
github.com/wowsims/sod/sim/core.(*Spell).calcDamageInternal(0x23fb180, 0x23edd40, 0x2824000, 0x4058eba4805ef5f6, 0x3ff0000000000000, 0x0, 0x28ff9d8)
	/home/runner/work...

**Comment by kayla-glick** [comment]
Verified this is fixed by https://github.com/wowsims/sod/pull/444 on the live site
