### ISSUE TITLE
Phase 3: Gear Effects

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#471]
New datamined raid gear
https://www.wowhead.com/classic/news/sunken-temple-raid-loot-in-datamining-phase-3-season-of-discovery-338288

New datamined Blood Moon gear
https://www.wowhead.com/classic/news/blood-moon-pvp-rewards-phase-3-datamining-season-of-discovery-338290

### Weapons
- [x] [Shadowblade](https://www.wowhead.com/classic/item=2163/shadowblade)
- [x] [Hookfang Shanker](https://www.wowhead.com/classic/item=11635/hookfang-shanker)
- [x] [Flurry Axe](https://www.wowhead.com/classic/item=871/flurry-axe)
- [x] [Hammer of the Northern Wind](https://www.wowhead.com/classic/item=810/hammer-of-the-northern-wind)
- [x] [Hanzo Sword](https://www.wowhead.com/classic/item=8190/hanzo-sword)
- [x] [Bloodrazor](https://www.wowhead.com/classic/item=809/bloodrazor)
- [x] [Firebreather](https://www.wowhead.com/classic/item=10797/firebreather)
- [x] [Vilerend Slicer](https://www.wowhead.com/classic/item=11603/vilerend-slicer)
- [x] [Thrash Blade](https://www.wowhead.com/classic/item=17705/thrash-blade)
- [x] [Joonho's Mercy](https://www.wowhead.com/classic/item=17054/joonhos-mercy)
- [x] [Blade of Eternal Darkness](https://www.wowhead.com/classic/item=17780/blade-of-eternal-darkness)
- [x] [Satyr's Lash](https://www.wowhead.com/classic/item=17752/satyrs-lash)
- [x] [Fist of Stone](https://www.wowhead.com/classic/item=17943/fist-of-stone)
- [x] [Serpent Slicer](https://www.wowhead.com/classic/item=13035/serpent-slicer)
- [x] [Searing Needle](https://www.wowhead.com/classic/item=12531/searing-needle)
- [x] [The Hand of Antu'sul](https://www.wowhead.com/classic/item=9639/the-hand-of-antusul)
- [x] [Shortsword of Vengeance](https://www.wowhead.com/classic/item=754/shortsword-of-vengeance)
- [x] [Gryphon Rider's Stormhammer](https://www.wowhead.com/classic/item=9651/gryphon-riders-stormhammer)
- [x] [Gutwrencher](https://www.wowhead.com/classic/item=5616/gutwrencher)
- [x] [Bloodletter Scalpel](https://www.wowhead.com/classic/item=9511/bloodletter-scalpel)
- [x] [Linken's Sword of Mastery](https://www.wowhead.com/classic/item=11902/linkens-sword-of-mastery)
- [x] [Cobra Fang Claw](https://www.wowhead.com/classic/item=220588/cobra-fang-claw)
- [x] [Serpent's Striker](https://www.wowhead.com/classic/item=220589/serpents-striker)
  - Added in https://github.com/wowsims/sod/pull/533 with a 5% proc chance (same as Mekkatorque's). Need to verify chance
- [x] [Ritualist's Hammer](https://www.wowhead.com/classic/item=221446/ritualists-hammer) (Druid Only)
  - Just a stronger Bloodbark Crusher
- [x] [Gurubashi Pit Fighter's Bow](https://www.wowhead.com/classic/item=221450/gurubashi-pit-fighters-bow) (Hunter Only)
  - Just a stronger Bloodlash Bow
- [x] [Bloodthirst Crossbow](https://www.wowhead.com/classic/item=221451/bloodthirst-crossbow) (Hunter Only)
- [x] [Dragon's Cry](https://www.wowhead.com/classic/item=220582/dragons-cry)

### Trinkets
**Raid Trinkets**
- [ ] [Chain Essence of Eranikus](https://www.wowhead.com/classic/item=221474/chained-essence-of-eranikus)
- [x] [Zila Gular](https://www.wowhead.com/classic/item=223214/zila-gular) (Warlock Only)
- [ ] [Atal'ai Blood Ceremony](https://www.wowhead.com/classic/item=220619/atalai-blood-ceremony)
  - No clue what this does. It's a 1-minute channel and summons an object
- [x] [Atal'ai Blood Ritual Badge](https://www.wowhead.com/classic/item=220633/atalai-blood-ritual-badge)
- [x] [Atal'ai Blood Ritual Charm](https://www.wowhead.com/classic/item=220634/atalai-blood-ritual-charm)
- [x] [Atal'ai Blood Ritual Medallion](https://www.wowhead.com/classic/item=220632/atalai-blood-ritual-medallion)
- [ ] [Nightmare Resonance Crystal](https://www.wowhead.com/classic/item=220621/nightmare-resonance-crystal)
  - [Spell](https://www.wowhead.com/classic/spell=446097/nightmare-resonance-crystal) hard to tell what exactly this does. Includes a server-side script

**Darkmoon Cards**
https://www.wowhead.com/classic/news/phase-3-datamined-darkmoon-faire-trinkets-season-of-discovery-338285
- [ ] [Darkmoon Card: Overgrowth](https://www.wowhead.com/classic/item=221308/darkmoon-card-overgrowth)
  - Basically [Revitalize](https://www.wowhead.com/wotlk/spell=48545/revitalize) but with a 5% proc chance [Overgrowth](https://www.wowhead.com/classic/spell=446395/overgrowth)
- [x] [Darkmoon Card: Decay](https://www.wowhead.com/classic/item=221307/darkmoon-card-decay)
  - Wowhead lists a 100% proc chance at the moment but this is most likely wrong based on the tooltip
  - Updated with a 35% proc chance and 200ms ICD (maybe just on spell cast and not ticks but unsure)
- [x] [Darkmoon Card: Sandstorm](https://www.wowhead.com/classic/item=221309/darkmoon-card-sandstorm)
  - Wowhead lists a 100% proc chance at the moment but this is most likely wrong based on the tooltip
- [x] [Darkmoon Card: Torment](https://www.wowhead.com/classic/item=221310/darkmoon-card-torment)
  - No combat effect so nothing to do for this one

**Not to do**
- [x] [Atal'alarion's Enchanted Boulder](https://www.wowhead.com/classic/item=220635/atalalarions-enchanted-boulder)
  - Seems to turn the user into a large troll [Spell](https://www.wowhead.com/classic/spell=446104/atalalarions-enchanted-boulder) with no discernible combat effect
- [x] [Lledra's Inanimator](https://www.wowhead.com/classic/item=220639/lledras-inanimator)
  - Seems to cause the player to hide in a barrel with no discernible combat effect
- [x] [Unorthodox Hex Stick](https://www.wowhead.com/classic/item=220638/unorthodox-hex-stick)
  - Seems to turn the character into a worm with no discernible combat effect
- [x] [Witch Doctor's Hex Stick](https://www.wowhead.com/classic/item=221484/witch-doctors-hex-stick)
  - Seems to make the character stealthier while in ST but with no discernible combat effect

### Armor
- [x] Phase 3 Tier Bonuses
  - https://github.com/wowsims/sod/issues/515
- [x] Phase 3 Crafted Armor
  - Shoulders added in https://github.com/wowsims/sod/pull/519

### Other
- [x] [Libram of Draconic Destruction](https://www.wowhead.com/classic/item=221457/libram-of-draconic-destruction) (Paladin)
- [x] [Totem of Fiery Precision](https://www.wowhead.com/classic/item=221464/totem-of-fiery-precision) (Shaman)
- [x] [Serpent's Ascension](https://www.wowhead.com/classic/item-set=1651/serpents-ascension) set bonus
  - Combination of [Serpent's Striker](https://www.wowhead.com/classic/item=220589/serpents-striker) and https://www.wowhead.com/classic/item=220588/cobra-fang-claw

### ~~[Incomplete Phase 2 Gear](https://github.com/wowsims/sod/issues/201)~~
- [x] [Gyromatic Experiment 420b](https://www.wowhead.com/classic/item=213348/gyromatic-experiment-420b)
  - [Battle Squawk](https://www.wowhead.com/classic/spell=23060/battle-squawk) buff added in https://github.com/wowsims/sod/pull/470. Maybe we could just implement the trinket to trigger the aura?
- [x] [Domesticated Attack Chicken](https://www.wowhead.com/classic/item=215461/domesticated-attack-chicken)

**Comment by Lisonna** [comment]
Two items I noticed the on-hit effect doesn't show up in the damage breakdown:
[Shadowblade](https://www.wowhead.com/classic/item=2163/shadowblade)
[Hookfang Shanker](https://www.wowhead.com/classic/item=11635/hookfang-shanker)

**Comment by rosenrusinov** [comment]
Added Flurry Axe to the list

**Comment by Lisonna** [comment]
Some more - All of these have some damage effect component or resource / debuff they apply, and the sim does not have those damage sources in the results. This is pretty much "any weapon with a proc in p3" I could find. 

[Hammer of the Northern Wind](https://www.wowhead.com/classic/item=810/hammer-of-the-northern-wind)
[Hanzo Sword](https://www.wowhead.com/classic/item=8190/hanzo-sword)
[Bloodrazor](https://www.wowhead.com/classic/item=809/bloodrazor)
[Firebreather](https://www.wowhead.com/classic/item=10797/firebreather)
[Vilerend Slicer](https://www.wowhead.com/classic/item=11603/vilerend-slicer)
[Thrash Blade](https://www.wowhead.com/classic/item=17705/thrash-blade) -> Unsure on this one, could not see any Extra Attack events in the Log tab of results
[Joonho's Mercy](https://www.wowhead.com/classic/item=17054/joonhos-mercy)
[Blade of Eternal Darkness](https://www.wowhead.com/classic/item=17780/blade-of-eternal-darkness)
[Satyr's Lash](https://www.wowhead.com/classic/item=17752/satyrs-lash)
[Fist of Stone](https://www.wowhead.com/classic/item=17943/fist-of-stone) -> Resource tab shows no mana gained, but I was testing on rogue so it may just not do that 
[Serpent Slicer](https://www.wowhead.com/classic/item=13035/serpent-slicer)
[Searing Needle](https://www.wowhead.com/classic/item=12531/searing-needle)
[The Hand of Antu'sul](https://www.wowhead.com/classic/item=9639/the-hand-of-antusul)
[Shortsword of Vengeance](https://www.wowhead.com/classic/item=754/shortsword-of-vengeance)
[Gryphon Rider's Stormhammer](https://www.wowhead.com/classic/item=9651/gryphon-riders-stormhammer)
[Gutwrencher](https://www.wowhead.com/classic/item=5616/gutwrencher)
[Bloodletter Scalpel](https://www.wowhead.com/classic/item=9511/bloodletter-scalpel)
[Linken's Sword of Mastery](https://www.wowhead.com/classic/item=11902/linkens-sword-of-mastery)

**Comment by kayla-glick** [comment]
Thanks @Lisonna ! Added all of those. I verified the two you weren't sure about were in fact not implemented

**Comment by Lisonna** [comment]
Forgot to mention the raid fist weapons
[Cobra Fang Claw](https://www.wowhead.com/classic/item=220588/cobra-fang-claw)
[Serpent's Striker](https://www.wowhead.com/classic/item=220589/serpents-striker)

**Comment by TheGroxEmpire** [comment]
[Cobra Fang Claw](https://www.wowhead.com/classic/item=220588/cobra-fang-claw) is added in #529.

**Comment by Foknetics** [comment]
[Serpent's Striker](https://www.wowhead.com/classic/item=220589/serpents-striker) is added in #533.

**Comment by kayla-glick** [comment]
[Serpent's Ascension](https://www.wowhead.com/classic/item-set=1651/serpents-ascension) set bonus
[Ritualist's Hammer](https://www.wowhead.com/classic/item=221446/ritualists-hammer) (Druid Only)
[Gurubashi Pit Fighter's Bow](https://www.wowhead.com/classic/item=221450/gurubashi-pit-fighters-bow) (Hunter Only)

all added in https://github.com/wowsims/sod/pull/534

**Comment by Lisonna** [comment]
[Dragon's Cry](https://www.wowhead.com/classic/item=220582/dragons-cry)

**Comment by Foknetics** [comment]
[Roar of the Guardian](https://www.wowhead.com/classic/item=221442/roar-of-the-guardian) is added in #545

**Comment by vigo2** [comment]
Added the first 10 non-implemented ones in https://github.com/wowsims/sod/pull/591 (Shadowblade up to Satyr's Lash)

**Comment by vigo2** [comment]
And the remaining ones, but for Dragon's Cry in https://github.com/wowsims/sod/pull/596

**Comment by kayla-glick** [comment]
Adding the following in https://github.com/wowsims/sod/pull/651
- [Dragon's Cry](https://www.wowhead.com/classic/item=220582/dragons-cry)
- [Atal'ai Blood Ritual Badge](https://www.wowhead.com/classic/item=220633/atalai-blood-ritual-badge)
- [Atal'ai Blood Ritual Medallion](https://www.wowhead.com/classic/item=220632/atalai-blood-ritual-medallion)
- [Libram of Draconic Destruction](https://www.wowhead.com/classic/item=221457/libram-of-draconic-destruction)
