### ISSUE TITLE
Phase 3: Figure out why Enhancement lvl 50 test average consistently off by < .01 dps in CI

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#473]
[Original PR](https://github.com/wowsims/sod/pull/452)
[Example build failure](https://github.com/wowsims/sod/actions/runs/8462159413/job/23183075619)

**Comment by rosenrusinov** [comment]
This usually happens when a non seeded random gets added somewhere (we should always use sim.Random to guarantee same results)

**Comment by kayla-glick** [comment]
I just don't recall using a non-sim.Random 🤔

**Comment by kayla-glick** [comment]
Also wouldn't you expect at least one test to fail besides the average?

**Comment by rosenrusinov** [comment]
> Also wouldn't you expect at least one test to fail besides the average?

That is indeed weird
