### ISSUE TITLE
Phase 3: Consumables

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#478]
This issue is to track the state of consumables for phase 3 - e.g. what's available, what's not, and what are we missing and need to implement.

Still need new phase 3 consumables

### Flasks
Vanilla flasks can only be crafted in Scholomance and as such I suspect will be completely unavailable in phase 3, We should consider disabling them in the UI for now.
- [x] [Flask of Restless Dreams](https://www.wowhead.com/classic/item=222952/flask-of-restless-dreams)
  - New SoD alchemy-only flask
- [x] [Flask of Everlasting Nightmares](https://www.wowhead.com/classic/item=221024/flask-of-everlasting-nightmares)
  - New SoD alchemy-only flask

### Elixirs
- [x] [Elixir of the Mongoose](https://www.wowhead.com/classic/item=13452/elixir-of-the-mongoose)
  - Obtainable from a drop that should be reasonable
- [ ] [Mageblood Potion](https://www.wowhead.com/classic/item=20007/mageblood-potion)
  - Locked behind ZG rep so I think we can count this out?
- [x] [Elixir of Giants](https://www.wowhead.com/classic/item=9206/elixir-of-giants)
  - Obtainable from a drop that should be reasonable
- [ ] [Elixir of Superior Defense](https://www.wowhead.com/classic/item=13445/elixir-of-superior-defense)
  - Purchasable recipe from a major city
- [ ] [Strong Troll's Blood Potion](https://www.wowhead.com/classic/item=3388/strong-trolls-blood-potion)
  - Trainable
- [ ] [Elixir of Fortitude](https://www.wowhead.com/classic/item=3825/elixir-of-fortitude)
  - Trainable
- [x] [Greater Arcane Elixir](https://www.wowhead.com/classic/item=13454/greater-arcane-elixir)
  - Only realistic drop is from mobs in BRD at an incredibly low drop rate. Probably not obtainable to 99% of players if at all
- [x] [Elixir of Shadow Power](https://www.wowhead.com/classic/spell=11474/shadow-power)
  - Purchasable recipe from a major city
- [x] [Elixir of Greater Firepower](https://www.wowhead.com/classic/item=21546/elixir-of-greater-firepower)
  - Obtainable from mobs in Searing Gorge

### Weapon Imbues
- [x] [Brilliant Wizard Oil](https://www.wowhead.com/classic/item=20749/brilliant-wizard-oil)
  - Locked behind ZG rep so I think we can count this out?
- [ ] [Blessed Wizard Oil](https://www.wowhead.com/classic/item=23123/blessed-wizard-oil) requires quests in the plaguelands but with a minimum level of 50. These might be useful if there's any undead bosses in the Sunken Temple
  - Unsure if these are realistically available for phase 3
- [x] [Wizard Oill](https://www.wowhead.com/classic/item=20750/wizard-oil)
  - Available in Silithus at Neutral reputation so I think this is ok
- [x] [Brilliant Mana Oil](https://www.wowhead.com/classic/item=20748/brilliant-mana-oil)
  - Locked behind ZG rep so I think we can count this out?
- [x] [Lesser Mana Oil](https://www.wowhead.com/classic/item=20754/formula-lesser-mana-oil)
  - Available in Silithus at Neutral reputation so I think this is ok
- [x] [Elemental Sharpening Stone](https://www.wowhead.com/classic/item=18262/elemental-sharpening-stone)
  - Pattern drops from Molten Core so this is definitively not available yet until phase 4
- [ ] [Consecrated Sharpening Stone](https://www.wowhead.com/classic/item=23122/consecrated-sharpening-stone)
  - Same situation as Blessed Wizard Oil
- [x] [Dense Sharpening Stone](https://www.wowhead.com/classic/item=12404/dense-sharpening-stone)
  - Trainable at 250
- [x] [Dense Weightstone](https://www.wowhead.com/classic/spell=16640/dense-weightstone)
  - Trainable at 250

### Food
- [x] [Blessed Sunfruit](https://www.wowhead.com/classic/item=13810/blessed-sunfruit)
  - Requires Argent Dawn revered so unsure if this is realistically available
- [x] [Runn Tum Tuber Surprise](https://www.wowhead.com/classic/item=18254/runn-tum-tuber-surprise)
  - Recipe drops from Dire Maul so likely not available
- [ ] [Poached Sunscale Salmon](https://www.wowhead.com/classic/item=13932/poached-sunscale-salmon)
  - Recipe obtainable in Tanaris
- [x] [Nightfin Soup](https://www.wowhead.com/classic/item=13931/nightfin-soup)
  - Recipe obtainable in Tanaris

### Misc
Consider doing https://github.com/wowsims/sod/issues/417 as a place to keep these
- [x] [Ground Scorpok Assay](https://www.wowhead.com/classic/item=8412/ground-scorpok-assay#reward-from-q)
  - Rewards from Blasted Lands quest +25 Agility
- [x] [Gizzard Gum](https://www.wowhead.com/classic/item=8424/gizzard-gum)
  - Rewards from Blasted Lands quest +25 Spirit
- [x] [Cerebral Cortex Compound](https://www.wowhead.com/classic/item=8423/cerebral-cortex-compound)
  - Rewards from Blasted Lands quest +25 Intellect
- [x] [Lung Juice Cocktail](https://www.wowhead.com/classic/item=8411/lung-juice-cocktail)
  - Rewards from Blasted Lands quest +25 Stamina
- [ ] [Crystal Ward](https://www.wowhead.com/classic/item=11564/crystal-ward)
  - Req lvl 47 quest in Un'goro
- [x] [Winterfall Firewater](https://www.wowhead.com/classic/item=12820/winterfall-firewater#dropped-by)
  - Drops from mid-high 50s mobs so will be hard to obtain but not impossible
- [x] [Gift of Arthas](https://www.wowhead.com/classic/item=9088/gift-of-arthas)
  - Recipe drops from mobs in WPL

**Comment by rosenrusinov** [comment]
Blessed Wizard Oil and Consecrated Sharpening stones are from the Naxx Invasion Event so they are 100% not available. 

We already have all Flasks implemented and we would only need to update their min level.

I marked a lot of stuff in that list that I know we have and we would only need to maybe change their MinLevel if they are not available this phase (we still have them implemented tho)

**Comment by kayla-glick** [comment]
@rosenrusinov Do you think we should enable items like [Blessed Sunfruit](https://www.wowhead.com/classic/item=13810/blessed-sunfruit)? I'm sure there is some absurd grinding someone could probably realistically do to obtain it in phase 3 unless it's completely removed from vendors

**Comment by kayla-glick** [comment]
Working on https://github.com/wowsims/sod/issues/417 and adding consumes like winterspring firewater, moving catnip to the misc picker, and adding restrictions on Atal'ai mojo, badlands buff consumes, and zanza potions
