### ISSUE TITLE
Crash Report -854845545

### ISSUE THREAD

**Issue by Greg-Pina** [wowsims/sod#479]
Link:
https://wowsims.github.io/sod/warrior/#eJzjEuVgUmDUYHRg8mBMYNzByHSAkWkCE6MTjwRjBOMGRrcMxhOMjEIMUq1sXGwBOYmVqUUCrBJGCpxacxm5OARWLmDUeNIuxcUm8DPW4DYjF4vA0gWMQN6rKInvjFy8AgtCDJbwSDxi09h7WoKLW+DPDEaJG2waOzukgHIrvA22MoG4d+ZKAo0628Sr8QqoikPgCpB16rckF5dAd5LERTaNrvMSQIM3doEMXh1isJkJyPv5mQdk2WReLk6B94kGBxglPoKkvyeCaGaB96lG/AJMGqwWzBmMBcwV7AcYGa3aWLgeMDGMApoCoQWMA+0EQuAVE4MTmwCjA2MAo5e4sYGRgamugSkQGhiYmgApQyBtGMAUwZLEkMUkwVhwgnEWI8MqJjYpFgFGCUalA8ycEGP8HAQhDBEHyVkzQeCkvSVE5IK9YhoYXLM3msDMcb2JV4jDJ7UsNUfB1EDCRGuQpcIPjQ5UMYdrAUXmCEj9p447gMAQTDrMd7DMzP/QejLkqr0jVMYhghEASBRnlg==

RNG Seed: 198748087

Aura Enrage already registered!
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:49 +0x10
panic({0x96940, 0x2384c60})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*auraTracker).registerAura(0x22d85c8, 0x22d8000, {{0x19f5fa, 0x6}, {0x0, 0x0}, {0x6843a, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/sod/sod/sim/core/aura.go:372 +0x3a
github.com/wowsims/sod/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/sod/sod/sim/core/aura.go:403
github.com/wowsims/sod/sim/warrior.(*Warrior).applyWreckingCrew(0x22d8000)
	/home/runner/work/sod/sod/sim/warrior/runes.go:245 +0x15
github.com/wowsims/sod/sim/warrior.(*Warrior).ApplyRunes(0x22d8000)
	/home/runner/work/sod/sod/sim/warrior/runes.go:35 +0x89
github.com/wowsims/sod/sim/core.(*Character).applyAllEffects(0x22d8000, ...

**Comment by TheGroxEmpire** [comment]
This has been fixed in #501.
