### ISSUE TITLE
Crash Report 519337530

### ISSUE THREAD

**Issue by Rissone** [wowsims/sod#499]
Link:
https://wowsims.github.io/sod/warrior/#eJzj4uJgcmDawch0gJHJiUeCMYJxA6NbBuMJRkYhBqk3rFxsATmJlalFAowSRgqcWhMYuTgE/k3g1XjSLsXFIvCgiRdI7gCS7AK7m3glvjNycQscBDIesWnsPS0B5PydwShxg01jD1A5t8BxoAyQM+mcBNCU8028Gq9Og1hXgKxTvyW5uASWektcZNN4OE0SZOoMRiC5BGzDz888QPIJkM0mcDxEYpUFF7PAbn4gccnTiMGqjYXrARPDKKApEFrAONBOIAReMTE4cXAwApMqkwOjl4SugSkQGhobGxgBKQMDU0NdUwMjA+MA5giOJIYsJgnGghOMsxgZVjGxSbEANTEqHWDmhJjk5yAIYYg4SM6aCQIn7S0hIhfsFdPA4Jq90QRmjutNvEIcPqllqTkKpgYSJlqDLCF+aHSgijlcCygyR0DqP3XcAQSGYNJhvoNlZv6H1pMhV+0doTIOEYwAOPdeog==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:49 +0x10
panic({0xc7340, 0xea0890})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/warrior.(*Warrior).registerGladiatorStance(0x23a2000)
	/home/runner/work/sod/sod/sim/warrior/stances.go:124 +0x17
github.com/wowsims/sod/sim/warrior.(*Warrior).registerStances(0x23a2000)
	/home/runner/work/sod/sod/sim/warrior/stances.go:154 +0x14
github.com/wowsims/sod/sim/warrior.(*Warrior).Initialize(0x23a2000)
	/home/runner/work/sod/sod/sim/warrior/warrior.go:121 +0x21
github.com/wowsims/sod/sim/warrior/dps.(*DpsWarrior).Initialize(0x21e7ce0)
	/home/runner/work/sod/sod/sim/warrior/dps/dps_warrior.go:73 +0x4
github.com/wowsims/sod/sim/core.(*Environment).initialize(0x2822e00, 0x238ef80, 0x206e690)
	/home/runner/work/sod/sod/sim/core...

**Comment by TheGroxEmpire** [comment]
Fixed with #502.
