### ISSUE TITLE
importer

### ISSUE THREAD

**Issue by metalzero4** [wowsims/sod#50]
im able to generate data on the /wse addon in game, i then copy paste into the balance druid import from addon on the website and when i click the import button nothing happens. im a user of this addon on dk wotlk and it works fine for me right now.

**Comment by kayla-glick** [comment]
Hi @metalzero4, we're still working out some issues with the SoD exporter as we only started working on it today. Hopefully we can have everything ready and in working order very soon 😄

**Comment by metalzero4** [comment]
no problem i appreciate you all for what you do just figured id let you know about this

**Comment by kayla-glick** [comment]
Hey @metalzero4 the WowSimsExporter addon was just updated today! Would you mind downloading the newest version and trying again?

**Comment by metalzero4** [comment]
> Hey @metalzero4 the WowSimsExporter addon was just updated today! Would you mind downloading the newest version and trying again?

its works now i appreciate your help
