### ISSUE TITLE
Crash Report 664691437

### ISSUE THREAD

**Issue by Rissone** [wowsims/sod#500]
Link:
https://wowsims.github.io/sod/warrior/#eJzj4uJgcmDawch0gJHJiUeCMYJxA6NbBuMJRkYhBqk3rFxsATmJlalFAowSRgqcWhMYuTgE/k3g1XjSLsXFIvCgiRdI7gCS7AK7m3glvjNycQscBDIesWnsPS0B5PydwShxg01jD1A5t8BxoAyQM+mcBNCU8028Gq9Og1hXgKxTvyW5uASWektcZNN4OE0SZOoMRiC5BGzDz888QPIJkM0mcDxEYpUFF7PAbn4gccnTiMGqjYXrARPDKKApEFrAONBOIAReMTE4cXAwApMqkwOjl4SugSkQGhobGxgBKQMDU0NdUwMjA+MA5giOJIYsJgnGghOMsxgZVjGxSbEANTEqHWDmhJjk5yAIYYg4SM6aCQIn7S0hIhfsFdPA4Jq90QRmjutNvEIcPqllqTkKpgYSJlqDLCF+aHSgijlcCygyR0DqP3XcAQSGYNJhvoNlZv6H1pMhV+0doTIOEYwAOPdeog==

RNG Seed: 3599829801

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xc7340, 0xea0890})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/warrior.(*Warrior).registerGladiatorStance(0x23cc000)
	/home/runner/work/sod/sod/sim/warrior/stances.go:124 +0x17
github.com/wowsims/sod/sim/warrior.(*Warrior).registerStances(0x23cc000)
	/home/runner/work/sod/sod/sim/warrior/stances.go:154 +0x14
github.com/wowsims/sod/sim/warrior.(*Warrior).Initialize(0x23cc000)
	/home/runner/work/sod/sod/sim/warrior/warrior.go:121 +0x21
github.com/wowsims/sod/sim/warrior/dps.(*DpsWarrior).Initialize(0x2396740)
	/home/runner/work/sod/sod/sim/warrior/dps/dps_warrior.go:73 +0x4
github.com/wowsims/sod/sim/core.(*Environment).initialize(0x2823400, 0x238f980, 0x206e9a0)
	/home/runner...

**Comment by TheGroxEmpire** [comment]
Fixed with #502.
