### ISSUE TITLE
Rogue/Druid ST Tier set bonuses do not update sidebar stats

### ISSUE THREAD

**Issue by Lisonna** [wowsims/sod#511]
**Describe the bug**
When equipping ST Tier set 
![image](https://github.com/wowsims/sod/assets/70078996/e87a5558-1fc7-4f5e-87de-43a278dfb59e)

The Hit Rating and Crit Rating bonuses on the sidebar do not reflect the set bonuses. 

![image](https://github.com/wowsims/sod/assets/70078996/75a9c4ba-e8a9-4ac3-b438-790152c9a53f)

**Expected behavior**
Sidebar updates should include updates to stats. When testing the P2 Tier set, the tier set bonus _does_ apply to the sidebar stats. **This leads me to believe that the bonuses themselves are not applying, but I do not know how to confirm if it is merely a visual bug or an actual stats bug.**

**Comment by kayla-glick** [comment]
I've opened https://github.com/wowsims/sod/issues/515 to capture this. None of the tier set bonuses are implemented at the moment

**Comment by kayla-glick** [comment]
Closing this after shipping a PR for all tier bonuses. I verified that bonuses are working correctly now 🥳
