### ISSUE TITLE
Crash Report 1429521940

### ISSUE THREAD

**Issue by synyker** [wowsims/sod#601]
Link:
https://wowsims.github.io/sod/feral_druid/#eJztVV1IFFEUnjMzu3s9Nuvs1XK8mmxLP9OGMju6uWuEm4SI9SDRQ/RLoqIhJAVRPpVWhE8SWNZL1kNRTyVCoBG9aQ9RQVYgUfT3UFGCRPVkZ2ZHjc3wIaMeOjD35zvnfOe7d8/OYC6Tw7IpW5CAFNRCO/TIUB0w4Do0tgCXxFcN/fVte480HdD9hh2G6FnAbH18TDMeVZjfhgpQ0S82Y0CfJKQ/SYuRYc146KeY97cICZhXJw3avLytGc+C5tSVAtqMXAbjedAcJk9Av7zD/DzkoO8o/nW2OejGf6DNFzDPkEfVb/YBjTe6nfF6rzOO39codZBKdeWhRMDtYc1erIMJCbkF2n2HA6fA1wPqKEDlSRVfyNJ/+6PG++FvS5jP3slSdSAF9dADUFcYt8jiZVasJG7R2rbK7LKYRVsrXq9uYw3Svk8BQ4kgZyhThzlPLrJ9flQZdWgkgD5UShIHeb5YjIsiiGwACGFH/SI98TYGogV3853IozpTudwhCYaUHysvrcBQNIf5ubxdEi4TKXDD/Fw5rXqYVZpAPRp0UhskQYkol1uoRbIxawAcHfS3cWD28RXwWlGD6/m6X9ZS56tlO7r1460cBRMeOy8Q+T8WpIMLb+ZJUYElfM20wo5ZhXNwo9INbgDrJVZbWLiSL58j1UG8VEpEiM3kFAmRGW9bM96lohBDkRzUBgC5rPsIfn0sfTk089ViFRZxkeGePtXbLnCEsjebTZXvEbtwC693awFXOsFTEscl0TzSljU0cxMuXuFplus8VbFy5BEdgwOQ7ZbysT7idQs4C76W2sLGVXxFZlh/0FQwJ6p5ZC570s1zPLxYFGGI/3TEGeHzNcC8zWZPN25YFGOuCLla1FktidlaNWIjVvIEiqhBl5TRkekf7kffpQyfc1H6hS5tIXjYm6diQXiG74n2UTgP0jXwC1VvDEPkjpLlvjiObkqF0q+QvFTB+XOO3a1KppEHVcuaXXtcZfco7EmnxtnmpkNNbeG4ZZRH/7EPz8Sx1ILwYP9v8ehiamF0kMXcMXUhlWzdP3Hi7taxqg2eJ7UNvgPu3+p5

RNG Seed: 1094133203

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xca960, 0xef7050})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/druid.glob..func4.1(0x2817ba0, 0x20b2ea0)
	/home/runner/work/sod/sod/sim/druid/item_sets.go:52 +0x7
github.com/wowsims...

**Comment by kayla-glick** [comment]
Hm weird I clicked the provided link but I'm not getting an error. @rosenrusinov was this fixed already?

**Comment by FelixPflaum** [comment]
I probably fixed that in https://github.com/wowsims/sod/pull/633
Even though I don't know how it even got to that code before that, but the crash reason there (bear form being nil) is gone.

**Comment by kayla-glick** [comment]
Ok cool sounds good @FelixPflaum thanks!
