### ISSUE TITLE
Trueshot Aura AP Values

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/sod#618]
![image](https://github.com/wowsims/sod/assets/118020821/982dd903-d677-4b71-b751-47dda227bc64)

Sim is currently giving 75 melee AP.  Need to update to the new values of 300 for ranged and 150 for melee.

**Comment by chimikoo** [comment]
Should have been fixed now. The tooltip in the buff selection will still say 75 but it actually gives 150 now.

**Comment by kayla-glick** [comment]
Yeah this should be fixed already https://github.com/wowsims/sod/pull/606
