### ISSUE TITLE
Wailing Berserker's Plate Armor, 2 set 1% Hit bonus not functioning

### ISSUE THREAD

**Issue by paulio64** [wowsims/sod#637]
**Describe the bug**
The 2 set bonus for the Wailing Berserk's Battle Plate is not awarding the 1% hit bonus to spells and attacks.

**To Reproduce**
1. Go to https://wowsims.github.io/sod/retribution_paladin/
2. Add a 2 set of Wailing Berserker's Battle Plate to Chest/Legs/Boots
3. Check Hit on character sheet
5. Add Hit gear equaling to what should be 6% melee hit
6. Check results page and you will see melee misses.

**Expected behavior**
The two set bonus should provide 1% melee and spell hit.

**Sim Links and Screenshots**
https://imgur.com/a/LxJPdn7

https://wowsims.github.io/sod/retribution_paladin/#eJztk01oE0EUx/fNbLKTScdORpHJ4EctKEsgstm40PSStScRDwE99KiFSCsFi4LoMQVF6iUglJiDDfQiAT8uXlyF4MXmZG3Rgh5axJNgiRdBWtHZ3SJexIMVPfg/vPm/mfd+MwwzlBHkwBD46DS0EIz0EZDwANxx6AEIQ61YNFmZPHOleoFj6Q6YuVmgaf65zuTbtL3cUNTkiwGjFn/6mMlWSZtnAZMvkrrogzYty/70UepkswFyzrLXdEeaf3nE5Lxlb/YkJXwmYPa9Wji9HkTUd+2sTno6Wd1h362FW7x+znRcCsL4JvIbnTA+XO+jhh5v3GSu4mDDEDqGxmEKXbauA24AdAAWAIavmXQNGf/1RyVa8LeP8Cu9R8YII8CRRD5UoA5wfLfnOJ5TyOe9olvUtuA6TrHgVdCoOWac64LElFPcBmMwRS2ayLuHvYvCVGjYECllqQTFfPaksNUhujOXIVjgGdNQhCapWdCVbj8lSnty/zZEFLFf7aWZXD9JCDRmKE2k2HUOhh1k+Yl+wYKquGO1nf3u9U8R+9QemmrCFuzn4OQPYC8GB/Ngm1ML0ARjCZLKJJjjwQ5OxZcy4Wdis8vPNm+F6pZL8cxi+cDZSK/Kbh2TlWkmyInqperkgOfII7l/7E/1av62cKbv/BaHq6/bcw6tQhT9Ob80cb53tXvqZfno1oo/Ct8AtIKEqA==

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Chrome
 - Version 123.0.6312.106 (Official Build) (64-bit)

**Additional context**
I specifically removed each individual piece to confirm it is the 2 set Hit bonus that is missing.

**Comment by kayla-glick** [comment]
Fixed by https://github.com/wowsims/sod/pull/639
