### ISSUE TITLE
APL Condition Feature Request: Resource Deficit (Or, alternatively, Talent Known)

### ISSUE THREAD

**Issue by Lisonna** [wowsims/sod#641]
**Is your feature request related to a problem? Please describe.**
Rogues base several decisions based on pooling energy and how close we are to energy cap. However, we also have multiple effects which alter our maximum energy. To track this in an APL, we would need to create multiple APLs based on if these effects exist or not. These effects are not castable spells, or auras, they are Talents and/or set bonuses. 

**Describe the solution you'd like**
Ideally, a Resource Deficit condition would be able to always hold the same value and consistently pivot decisions in the Rogue APL appropriately. 

**Describe alternatives you've considered**
Alternatively, being able to pivot based on Talent Known could be doable, but that is more maintenance for the APL because it's extra fields that have to manually be kept in sync. It also wouldn't account for anything that increases the effect that isn't from a talent. I think a Talent Known condition could be helpful for other cases but it is the less ideal solution for my specific, current use case of interest.

**Comment by Lisonna** [comment]
I forgot that Compare can compare against more than just constants, so Resource Deficit could just be created out of having a Max Energy value and using compare and a math combination, as an alternative option. Personally I'd prefer Energy Deficit as its own independent value under Resources, because it has the potential to be used pretty regularly throughout Rogue APLs, however a standalone Max Energy value would be fine as well if the team prefers that.

**Comment by rosenrusinov** [comment]
To me it makes sense to add both MaxEnergy (if it doesnt exist already) and Energy Deficit (which if i understand correct is how much below cap you are)

**Comment by vigo2** [comment]
For now, this is implemented as "Energy Threshold >= X", which additionally allows X <= 0, which are then relative to the energy cap (e.g. X = -20 is the same as X = 80 w/o Vigor, and X = 90 w/ Vigor)
