### ISSUE TITLE
Crash Report 433655128

### ISSUE THREAD

**Issue by schemek** [wowsims/sod#650]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJztVE9IFFEcnt/M7Myb3+7Q+NB6vgrWjeCxsDK7OqVedvIQEhEudFg6RAqGhZAURN2s0KRLIkQkQVt0KQu2bmFESFDSwYoK6Q9sQhcvWR2UDtWbWXcpITxk1KHv8Jvf+75vvvfmDe9hHVHjqgst4KsdsA96oV8dUaHdYRAHH0oAeSjC9l6gCr9sodHZ13W857BjMBE3kxcBo87XEZvNRsXV8XrUndJJG03n4V2bFVrRcOb2sKeG9HyckIQpigtMDmbv2eySKYaKHNF5tpfNGGJCCsR5PGKL26Hl00SYufilXg4+y8GwKRYXmZzg1bQt660zIGvxXFBfS8ZyPnS5M4SdqpWz35R+2SiZOicqIi1ah5aHY7EBiA2Ddh+gbUjHkqr8xx8FLcDfXsJKmFOV9ogPwwA7XNdzM01uFSkvYJoyS7yXTrk/o1PPk27l4IDGNFyHFjcxQr7lhJpAJGikmhu3ekeqwrus0JaEpsbMD8LbtNCXhHT4Rh0SbqBO3hQgYaG0pAI/RV6m389wqnO1TaEb+XqsSa4hOlW7lSALtS3e5tAkDw3dwPly2ZOyfDiDLo1xGYgGeX4aBFTD5RmkCR7HtclaAlRaETxuTUKg3Vlgoee69GziDb/0BB91xRTqiqbzOWFSzhnaiShamYCazgmdVxoa5eUtupETkWXGYNeq29f/CMZAGVUNrhOVaYlJzSr/3V1+TaWpH7sQYCrbWmaeZBv2h3iZzYxq5Nq4TcnOnqM9ffFmlyXlvfaPXQ/zJ/xVycHCb+U8iNVsW5V1SKTD6p/1Ww8cmh+c2v0iW4n28/AdmuukdA==

RNG Seed: 1399877189

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xcaea0, 0xf04250})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Aura).Activate(0x0, 0x23ff440)
	/home/runner/work/sod/sod/sim/core/aura.go:550 +0x2
github.com/wowsims/sod/sim/common/sod/item_effects.init.1.func17.1(0x23ff440, 0x22df000, 0x23e7180)
	/home/runner/work/sod/sod/sim/common/sod/item_effects/phase_3.go:637 +0xa
github.com/wowsims/sod/sim...

**Comment by kayla-glick** [comment]
Hey @schemek the issue here is that your character is using invalid gear. The character is set to level 40 but the Serpent's Striker offhand is a lvl 50+ item
