### ISSUE TITLE
Warlock Talent "Improved Imp" not working correctly

### ISSUE THREAD

**Issue by DipsyHyb** [wowsims/sod#667]
The warlock talent "Improved Imp" should only increases the base dmg of the ability by 30% not the entire damage (that is base damage + spellpower coefficient).

Here are two images of Details, once without and once with the talent. Rank 5 firebolt was used, so average 55.5 base dmg\
The warlock used for this has 305 spellpower.
In the first image the average dmg for normal hits is 86, in the second one 101. The difference 15 is very close to  $`55.5*0.3=16.5`$ but quite far from the supposed   $86*0.3=24.9$
![image](https://github.com/wowsims/sod/assets/166833829/14fe7a51-a523-4bd8-9f5d-912fdb543bf4)
<img width="1159" alt="image" src="https://github.com/wowsims/sod/assets/166833829/58efb318-4712-4a9c-8066-ac8d36d291e9">

Meanwhile in the sims you have the following difference, once without and once with Improved Imp:
<img width="362" alt="image" src="https://github.com/wowsims/sod/assets/166833829/ed0d0918-a729-456f-be6b-6a8c795c5f6f">
<img width="365" alt="image" src="https://github.com/wowsims/sod/assets/166833829/ce32fcfb-369f-48b7-b67a-5ef90890b203">

The difference here is pretty much exactly 30%

To reproduce you can use any warlock in SOD and just shoot something with your imp. A warlock with high spellpower is recommended or it could be hard to see the difference.

**Comment by vigo2** [comment]
Fixed in #681
