### ISSUE TITLE
Rolling Thunder - Shaman Bracer Rune

### ISSUE THREAD

**Issue by tilarn** [wowsims/sod#678]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] Unable to select a number of charges associated with Lightning Shield under Auras

**Describe the solution you'd like**
If stack amounts could be added to lightning shield and rolling thunder damage calculated with that it would be appreciated
**Describe alternatives you've considered**
Not a programmer and dont know the best for this to come about, but
IF->Rune-Rolling Thunder
IF->Aura stack amount->Lightning Shield >=XYZ
Cast->Earth Shock
**Additional context**

**Comment by kayla-glick** [comment]
Lightning shield charges can be tracked already using Aura num stacks as in the Ele APL
![Image](https://github.com/wowsims/sod/assets/12898988/2d6b5d39-e516-45e3-b7ef-cd58260fc1dd)
