### ISSUE TITLE
Crash Report -1838179782

### ISSUE THREAD

**Issue by Peoplesman** [wowsims/sod#683]
Link:
https://wowsims.github.io/sod/balance_druid/#eJzj4uVgEmAyYLRgzGCcwMToxCTBKMQg1cXGxRaQk1iZWiTAImGkwKhVy8Uh8HIXr8acVVJcLAJXF/ICyRcHQeSnq7xAuYY9vBrnV0hysQucltf4vxzEmBitseOLBFBu6jMejR1fQaxGoKrW3ZJA1vODvBqHgGJsApdiDf6zAs1pu8bLxSzwKQzI3Ac2eN1uXi4GIL3iKY+REAerB2MFXwcj6wRGlhWMjDcYuazaWLgeMDGMApoCoQWMA+0EQuAVE4MTuwNjAOMERkYvQ1NDAwNTA2NjAyNTINPUUNcADeiaovIDGCNYkxiygOm+4ARjJ9S3Ig6zGBkWMbJIMXExKB1g5oSI+jkIwqQlZ80EgZP2lhCRC/aKaWBwzd5oAjPH9SZeIQ6f1LLUHAVTAwkTrUGWUD80OlDFnKYVFJkjIPWfOu4AAkMw6TDfwTIz/0PryZCr9o5QGYcIRgCy/GFU

RNG Seed: 3589576808

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xcc7e0, 0xf34410})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/druid.(*Druid).tryElunesFiresSunfireExtension(0x28b2000, 0x239cea0, 0x23cd000)
	/home/runner/work/sod/sod/sim/druid/runes.go:244 +0x8
github.com/wowsims/sod/sim/druid.(*Druid).newWrathSpellConfig.func1.1(0x239cea0)
	/home/runner/work/sod/sod/sim/druid/wrath.go:86 +0x7
github.com/wowsims/sod/sim/core.(*Simulation).Step(0x239cea0)
	/home/runner/work/sod/sod/sim/core/sim.go:503 +0x25
github.com/wowsims/sod/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/sod/sod/sim/core/sim.go:460
github.com/wowsims/sod/sim/core.(*Simulation).runOnce(0x239cea0)
	/home/runner/work/sod/sod/sim/core/sim.go:351 ...

**Comment by FelixPflaum** [comment]
Should be fixed once pushed change is live.
