### ISSUE TITLE
Crash Report 828868098

### ISSUE THREAD

**Issue by oznustn** [wowsims/sod#684]
Link:
https://wowsims.github.io/sod/mage/#eJzj4uZgMmC0YMxgnMDE6MSiwOjAKMQgNZmNiy0gJ7EytUiASUJDgVmrlZGLQ+DjQV6NQ1OluFgEHjbxAsnvB3m52AXWzOGV+MIGlP4GlG7fJQFkLW3i1TgKVMgh8Bko9nQnSOzMQl6NewdArK9AsSkHQaxPQNaSSyADF4MN3D8bRD4Gs3995gGSi5pB7GUtIHJxM6+RgAC3B3MEYwJjBV8HI/MCRkarNhauB0wMo4CmQGgB40A7gRB4xcTgxC4ATL4djIxexgZoQNfUwBRVwMjA2MjAyNjY0NjI2NTQwMAwgDmCO4khi0mCseAEYyfUvyYOsxgZTjGySDFxMCkdYuaEiPo5CEIYIg6Ss2aCwEl7S4jIBXvFNDC4Zm80iZlj5WpeIQ6f1LLUHAUTAwktBXatQZZYPzQ6UMUcrgUUmXOER9CRKu4AAkMw6dDvYJmZ/6H1ZMhVe5jRDhGMAA1EYoY=

RNG Seed: 3016152287

runtime error: index out of range [3] with length 3
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0x13d340, 0x2812150})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/mage.(*Mage).newBlizzardSpellConfig(0x2800000, 0x1)
	/home/runner/work/sod/sod/sim/mage/blizzard.go:42 +0x19
github.com/wowsims/sod/sim/mage.(*Mage).registerBlizzardSpell(0x2800000)
	/home/runner/work/sod/sod/sim/mage/blizzard.go:21 +0xa
github.com/wowsims/sod/sim/mage.(*Mage).Initialize(0x2800000)
	/home/runner/work/sod/sod/sim/mage/mage.go:121 +0xa
github.com/wowsims/sod/sim/core.(*Environment).initialize(0x2394a00, 0x238f780, 0x229f650)
	/home/runner/work/sod/sod/sim/core/environment.go:134 +0x25
github.com/wowsims/sod/sim/core.NewEnvironment(0x238f780, 0x229f650, 0x0)
	/home/runner/work/sod/sod/sim/core...

**Comment by FelixPflaum** [comment]
Should be fixed once pushed change is live.
