### ISSUE TITLE
Crash Report -1342969158

### ISSUE THREAD

**Issue by pachulius** [wowsims/sod#700]
Link:
https://wowsims.github.io/sod/balance_druid/#eJzj4udgEmAyYLRgzGAsYJzAxOjEJMEoxCA1kY2LLSAnsTK1SIBNwkiBUauBkYtDYGETr8b7XZJcLAIPm3iB5IeDIHIvkM0hcHESr8b5FZJA1qqnPBr/l4NYDbt5NXZ8keBiF+iL1tjxVQIodBmorHU3SLJ5D6/GIaAYs0CjNdCUK7tBZt0+DyJvgdnzLoHI1c0gctVsXiNRDlYPxgq+DkbWCYwsCxiZVjAy3mDksmpj4XrAxDAKaAqEFjAOtBMIgVdMDE7sDowBjBMYGb0MTQ0NDEwNjA0MjExNDY1NDXUN0ICuKSo/gDmCMYkhC5j8C04wdkJ9K+Iwi5FhESOLFBMXg9IBZk6IqJ+DIExactZMEDhpbwkRuWCvmAYG1+yNJjBzXG/iFeLwSS1LzVEwNZAw0RpkCfVDowNVzGlaQZE5AlL/qeMOIDAEkw7zHSwz8z+0ngy5au8IlXGIYAQAq6piOw==

RNG Seed: 4161483070

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xcce60, 0xf3d570})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/druid.(*Druid).tryElunesFiresSunfireExtension(0x2166000, 0x2833320, 0x22be000)
	/home/runner/work/sod/sod/sim/druid/runes.go:244 +0x8
github.com/wowsims/sod/sim/druid.(*Druid).newWrathSpellConfig.func1.1(0x2833320)
	/home/runner/work/sod/sod/sim/druid/wrath.go:86 +0x7
github.com/wowsims/sod/sim/core.(*Simulation).Step(0x2833320)
	/home/runner/work/sod/sod/sim/core/sim.go:503 +0x25
github.com/wowsims/sod/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/sod/sod/sim/core/sim.go:460
github.com/wowsims/sod/sim/core.(*Simulation).runOnce(0x2833320)
	/home/runner/work/sod/sod/sim/core...

**Comment by FelixPflaum** [comment]
Should be fixed once pushed change is live.
