### ISSUE TITLE
Maelstrom Weapon Stacks do not reset after used

### ISSUE THREAD

**Issue by bidini** [wowsims/sod#701]
**Describe the bug**
Description in title.

**To Reproduce**
1. Go to the Shaman Enhancement (Season of Discovery) sim webpage.
2. Go to Gear and add the Maelstrom Weapon rune to any waist gear.
3. Set one enemy with 100 duration.
4. Go to Rotation and add a new action " Cast Chain Lightning", if Compare - Aura Num Stacks - Self - Maelstrom Weapon == Constant 5. 
5. See error in Results - Timeline: Maelstrom Weapon reaches 5 stacks and it never goes down again.

**Expected behavior**
Timeline should show Maelstrom Weapons stack dropping to zero after the cast of Chain Lightning.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Firefox
 - Version 124.0.1

**Additional context**
The bug leads to unrealistic high DPS for Shaman.

**Comment by vigo2** [comment]
I can't reproduce this.

**Comment by kayla-glick** [comment]
I also tried to replicate this and everything I see is expected

![Image](https://github.com/wowsims/sod/assets/12898988/5ce786e1-95ec-4d6c-8e06-87154b026381)



![Image](https://github.com/wowsims/sod/assets/12898988/b1816db3-c946-48bf-add5-475a583dc35c)

**Comment by bidini** [comment]
Apologies, to reproduce the bug you need to cast Healing Wave. Using Healing Wave should remove the Maelstrom Weapon stacks. Healing Wave certainly does not contribute to DPS, but it is something that sometimes needs to be included in rotations to budget for global cooldowns. Picture attached.

Ben

￼
