### ISSUE TITLE
Rogue Helm Rune Focused Attacks still 2 Energy instead of 3

### ISSUE THREAD

**Issue by Rerox-WoW** [wowsims/sod#702]
In the recent Hotfix, the Rogue Helm Rune "Focused Attacks" was changed to provide 3 Energy per Crit, instead of 2.
The Sim still shows only 2 and the calculation seems to support that.

**Comment by sanguinerarogue** [comment]
If you can double check on your side or post a link to your sim from the export tab.  It appears to be working on mine:

![image](https://github.com/wowsims/sod/assets/118020821/cf81022f-0da2-4816-a116-6c32e40a910f)

![image](https://github.com/wowsims/sod/assets/118020821/c2316080-6d4d-4c96-924c-169482fc48cf)

**Comment by Rerox-WoW** [comment]
Yes works now, either there was an update or I had an cached older version. (not using the downloaded client).

**Comment by Rerox-WoW** [comment]
Yes works now, either there was an update or I had an cached older version. (not using the downloaded client).
