### ISSUE TITLE
Crash Report 1053016461

### ISSUE THREAD

**Issue by jwvanderstam** [wowsims/sod#703]
Link:
https://wowsims.github.io/sod/balance_druid/#eJzj4udgEmAyYLRgzGAsYJzAxOjEJMEoxCA1lY2LLSAnsTK1SIBNwkiBUaudkYtDYGETr8b7XZJcLAIPm3iB5FYgySzwPIqLW+BAE6/EIzaN8yskgep6ZjJq/F8uycUpsNhPQkhjxxcJoOCN87waO76CWJeBxrTulgTqat7DK9HPrnEIKMwisH8GI5BcDDa5ew6I/Rhs/iIbIHPbbpDwqtm8RkIcrB6MFXwdjKwTGFlWMDLeYOSyamPhesDEMApoCoQWMA60EwiBV0wMTuwOjAGMExgZvQxNDY0MTE0NDAyNTE0NjU0NdQ3QALpAAGMEaxJDFjALFJxg7IT6VsRhFiPDIkYWKSYuBqUDzJwQUT8HQZi05KyZIHDS3hIicsFeMQ0MrtkbTWDmuN7EK8Thk1qWmqNgaiBhojXIEuqHRgeqmNO0giJzBKT+U8cdQGAIJh3mO1hm5n9oPRly1d4RKuMQwQgAgzxh4Q==

RNG Seed: 2158817356

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xcc7e0, 0xf34410})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/druid.(*Druid).tryElunesFiresSunfireExtension(0x281e000, 0x21f38c0, 0x2384000)
	/home/runner/work/sod/sod/sim/druid/runes.go:244 +0x8
github.com/wowsims/sod/sim/druid.(*Druid).newWrathSpellConfig.func1.1(0x21f38c0)
	/home/runner/work/sod/sod/sim/druid/wrath.go:86 +0x7
github.com/wowsims/sod/sim/core.(*Simulation).Step(0x21f38c0)
	/home/runner/work/sod/sod/sim/core/sim.go:503 +0x25
github.com/wowsims/sod/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/sod/sod/sim/core/sim.go:460
github.com/wowsims/sod/sim/core.(*Simulation).runOnce(0x21f38c0)
	/home/runner/work/sod/sod/sim/core...

**Comment by jwvanderstam** [comment]
Loading gear from the add-on leads to this crash report

**Comment by FelixPflaum** [comment]
Should be fixed once pushed change is live.
