### ISSUE TITLE
Cant SIM my Balance Druid in Season of Discovery

### ISSUE THREAD

**Issue by azus3** [wowsims/sod#707]
Using https://wowsims.github.io/sod/balance_druid/ to SIM my gear on my Balance druid in Season of Discovery

Imported data via addon called "WowSimsExporter v2.8 Classic SoD".
When trying to SIM i get a SIM crash with following data/text:

https://wowsims.github.io/sod/balance_druid/#eJzj4udgEmAyYLRgzGAsYJzAxOjEJMEoxCDVwcbFFpCTWJlaJMAmYaTAqFXNxSFwdRKvxvtdklwsAlsv8XIxC7yIAhLPo4AyB5p4Nc6vkASyjgFZ/5dLcrELTIzW2PFFAih0Gii04yuIdRnIat0NUnYJaNQhoBiLwIEZjEBycRMvkNx3EEQ+BbNfAUkGIL3iKY+REAerB2MFXwcj6wRGlhWMjDcYuazaWLgeMDGMApoCoQWMA+0EQuAVE4MTuwNjAOMERkYvQ1MDAwNTUwNjQyNTU0NjU0NdAzSALhDAGMGRxJAFTPUFJxg7ob4VcZjFyLCIkUWKiYtB6QAzJ1iwIc1BECYtOWsmCJy0t4SIXLBXTAODa/ZGE5g5rjfxCnH4pJal5iiYGkiYaA2yhPqh0YEq5jStoMgcAan/1HEHEBiCSYf5DpaZ+R9aT4ZctXeEyjhEMAIAuEVglA==

My elemental shaman is not affected by this problem, and can SIM without problems.

**Comment by FelixPflaum** [comment]
Should be fixed once pushed change is live.
