### ISSUE TITLE
Crash Report 1604507066

### ISSUE THREAD

**Issue by Callz93** [wowsims/sod#737]
Link:
https://wowsims.github.io/sod/warrior/#eJzjEuRgUmByYEpg3MHIdICRaQIToxOfBGME4wbGlATGDMYTjIxCDFKz2LjYAnISK1OLBFglNBQ4teYycnEL/JzAK/GIW+NOuxQXi8CF3bxc7AKH9vBKLLAEMo7v5pW4yAZU9BbIeMSmsfe0BJDzZwajxF0+jZ0dUkDO3128Evf5NO7MleTiEDg9gVfjCJj1bjevxqnfkkAFH3aDFXSdlwCav30GI5C8BLSFRWDRXBD79nmQjWuAippFgIy1EAaLwOzdvEZ8GqwWzAWMFRyXGBlmMDJatbFwPWBiGAU0BUILGAfaCYTAKyYGJw4Hxg5GxgmMjF5SxgbGBiYGBgbGugamQGhgYGoCpAyBAgEsEUxJDFnCEsxc3FwMSuxcrFzMuobFQkxSDAUnGGcxMqxiYpNiEWCUYFTawMwJMdzPQRDCEHGQnDUTBE7aG01i5li5mleIwye1LDVHwcRAQkuBXWuQpcUPjQ5UMYdrAUXmHOERdKSKO4DAEEw69DtYZuZ/aD0ZctUeZrRDBCMA7WtmUA==

RNG Seed: 3045108024

Serpent's Striker requires level 50+
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:49 +0x10
panic({0x9d340, 0x28b7f0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.SerpentsStrikerFistDebuffAura(0x2812000, 0x28)
	/home/runner/work/sod/sod/sim/core/debuffs.go:1152 +0x9
github.com/wowsims/sod/sim/core.(*Unit).NewEnemyAuraArray(0x2874000, 0x1c4be8)
	/home/runner/work/sod/sod/sim/core/aura.go:916 +0x11
github.com/wowsims/sod/sim/common/sod/item_effects.init.1.func9(0x2874000)
	/home/runner/work/sod/sod/sim/common/sod/item_effects/phase_3.go:435 +0x4
github.com/wowsims/sod/sim/common/sod/item_effects.init.1.CreateWeaponProcSpell.func14({0x296510, 0x229be50})
	/home/runner/work/sod/sod/sim/common/itemhelpers/weaponprocs.go:74 +0x7
github.com/wowsims/sod/sim...

**Comment by rosenrusinov** [comment]
The error message is very self explainatory. You have equipped a weapon that requires 50+ and you're simming for level 40

**Comment by Callz93** [comment]
The problem is obvious if you actually look at it, your website has pre made ”P3” sets with settings suited for P3 and gear, but still has some error when trying to simulate it. I have not done anything besides entering your website, and tried to sim your own P3 gear set and settings. After this problem occured your website directed me to making an account and also send an error report, did not make much of it, but here we are.

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

________________________________
Från: rosenrusinov ***@***.***>
Skickat: Saturday, April 27, 2024 7:06:29 PM
Till: wowsims/sod ***@***.***>
Kopia: Callz93 ***@***.***>; Author ***@***.***>
Ämne: Re: [wowsims/sod] Crash Report 1604507066 (Issue #737)


The error message is very self explainatory. You have equipped a weapon that requires 50+ and you're simming for level 40

**Comment by rosenrusinov** [comment]
Change your level dropdown to level 50 and the p3 sets will work. Sadly the player level selection is not something tied to the gear/talents/rotation sets so you will have to maintain it yourself.

**Comment by rosenrusinov** [comment]
We can look into improving the error messaging so it directs the user on how to fix the problem

**Comment by Callz93** [comment]
Thank you!


Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

________________________________
Från: rosenrusinov ***@***.***>
Skickat: Saturday, April 27, 2024 7:39:12 PM
Till: wowsims/sod ***@***.***>
Kopia: Callz93 ***@***.***>; Author ***@***.***>
Ämne: Re: [wowsims/sod] Crash Report 1604507066 (Issue #737)


Change your level dropdown to level 50 and the p3 sets will work. Sadly the player level selection is not something tied to the gear/talents/rotation sets so you will have to maintain it yourself.
