### ISSUE TITLE
Missing buff: Rapid Cutting

### ISSUE THREAD

**Issue by Dismayus** [wowsims/sod#764]
It doesn't seem like the Rapid fire melee attack speed buff for melee (sunken temple 3set) is being taken into account on the sims. I am looking to find out if it's viable to run rapid killing for a 1min cd 10% attack speed boost vs Catlike Reflexes for 50% off the cooldown of flanking strike. Having the 3set makes Rapid Fire also grant Rapid Cutting, which doesn't show up on the buffs section in the sim details. There seems to be no dps difference at all when casting rapid fire with the 3set active. 
Links to [WOTLK Wowhead](https://wowhead.com/classic/items "https://wowhead.com/classic/items") for each item:
https://www.wowhead.com/classic/spell=450084/rapid-cutting

**Comment by kayla-glick** [comment]
Hey @Dismayus I see code in the sim that adds the 10% melee speed buff to rapid fire when using the Dread Hunter's Chain 3pc set 
https://github.com/wowsims/sod/blob/ddc49c8f0a88129f6e397e3c99eb753cfe3cb28e/sim/hunter/rapid_fire.go#L15-L34
