### ISSUE TITLE
Firestone Spell

### ISSUE THREAD

**Issue by Vancopland** [wowsims/sod#772]
Hello wowsim team!
I noticed that Firestone, and any level of the spell created item for warlocks, isnt in the DPS or Tank sim for them. Though it is more relevant for the Tank sim due to melee weaving.

Could you please add the class created item! Ill provide the link down below.

**Additional context**
I have an idea I would love to sim for melee weaving caster dps, and I would like to test if the Firestone is better than Shadow oil or Lesser Wizard oil. They take the same slot and Ive wanted to test out Firestone melee weaving since phase 2 but it was never supported and lesser wizard oil seems to be better for meta warlocks, or simply using Shadow Oil.

here is the link to the Spell information on Firestone (Greater) the one that is currently avialable at level 50:

Spell: https://www.wowhead.com/classic/spell=17952/create-firestone-greater
Item: https://www.wowhead.com/classic/item=13700/greater-firestone

I hope this email found you well!

Kindest Regards,
-Vossiel

**Comment by kayla-glick** [comment]
Hey @Vancopland 👋 The ability to select Firestone/Spellstone is only available when you unequip your off-hand. When you do, you'll see an extra input in the Setting Tab's Player inputs and you'll be able to select one of the stones there.

![Image](https://github.com/user-attachments/assets/0ffcce27-9a2d-4470-ab7b-f45b23bd745d)
