### ISSUE TITLE
[Phase 4] New Runes: Hunter

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#791]
# TODO
- [ ] Giantstalker Pursuit set bonus https://www.wowhead.com/classic/item-set=1702/giantstalker-pursuit
- [ ] Giantstalker Prowess set bonus https://www.wowhead.com/classic/item-set=1703/giantstalker-prowess

**Comment by ncberman** [comment]
#829

**Comment by adocoD** [comment]
List of P4 hunter changes:

Runes
	New runes:
		- Resourcefulness = Trap mana cost -100% cd from 15 to 9s
		- Cobra Slayer = 5% chance per auto for MB proc, +5% for each auto. 100% on dodge. +40% AP on MB
		- Kill Shot = 100% weap dam + 138.435. 15s cd. Insta reset on 20% or lower
		- Wyvern Strike = 100% weap damage, 8s cd, Bleed for (3 / 100 * 8 * Attack power) over 8s

	Deleted runes:
		- Heart = baseline +200 mAP, Kill command, Invigoration

	Old rune changes:
		- TNT = Explo initial increase 50% of mAP. Immo dot increase 50% of mAP
		- Catlike Reflexes = Kill command gone
		- Rapid Killing = Also 40% Melee AS (CD -80%)
		- Check Melee Specialist
		- Check Steady Shot (100%)
		- Check DW Spec
		- Check Chimera
		- Check Explosive
		- Flanking strike = 5% all damage increase 10s, 3 stack max, pet auto 33% reset chance
		- Carve = 65% + 50% on primary (so 97,5 total)
		- Check Beast Mastery
		- Lone Wolf = 40%
		- Cobra Strike = now also from all Strikes and Mongoose Bite

Talents
	MM:
		- Efficiency = Also for Raptor, Flanking, Wyvern
		- Lethal Shots = also for all melee, possibly all crit though
		- Mortal Shots = also for MB, Raptor, Wing clip, Flanking, Wyvern
		- Trueshot = only rAP (200 rAP)

Gear
		- Tier 0, 0.5, 1 sets


Other Notes:
		- Faster OH will be better for Dual wield cause of Mongoose procs (no daggers cause of normalization)

**Comment by ncberman** [comment]
Created a new PR for some of the easier changes #834

**Comment by ncberman** [comment]
Have a new PR to address the minor rune changes, Rapid Fire and Cobra Strikes as well as update efficiency, lethal shots, and mortal shots talents. #839

**Comment by Kawney** [comment]
> V - Flanking strike = 5% all damage increase 10s, 3 stack max, pet auto 33% reset chance
Does not reset off of pet autos - it resets off claw/bite similar to Focus Fire

**Comment by ncberman** [comment]
Created a PR to add Wyvern Strike, pretty sure the implementation is correct but wouldn't mind getting a second set of eyes on it.
link: #841

**Comment by adocoD** [comment]
Unless I am mistaken only Kill Shot and baseline mAP of heart of the lion are left open.

**Comment by ncberman** [comment]
> Unless I am mistaken only Kill Shot and baseline mAP of heart of the lion are left open.

I think the heart of the lion ap buff is already live: https://github.com/wowsims/sod/blob/51fcbd868e76e793316e216339ba65a08ebf22fc/sim/core/buffs.go#L850

Gonna start on kill shot today

**Comment by adocoD** [comment]
Apparently in the sim explo overwrites the immo dot. Immo dot should run its full duration while explo dot is active in the background. When Immo ends the explo dot gets active for its remaining time. Immo always takes priority.

**Comment by ncberman** [comment]
> Apparently in the sim explo overwrites the immo dot. Immo dot should run its full duration while explo dot is active in the background. When Immo ends the explo dot gets active for its remaining time. Immo always takes priority.

Hmmm I guess I misunderstood the log I was looking at, It looked to me like it was just overwritten. So the correct interaction would be:
You cast Immolation Trap and 10s later Explosive trap, then immo does damage for its full duration, explosive trap causes initial damage and applies its DoT (but DoT doesn’t do damage). Immo trap wears off at 15s and explosive trap DoT has 15s left of duration so it starts doing its DoT damage?

**Comment by adocoD** [comment]
> > Apparently in the sim explo overwrites the immo dot. Immo dot should run its full duration while explo dot is active in the background. When Immo ends the explo dot gets active for its remaining time. Immo always takes priority.
> 
> Hmmm I guess I misunderstood the log I was looking at, It looked to me like it was just overwritten. So the correct interaction would be: You cast Immolation Trap and 10s later Explosive trap, then immo does damage for its full duration, explosive trap causes initial damage and applies its DoT (but DoT doesn’t do damage). Immo trap wears off at 15s and explosive trap DoT has 15s left of duration so it starts doing its DoT damage?
> 
> more simply immo trap and explosive trap DoTs can exists at the same time however explosive trap DoT can only do damage if there is no immo DoT

You're on the dot

**Comment by Kawney** [comment]
It looks like with the latest addition of Kill Shot, the Cobra Slayer rune has disappeared from sim

**Comment by ncberman** [comment]
> It looks like with the latest addition of Kill Shot, the Cobra Slayer rune has disappeared from sim

Looks like it was a casualty of #856

**Comment by Kawney** [comment]
Another bug found- it doesn't look like the Trap Mastery talent (https://www.wowhead.com/classic/spell=19377/trap-mastery) is implemented in the current sim. Testing different variations of the sim with VS without the talent doesn't lead to any differences in the miss rate of either immolation or explosive trap.

**Comment by adocoD** [comment]
The to do list has now been completed. I'm working on APL's now but already noticed some bugs/issues. Ill make a checklist for those here.

```
Issues
		- Raptor Strike queue time seems to be affected by both Ranged and Melee swings. Should only be melee. (speculation)
		- Movement seems to be a little bit too slow. This makes it hard to make a weaving rotation
		- Even though minimum ranged range is 8 yd, the sim only allows proper spell cast at 9 yd
```

**Comment by adocoD** [comment]
Nevermind. I think in the end you can ignore it.
Got an APL thats based on p1 weaving from someone and it works with some auto attack markers which for some reason completely fix the issue. Odd, but it all works now

**Comment by adocoD** [comment]
https://github.com/wowsims/sod/pull/862 Trap mastery fix
https://github.com/wowsims/sod/pull/864 Cobra slayer fix

**Comment by adocoD** [comment]
One more thing that has to happen is either a toggle in settings to turn bite off, or add a condition to the Focus Fire and Cobra Slayer runes where it disabled pet specialability when you have the rune activated.

I tried to look into it but couldn't figure it out.

**Comment by adocoD** [comment]
New issue discovered: Sniper Training currently doesnt properly lose or gain stacks in the sim on movement.

**Comment by adocoD** [comment]
To do:

```
- Fix Lion AP
- Readjust OH Raptor/Carve
- Fix ammo damage
- Add Bite toggle
```
