### ISSUE TITLE
[Phase 4] New Runes: Shaman

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#792]

**Comment by Lastwolf1882** [comment]
I don't think the shield mastery rune is applying, unequiping and re-equiping the ring rune, causes a dps loss (around 3)

When it should cause a dps gain of around 10? (tested by manually adding 50 spell power)

**Comment by kayla-glick** [comment]
@Lastwolf1882 there's not currently any settings that enable you to tank on shaman in the sim, so the shield mastery's defender's resolve aura will never proc. I may explore a tanking shaman sim though since I've been maintaining the tank functionality anyways

**Comment by kayla-glick** [comment]
Oops didn't mean to close
