### ISSUE TITLE
Crash Report -1775393593

### ISSUE THREAD

**Issue by Peettah** [wowsims/sod#808]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJztVE9IFGEU3zczuzvzdHT8cm38TroZDUva7Kybfy47GkFYlkaEEEFGSomQJEjdTMk8hQRBSdASHcIKpEvUHhQpqlMlZR4Sq0vRRauDUpG9mf3jSpCHjDr0Dt++7/3e+7335ntvMSALJYIhmFANtrADDkEXDAlQX6DDIgg2TAPsgFE4chRqBQ2Yh5/LRV9TZ+upthOaV7dK/KHLgDna1H1Vf5tjXLtRjJL2NKGiX5u7p+rxGlIeJlT9mY+cPpIS9xujCzpdli6CPpNnDIxyunwn32mfkSBE1gYTqnGbNL/2KeGwEv6ZlNk8Y3FRJ/pJope0OxeBztELztk34SSMk1N/4bIiaWMJ1SoxoFqgzoQWOJnbC7mDII0DTAJ1Mw3KIxBqByR8LXj+yx8VFoe/XcJq8kHw1PttaIIhgAbTjJpmxMxIOV2jVsRy7FbEjIbLzZXSJLbIhz0ds15dxAAq3I9eeazZ8AVl9KFUHja7sRDlDtJl2pIs6/qUc+9eQwwiElC+tcKKLgNvYhmgsqKKgAD6uRdFuX97yhxZ4f+g2fCmgLDjzyQu1HoY5zqqwRxULMfpSbMh8bTCyngQdVaEyojkFPhtpBiV2+CoM3OcO78jCzqr5BZuYhvTXs6OpryclXa5kwjtsct9s8gQ2R7eiNtYHfKQLnuZ0pHJrgwLKebsWJf1KqSRlJXUTBmNfCfWsdgvCYtChbKPKRMuz10Kpu+FEM1KkqE7yA9gE9u9Kp33J7rK7JqzWhhJtf+ux1BYDk++yi2aBZbLkdO7yM/PggFsAy9NMy9nTRbqhrxvps9HAW6pX78UszDfgmUsmPWMzltjQSifmhUaPE4UihGzOzMHLMDXoYJ0bW/t7G5zmV7FgdXwKtzMQrg+FJAlhhOQHtdkfgvzQyrV5XAmW83Mc9cj6AUYBs95geZKF4PjouKuT+9+uyC5SIV28fAlRx7HapKWp7HSdlemYtaQKL/sU5m8q62nrbMkauqVoX/s73f+tL0mPH3Xf4tH40trUwdJ2D3tK3bNsePzZx7vexGrSyF2C/wAi7nqmA==

RNG Seed: 4257083892

runtime error: index out of range [0] with length 0
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0x144420, 0x245f170})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.DotArray.Get(...)
	/home/runner/work/sod/sod/sim/core/dot.go:296
github.com/wowsims/sod/sim...

**Comment by kayla-glick** [comment]
Hey @Peettah can you try clicking the ⚙ in the top right then "Restore Defaults" I accidentally introduced a bug with Flame Shock in the old APLs that causes this error and don't have a way to reverse it
