### ISSUE TITLE
Overpower is not being cast

### ISSUE THREAD

**Issue by kickfiz** [wowsims/sod#82]
**Describe the bug**
Overpower is not being cast at all

**To Reproduce**
1. Go to 'rotation' tab
2. Click on 'New Action'
3. Make either of the ones below in 3.1 and 3.2
3.1 Make a "If Can Cast Overpower" -> "Cast Overpower"
3.2 Make a "If Spell is ready Overpower" -> "Cast Overpower"
4. Sim and check results

**Expected behavior**
Under the 'Results' tab you should be able to see overpower being casted.

**Sim Links and Screenshots**
Sim link:
(https://wowsims.github.io/sod/warrior/#eJztU0Fo1EAUzZ+kyeRvs8RxbWcHa9e9mK4ISbYLrSAbiwcRkR48LJ6qsKVKQWlB9KZbKt7ssUYWVDyI4EUEC0UQrNgqUlHcXj0oqKeCgqhonSS7VdSLWMSD7/Dz8t789z8kg2lKArIbhmAGyB0gAykOFfk2AvMATBFPDdQHRw+erI7ZKndyZmESULO/TFmyPq9FdUZWw56tWfw9YMqek2RRd24/5FL9PA38lo7Uvl+znHt1IdkjyebqWcmeROxTVvYsxc3Oxwkh82anowlX4uwPb9tlfRFPuDph8ddpVKRw4WW7n7LBIX3aCeMU6NvrKr4iyn/8FTD3dzveEGXApMBJAGcB9rCiW/R7Xd8tlvyS50p4g1qFHlKONAhXkaEh2lClK5m8gZJs88ZXtXB9UyuNs6zoxFQIFHV68xI4qlhlrFNsQAxBHqWLOxwiWiQxLv/CiMKsfArNG6CjRuXvK6Ln3SlgXHT8aCXrsQ6RaalL9Wwc9m5Xa0oy/syQA6JFWI/YgpvYRqQhRBHyFtmFNG1jZEyJxiEpeiIxWLfoik39m9nnChMNev1ADhydbRU92M260AzjBaLb9XNY0zk2DyEo14guNBs45B+oZvJl9gXrEpIJsuH5CAvl/kR5XN48HKNR9kOVNmoWo3urx6ujuV6XF3K08I/duOXTwZrk4MU/yrHFytrs8R28uAbngv7DR5cnF/Y/K+9sOkEFvgIE2IvC)

**Desktop (please complete the following information):**
 - Windows
 - Opera
 - LVL5 (core: 106.0.4998.61)

**Comment by TheGroxEmpire** [comment]
Overpower can only be cast if you are in Battle Stance. I'll be adding Overpower aura in the APL so that the APL can stance dance to Battle Stance.
You are able to stance dance in the APL with something like this:
![image](https://github.com/wowsims/sod/assets/47816228/d4a997b1-98e4-4a9d-9f34-ef4e8314e3a8)
