### ISSUE TITLE
ZG Buff 

### ISSUE THREAD

**Issue by Anhak-Anhak** [wowsims/sod#840]
ZG Buff is being given on rogue sim without the option to turn off/on for sod and we are not in zg yet

**Comment by Anhak-Anhak** [comment]
Seems attached to ony buff maybe ony buff isnt being given but zg is? unclear

**Comment by kayla-glick** [comment]
Looks like I just had the wrong Spell ID in the aura for rallying cry. It was still providing the rallying cry stats but looked like the ZG buff because of the spell ID
