### ISSUE TITLE
Missing Dual Wield (Ele Sim)

### ISSUE THREAD

**Issue by t-mccawley** [wowsims/sod#86]
**Describe the bug**
The elemental shaman sim does not allow users to equip dual wield weapons (for example, Dagger of Willing Sacrifice in off-hand). By extension, it is critical that the sim support double rockbiter enchant (on MH + OH) for Shamanistic Rage. This is a bug as Shaman by default now are able to dual wield (after a quest chain).

**To Reproduce**
Check off-hand weapons available:
![image](https://github.com/wowsims/sod/assets/29646748/fb3f1d9e-3f68-483a-bb87-06f948b8646d)

**Expected behavior**
Off-hand weapons available with normal enchants and imbues.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version (Chrome) 120.0.6099.225 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kayla-glick** [comment]
Hi @t-mccawley 👋 This should be fixed now! https://github.com/wowsims/sod/pull/87
