### ISSUE TITLE
Blood Fury AP calculation is not accurate due to Strength-AP conversion ratio

### ISSUE THREAD

**Issue by neustart** [wowsims/sod#863]
**Describe the bug**
Blood Fury AP calculation is not accurate due to strength conversion ratio. [Hardcoded as AP=STR*2](https://github.com/wowsims/sod/blob/5b39df514e253d2ec9eae70f469b6650c11eeb8b/sim/core/racials.go#L81
), while true for most melee classes is not the case for Rogue and Hunter, their conversion rate is AP=STR.

**To Reproduce**
1. Go to SoD rogue sim
2. Sim as orc vs any other race
3. Check stat weights, Strength is overvalued due to incorrect calculation

**Expected behavior**
Blood Fury AP contribution from STR should be "STR" and not "2*STR" for Rogues.

**Additional context**
https://vanilla-wow-archive.fandom.com/wiki/Attributes#Strength

**Comment by sanguinerarogue** [comment]
Going to reopen this so I can test in game tomorrow and confirm.  I believe rogue calculation should be:
(Base AP + Agility from Gear + Str from Gear) * AP.  This is how it was implemented in the previous rogue dps sheets.

**Comment by sanguinerarogue** [comment]
![image](https://github.com/wowsims/sod/assets/118020821/2308a35c-1931-4eb6-a871-0888eb74fc27)

confirmed scales with agility for rogues

**Comment by sanguinerarogue** [comment]
Fixed in recent commit
