### ISSUE TITLE
Slice and Dice Not Refreshing with Blade Dance Active

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/sod#865]
**Describe the bug**
Appears that SND is not being refreshed when blade dance is also active.  Need to test logic of CTTC

https://wowsims.github.io/sod/rogue/#eJztVmtoHFUU3jMzu3v3bGYzuW7N5KaVdC1lGIzOzmbz8rGbVLGvNJEqrFFEpZFai8YEn79CjJKAtluRYuKDoKBFLMQQLcQ/ISg0RbDxUQL1R4P9JS0UxZK2lnrnzj4m28RYWrGCl2E499xzvvO8ZwbDREpLG+FRyErQWqnDAQnGJDgKcAKgQ9oJhwE2AvWx+UoMdOx+7KWuHk3W76gJmB8AhrXhU6p+MmwMfsZQ0b45r2JQO3Na1UebMKC9u1OfDXCZIS7zc8TY87nON3v45p2gsZcroDbWow8GjdmzVVzt0x5jYqEKifbbadV4XciOcNm9QSPLN0S7uB+MsYHVnPp9QTWyA9Xc4IUplb8vTjlmD55X9YGoA+QSivbtOdWuJrIGBjRCGl4M9oGeBXkK4DvwzYG/+TUFT0i+/9c/uugo/NsurLR+kXytqtMiHfA28JvQDZvXJKxkwkrEbbvWsjmdtOKWZfE3fxLxDiVDHvft+rJCl7ECg7v8KJMLaiyACkpWL65CwjhNfhqFWAiD6K+N35rsxSgGJkGmkIwR5Me1nKcDjTKKkVgZ4jhwSQ5jKM0+2sG24T1sA9bTOgx9ojhozjVZbTIi0/JpKKOS5seAw6zZwbh9hASGYhzhiCKRaJFE51D743a6hW3CNL2r1FaePltnSFjDbkI1Fs5bfItfUnUcUNgSWwG2fzvtZJmrB7Ojbp60vn1qjprdB3QGCLCvACeBHgKv9gvsOayIlZeg4C3UxLJxCAmWTIYyyEydZ6ls0sNjojbxXrSphVosUqLh5tWjMZxhokiicJoZIQEq94PPzXSd4PiptNnn4jb2eiPlNWEuLm1nbdhK0/kTZ+p5UibSVAoexwqznHMccC6EctzqZXlp+jDrxHba5jXngOrmjdx/nrK8YCHepX0PFH23rSJ6G9uCLTTlRRaGxsHZOkP5b3mbExZdso1uLXW20lzFnQ1N5kGvyNc89t2sFZtoQx538FyV11Vn6+iCBy2JoRFxeHxCF/WZitBe9ix2Ul5/xryqHodXQsJqs4ofRqYhLFrHT45n8jcyad+AQWFq/uncSOAa1GYWrqfrBKy8CNbhKFR6ORduQ1Lo8M8i3cBasIEmF3nGU3l5xijTMHJECZNTl3ILBMiBX4E+wLbjJnqvF6CZNS4R3joaWwJ6Odg6fl+LESnFciUuL6ld0Poa2DTgIaAT4HXoI2AfQg7I22b30XbhbIkTwiwZUZwkf/EUknHIUUJurijntClP9puKr9BuJjV4IQtVLmkdr/lErlaFyOrdJv+BV/M2Vos307VLVWYRREEhK7E3JHxFon3SyoHb113gmKJ3inkJy3yHkrjGrOZFL58sOc2PypIx+V6GPsQeFINiJejEX0LXL4J2htr7GYPQk8DmAY8B/X5Ro7n99x/ItxOyvEzIcbcPOefK+pArdB+GPoAFCUbA1y/xW0t2xKbkkPtH9Ei6wiWi6aqRYWfNpJpcztHU2ifEOpayszKZ61cp2dr1fNfumnpLT5nX2Q+1MZS+JjjrD14VjsYuXRs/+IqLd/fH6aYnnznz6sz9P6ZacifpDPwJ9/X2EQ==

**Comment by kayla-glick** [comment]
Is this related to Cut to the Chase?
![Image](https://github.com/user-attachments/assets/d72e5c52-fa65-421f-9b03-8cc736a60fe4)

**Comment by sanguinerarogue** [comment]
Fixed this in recent commit.
