### ISSUE TITLE
For P2 / Level 40, Auto Rotation Selects Rank 4 Lightning Bolt

### ISSUE THREAD

**Issue by t-mccawley** [wowsims/sod#88]
**Describe the bug**
When selecting "Auto" rotation for a sim configured to Phase 2 and a level 40 character, the proper max rank of lightning bolt is not selected. Even with a very short fight duration, Rank 4 Lightning Bolt is selected (rather than, for example, Rank 7, learned at level 38).

**To Reproduce**
Configure settings as follows:
![image](https://github.com/wowsims/sod/assets/29646748/56c3be44-da63-451c-b49d-f7c25a4c5a83)
simulate
evaluate Results to confirm that Rank 4 was used:
![image](https://github.com/wowsims/sod/assets/29646748/32758dd9-8259-4e46-83b3-6e6c3ee86e35)

**Expected behavior**
For such a short fight, almost certainly Rank 7 could be used without going OOM, but generally the max rank possible that maximizes DPS should be used and displayed.

**Sim Links and Screenshots**
https://wowsims.github.io/sod/elemental_shaman/
See above, gear configured as follows:
![image](https://github.com/wowsims/sod/assets/29646748/e05263d2-281a-48f9-970d-26e6be93f7eb)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 120.0.6099.225 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kayla-glick** [comment]
Hi @t-mccawley 👋 This is because the auto rotation really just defaults to whatever APL we have set as a default. We still need to add a Phase 2 APL. But I'll leave this open because I do want to be able to assign default APLs based on level so that for example a lvl 25 character isn't trying to use the lvl 40 APL by default

**Comment by t-mccawley** [comment]
@kayla-glick makes perfect sense, thank you.

Can I request / suggest that in the interim you expose a P2 APL, if you already have one, so that we can manually select it?

**Comment by kayla-glick** [comment]
@t-mccawley phase 2 APL and Gear presets for Ele should be going out shortly!

**Comment by kayla-glick** [comment]
This PR adds automatically-switching APLs based on player level when using auto rotations https://github.com/wowsims/sod/pull/130
