### ISSUE TITLE
Crash Report 1795411174

### ISSUE THREAD

**Issue by Lastwolf1882** [wowsims/sod#899]
Removed Flurry from talent spec and tried to run with t1 Earthfury tank set.

Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJztVE1IVFEUfue+cebN0TdO15/eXF3Y0M9lSHgzOqYSzCQRIhJOtXARUZFhIiQJUjuJIoMoaxMJgVRQaIrYqkVqFqYUkf3hRgpqUVIYQTpYUGfemxkjXJVSi87ivXO+e+453zn33ItCY0VMMhPKIcqqYS80QgtrZ9jJoMpnQBHcYDDAIApTAANwoBGqIQ5QybzAFdGXic665n3HGo54ncbmIlegFzDTOzajG7M58lqvDx3eW3M6urzjBF2uoLWOuG5MOuWJz4KMe4S+8chH8wYZo2RMe+SZgcTKHTKuuuTXBR9q3rszuhy0fIYJfpAjn1nGfTJeeWQ8bpDP8Lwuz54oIO3hgi47SVO9V3ZT/scLifwXv+jGBw8p/XO0yUn45Jwe8muqBKqcUeWsnh11d0BGN7ARgKegTIFjHFjlkANfM+W/rKjwKfjbFFZKZphSlV0O3UBXqA7q6YK1QE2hGTZLSoJh0zRLiukbDpWYthUMB+u0enW/0jTkMFTMQ7dwYYY2EpMuv4Y0uMVBs5VgFGRp58dAZvjJAdXi8kX4HMFqEi5rxdxkkLGYdCbRYCt3CFap8LXCjwbPR3ePg4Jr33p86B6EhDo9K0Ti3zNv8FIRwg183dJeqPszUyvkbKX6uEM6+HZRi1U8igUBn5bBsSlB7eZbkE7h7mJJb8wP5GpO7h61ot2m7UQPIZwKSPc+zaJQCPT4sxBDi5HSGs8XuT9TT7PIEnZTnp8CCTxT2L3op4Zaxa8O5P1CziZgeb2PUYCdIobb+NbfK2OJ3rxrk8iJk1UXvXBcCMP2C6VOKX1cvEJswo08YNF0cByF1DTYCUKYHdCJFatRbKA0PS4t49AOEGfQBcoFRqdtqP4R1W1P5Z7oKlvJjfq6LiVkIlJhI08iaw5a8jIS6lS1qeM612ob2hqai8pMIxL4xx5DeTq6LHHW9/1RHK/4vjw8SILWt+V6tOLQ4U8nJ3a9iGxJrkTr4QeMKNvj

RNG Seed: 2005060430

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 244 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xddf40, 0x113aab0})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Aura).Activate(0x0, 0x26aa5a0)
	/home/runner/work/sod/sod/sim/core/aura.go:554 +0x2
github.com/wowsims/sod/sim/shaman.glob..func22.2(0x2c171e0, 0x26aa5a0, 0x2547b80,...

**Comment by kayla-glick** [comment]
Should be fixed now 👍 just a heads up though that that setting does NOT cause you to dodge/parry/block. It causes the target to dodge/parry/block your attacks. There's currently no tank settings available for Shaman
