### ISSUE TITLE
Rogue Sod Sim Crusader bug

### ISSUE THREAD

**Issue by Anhak-Anhak** [wowsims/sod#902]
Crusader on a recent update went from tracking offhand and mainhand as seperate buffs to for some reason tracking as a single buff. Thus giving people the wrong impression on enchants etc

**Comment by Anhak-Anhak** [comment]
64%ish uptime with both 51%ish uptime main 31%ish offhand  its just not tracking separately in a recent update

**Comment by kayla-glick** [comment]
This should be fixed. Thanks for reporting it!
