### ISSUE TITLE
Cadaverous Armor missing stats in Enhancement Shaman Phase 4 Sim

### ISSUE THREAD

**Issue by TwochainzClassic** [wowsims/sod#906]
**Describe the bug**

Cadaverous Armor is missing the +60 Attack Power it should have.

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kayla-glick** [comment]
Pushing up a fix for this. There was an extra item added in SoD that seems to be intended as a replacement for the original but was never used
