### ISSUE TITLE
The Attitude Adjustor Stats Incorrect

### ISSUE THREAD

**Issue by MetalJacx** [wowsims/sod#907]
**Describe the bug**
The Attitude Adjustor is showing strength +13 and they removed the STR modifier.

**To Reproduce**
Nothing to reproduce

**Expected behavior**
Expecting this as the item in sims.
![image](https://github.com/user-attachments/assets/701fbc0b-3e85-4991-93e5-421dcc962ac0)

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Windows 10 Brave 

**Additional context**
None

**Comment by kayla-glick** [comment]
Hey @MetalJacx this is an issue with wowhead not having updated this item yet. Once they do I'll be able to update the stats in the sim too. The tooltip comes directly from wowhead though

**Comment by kayla-glick** [comment]
This should be fixed now
