### ISSUE TITLE
Please add Defence stat rating to Warlock Tank sim

### ISSUE THREAD

**Issue by adam-tj** [wowsims/sod#909]
Could you please add "Defence" to the column where the other stats are showing in the Warlock Tank sim. The column is shown in the screenshot uploaded below.

Thank you!

![image](https://github.com/user-attachments/assets/46bde306-87b8-4419-b238-0686d2bf75a0)

**Comment by kayla-glick** [comment]
This is now added! Sorry about that

**Comment by rosenrusinov** [comment]
There is no reason for having defence listed in the stats it just takes space without giving you any valuable information. Warlock tanks are crit capped by default when they enter metamorphosis form and whatever dodge/parry the defense stat gives is already listed in those stats.
