### ISSUE TITLE
Crash Report -94638786

### ISSUE THREAD

**Issue by Chillexn** [wowsims/sod#911]
Link:
https://wowsims.github.io/sod/warrior/#eJzj4uZgcmDyYExg3MHI5MQnwRjBuIHRLYExg/EEI6MQg9R7Ni62gJzEytQiAWYJGwVOrTmMXNwCPyfwSjzi1ph0ToKLReBBEy8Xu8ChPbwSCyyBjOO7eSUusgEVvQUyFrBrnP0tCeQ82scrMZ9dY2eHFJDzZxevxA02jTtzJbk4BE5P4NU4Mhek5t1usKmTgaZyC3wAcvrZNX41SwGtuLSbF0jeOg8iF81lBJK3z4MsXQNU1CwCZKyFMBiMRAXYNVgtmDMYC5gq2A8wMl5iZLjByGq1j4XrARPDKKApELrBONBOoBV4xcTgJMjBKMAoweTAGMA4g5ERlEW8zIwNjA1MDYwMjQ2MDCBAF8g3BdKmIMoQSBvqGqCDAKYIliSGLCYJxoITjD+YGGcxMqxiYpNiARrPqHSImRNiZ5yDIIQh4iA5ayYInLS3hIhcsFdMA4Nr9kaTmDlWruYV4vBJLUvNUTAxkNBSYNcaZIn9Q6MDVczhWkCROUd4BB2p4g4gMASTDv0Olpn5H1pPhly1hxntEMEIAPQZcRg=

RNG Seed: 1535529237

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 10 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xde660, 0x1142b30})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/warrior.(*Warrior).applyFuriousThunder(...)
	/home/runner/work/sod/sod/sim/warrior/runes.go:189
github.com/wowsims/sod/sim/warrior.(*Warrior).ApplyRunes(0x2c28000)
	/home/runner/work/sod/sod/sim/warrior/runes.go:43 +0x3f
github.com/wowsims/sod/sim/core.(*Character).applyAllEffects(0x2c28000, {0x2cf1b0, 0x27badf0}, 0x27c9440, 0x27ffd80, 0x27f2600)
	/home/runner/work/sod/sod/sim/core/character.go:315 +0x14
github.com/wowsims/sod/sim/core.(*Raid).applyCharacterEffects(0x250ba20, 0x27b9800)
	/home/runner/work/sod/sod/sim/core/raid.go:295 +0x3c
github.com...

**Comment by kayla-glick** [comment]
Pushed out a fix for this
