### ISSUE TITLE
Blazefury Medallion crits don't trigger Focused Attacks

### ISSUE THREAD

**Issue by Jgholmstrom** [wowsims/sod#925]
Sim reference: https://wowsims.github.io/sod/rogue/#eJztVmtoHFUUnjMzu3v3bGYyOa5lctvKdi1lWEidnc2mSRSzpha0WrNVfyyhqJVG6UuDi+IDIQZFxVcqWmzoj5SClYK0LkEhoISA0BaljVQJpEUF/ygpitAa8VHv3J3dTB7VH23RH54fy5lzz/m+87oziyZTC+pt8AAMqMUhFboNG95T4agKJTgGQAofJ4wWd219qu8xS7NvSkUzBwCZ9eeQ4Qx8wFG3BmcNjFnT+8Ee6RDK90KZjGLC+vmcYX9nOmdHbfHw+oxhnzWdt0REwnpVPHxtOqfFCbM+3w/O6Gyz0M6fM5xp6X1aYAiHl371zad+NJwXn18utD/2gjMkNM16bbcgnj7pEx85b9gzplBmZ6WiWwffBi/yZOwLUDo/0fEbVflfrqrQFPzbKVwt+UFVuslW22EEoABFeAfERemHjStdN5/zclk3m89n3dYW18vl3LznCsm72aJeYg8qO35J2Bo2YWxHBDX2m5GOoo6qW8ZrkXGhszMjkI5jDCMt2bX5MiYxOgYaQT7NUBy3CJsNlOSEZroBsQLCU8A4eqdCRX4XbuDrsY1aMX5Y99EmLzTjigxnGjVOQAOpVgSjvjG1jQt+hDzG0wLhhK6y5JyK/qH1+410B78dC3TzQq6afqHVUTHFr0Mjnagx+pfZqABKLvkowfbeQ728dPlgXrLaJ2tgjxFok3uATgL/DHAc6GMIxz7Ln8GmdOMCDHRpLZoVSEhThL1ScqJBl8yxeVYup5MtYyt5SGnrElENYxCXVo3tK3E5KDk8K2OyKGmDoFS73SotEVI3KlXk9nK4WjEXHguQqYdvwm4q1M7eEGmHGiebtRA+i02ZRmHx4YUTalm3zGvetIX3Yg9tChP6oHZmmagAx+qw9ZqXzj46l73nzqHfyruxg9bVkP2XtCSqQO3RD4YQnFi9YXko3u6+hY2b9Dgv4xbqxRWch0NDKf8TEq7MLBeH1gQYciIxdqaU2ubogad3DcYk2bePBPdNxNBm3oMbaL0E1uYB/z2aDNBJfTpoyLq8hBQfLlnJdnp4Xuqi24t76jfOPKEn2MzFQCDcOb+kZZmkYIkfhgC8Nu3A5dBzUK9kN9+JW+n+MOXdvLhEx1ZTeolkFiZyCeY6ncddXEOra32oLUZu8fJ49ZhPgU8AfgQ0CuE03wV+EAKg8Epvph7s5O2LUvNp2bDuz/LDncgqEGjSb2rOz78SYqZv6kp9sTPkiI2pr9OCHQ3T54KVqFfWVpZ1iD8pdANvwetp1VITngdRC+g/BrMqDIMyqIpWMS89rsWr35P7Ck1VJVloHt7ny/GujqrlVNeqh6R81eUNaWxq0CB2Z98TfbtSba7dlfmP/Y1xXi5cEZw1718WjsUvXpk8hGTlb/+hQsf2R3964fi9X3bdEpwUSvAXkNFr0g==

Blazefury Medallion adds 2 fire damage to melee attacks, which is the damage spell Fire Strike in the result. This can crit, and when it crits in-game it adds energy if you have Focused Attacks and it adds combo points if you have Honor Among Thieves. In the sim, Honor Among Thieves works correctly but Focused Attacks does not. You may have implemented Focused Attacks based on the wording in the tooltip which claims it triggers off of melee and ranged crits, but it apparently also triggers off of spells (or at least Fire Strike).

To reproduce: run the sim, check the results and you should get about 152 procs of Focused Attacks. Change the neck to another neck with similar agility (e.g. Evil Eye Pendant) and run another sim, which should also get about 152 procs. You can make a similar comparison by changing the head rune to Honor Among Thieves and running the sims, which should give you about 77 procs with Blazefury Medallion and 65 procs with Evil Eye Pendant.

In-game screenshot of the interaction (note that it says 0 energy because I was already at full):
![image](https://github.com/user-attachments/assets/f739a3a3-4b23-4936-b50e-b9142b2078fe)

**Comment by kayla-glick** [comment]
Hey @Jgholmstrom 👋 Blazefury Amulet is a really weird item and we're still working to try to understand it and get it coded right in the sim. We know about the FA interaction so that's on our checklist of things to make sure it does correctly!

**Comment by kayla-glick** [comment]
I created an issue to track the information we have about this item https://github.com/wowsims/sod/issues/935 and to make sure we get it implemented correctly
