### ISSUE TITLE
Crash Report 1569997388

### ISSUE THREAD

**Issue by saimpot** [wowsims/sod#929]
Link:
https://wowsims.github.io/sod/hunter/#eJztVE9IFGEU3/ft7Dj71tHxa83ZT5NtqZiWlNlZZ9H+sJt0kOgg1cFjCYZGoLQQdZMyyoQQQVPpYAgVgRBBEEVlQZCXqCCxU12CiBRLLCOs3s7sLB66pdShd5jvN++97/f+fN/3cIPCNBZlBjOhHjKsCQ5BF+tmO/sZ3GTQGNHhuoMyMAPQzNphDNhTgCbgPnE/hHLzscOn2o5rAX1nlMWvACra91nVuD0RQUkbHwYs0pZnVX2sAVG73K6/kI0XnwSGtL45UhYZF8gvpJ0ZAf0rGBODOcuzj6r+psR4/UMnroVvqjH2M4fOzanGNcf7kevwxFEvLqlGX09lHl0kJGnLkyp9hxZVCn7pnqpPh9FHcHwQ9OGAVaf4NTDAKReaqKAu+WT4PAT6gVFpN0G6A9IkwEtgGpUceA8wD9L2BxK+Zb7/sqbCZ+Bvp7BW8oH5Gkvr6fHQpWuGFnpl7bC3MlFj2nV2wjRNuyaZNE3LspKmlaSP3Sy1+Ft9R69Kuh/DGBRFGFA+dxpyjAD6a+wsrs9rFzoMJRZEgjVmrZXFCkShoKxcHwdydw3J2mSWC6GjGgth0PK2FfbzKiGwLF6qSJy1+oQTw7Y3C1q0no7fWVN565dWTmnkoPKugm8TcYzyasdZXkFlbsbgLZBRUh5ORPbnV75HNGJK1GFFvFzx8+AN1+GnLmhFlshiJF5BNKEbUKjHNaWyA+AQI9hcFSFBVSp3O6N+qoSKF3meAv68XMm3iE1OINkLREqXrZ7YKIAT0+LlYp2XK00xZzvNIk4xnG697DSkAm/OUCxWtJtHRTWGOUctXpLvlsNLzfKK3iuacBff4Z5EoSdYEitGvAXeMaOI60rAS5XiCOcgE7V1drZwF7zOa0MHup5Cb/7xGJklBqPgewzVvEoJanLMt9W1zKcTHqDRVxR77A86v91HMmWuIZyJjI7kZCrd4GqepzcecWQ6bQ34lZnTKlf2tZ1oOxZNmXo6Ksf/sbFo9GZWhWfLxB/xaNHU7lXJg8Q9tK5rmYaOzvmzUwdfpT3qTAv8Au3M0cE=

RNG Seed: 3376593443

no base result for equipped gear found in bulk sim

**Comment by kayla-glick** [comment]
Related to the batch sim. Closing in favor of https://github.com/wowsims/sod/issues/944
