### ISSUE TITLE
DPS as Crazy number 1.SomethingSomething e+204

### ISSUE THREAD

**Issue by shaugen** [wowsims/sod#930]
**Describe the bug**

**To Reproduce**
After swapping some gear  from T0.5 to a few pieces of T1 I suddenly got some crazy numbers. 1.something something e+204

**Expected behavior**
Expected to see slight variation in dps output, Not this crazy number.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

https://wowsims.github.io/sod/warrior/#eJztVE1IVFEUfue++bnvTM+eN6k3V80/yufExJunYxrBTG4iaeEiSiYIE4wUI1GI2pplIYEQ9GMbc1MIkkmpKIk7NbA/qAw3JS3SJGxhBAZ23xtNMQkhpRadxbnn3HO+7/zMm4sJlGgkSsqgmUAngSKvDqUwDLCXaMAkPrQJPSXVJ85X1GpE35euBG4AUq13UjU+NHJ0aZc6QOj+SRW92lTMePCZo0/rnVb1Vq8xft0vnIeTqj7mMSYa7UjHtOPMjeqC5ZFgGf9o8/UJ69pTXST0iOzLXuO9gFJtZlY1OhtSBHVDufH9QjLK2tXTotz4M1Xoka+27u239e1+1dKoSyMGFJBz3pcgzYgRBlz4jkj/ZUOFjcHfbmGjZIpIRQk6aQVSAjcByuAUFKfnmrlm2DRDuaYVNHOD4bAlnJAZFr4pjlC5VDXp1mXcgpR70EXFp5zpRTfKwVAd206Bc0wMbKYuRool7gSscB0Xh1ZfyZK5H7VAApUZqZVsOJKQZQfpfBLLF2ALc1i2k+JZSsk3UekCu1hTUwrSNrABPSqPHyxvdVRBeBHVJf61v6CCfBemsdTfojhFD+2+A4ab+fk29LWBfTHbB4aL/7RYDs/GFMaX96hm+lCxxPS0O2Z4+aLBsngGJjG2suieMFfQS+/H0sGgzMcVBzEaE3XjG43nyxMg2e0jhJzV3/vCWZqIJ6/ceH6ozkn4NAALCSsJ8pwKj2OGh6WKBP8qFew9NassQYTRmXbwDRgyyxO+iTtYFirtLruI/QxuDSSJ+krVz4kdDnNp8JhAHcGD7MAi6smcf5Wf2b6B5V04zG6m9DmrHZrzx++t5fs6JriPro3bvSZuRErftoIgd9cMwzcCIwuvLI2+WLAKo2MEWkBqJx7u0kCHzEFZiYeORxPjxu6ov+WWLSORwvjN80jGSUdeR6xmmY7Vq4weqjhbUZ2eb+qRwD/2mBtXouvCs7Pjj3g0Pr8+fQgJObrmbrSw8szMxZHDryL7FyLRUvgB0EDSGA==

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 126.0.6478.183

**Additional context**

**Comment by shaugen** [comment]
It seems to be the 6-set bonus from the Might set which adds 4% damage when in Gladiator stance that messes with the calculations. When I swap an item to disable this set bonus, the error goes away.

**Comment by kayla-glick** [comment]
Oops, looks like it accidentally adds the 4% every iteration 😅 being fixed in https://github.com/wowsims/sod/pull/934
