### ISSUE TITLE
Please add Protection Warrior Gladiator stance rotation.

### ISSUE THREAD

**Issue by shaugen** [wowsims/sod#931]
**Is your feature request related to a problem? Please describe.**
This is currently not available, and I have to fiddle around with my own rotation like a newb in this tool.

**Describe the solution you'd like**
Automatic rotation for Deep prot Gladiator stance

**Describe alternatives you've considered**
I have been trying to mess around with rotations on my own, but it is kinda fiddly (not familiar enough with the tool)

**Additional context**

**Comment by kayla-glick** [comment]
Hey! This is on my TODO list of things to do and I hope to get to it very soon! It's been tough with the pre-raid prep but things should calm down a bit. Thanks for using the sim!

**Comment by kayla-glick** [comment]
Added one last night 🙏 It probably has room to be optimized more by the community so let me know if you find improvements!

**Comment by shaugen** [comment]
I see you added it now, but it doesn't take Sudden death into account? Not a single Execute? How come?

**Comment by shaugen** [comment]
Here's what I have come up with (with my current gear).

https://wowsims.github.io/sod/warrior/#eJztU01oE0EU3jebZGdf2LCOBTfTiGkEO41ENhtTjQhZexQPPXgoOYgWIioVSwXRq1ZbKUJFEO2p7UUohMYeqhgUj82h1gpKoBcVDyKxBKRSUaizSargwYstevA7zLzv/XzvDczDECUmcclxGCVQJNClW9ADp2AO4AAxgSn8E8VAd9+JS/kBk1gHo3p8ApCaj6uGeDfE0WdeKwBq5lTVsMYzGDSHVw1rMSDuL3NJPpakVxNLt8OSTMuUSkC8HfIihQb5Om9JsaIUW3rvyS6XDHHrmSUTarJ0WBNvZCk1ayuGKA5GZJ/BXvHtSiuq5o2zsvfSgiF95c+GVQ1J+rBkyHPhi+GEqE/AfnJRewFKTT7liQ9fE+U/NhWsAn97hM3CB6J0oUXGgXTDHYDD0ZSdstO2nUzZTsJOJdJpR5KknZbclleyVzlzk1gqbkXKA+ij8h/HNPSjmkieZ608jGY8RFVGBhQvjCTpcBmkay1sL3ewg7XXEwI/Ezpt1GfAk5qRq0UnwUt/YPDGxRJ8N+5g239bxeUm09kJEH4W5tswOAmeY+URCB//YbEO3o4RxtfrRkYiaMSCqDtyfDqbExpfN9hO3oYtjP3adF+a66jR6VwUBGVBrtcr5nPC3z8HqwTKzU2k7mLTyrgVAmOgTJEA95lgQeypqjdCx9wtDWOPGx6766GczTQ8z7NtJ+t4lXVGVVq5bDB6JH8h3xfttK1s/B9beHHd3RCdXYU/0jH52sbMIZGsn/333Mzpc7Wr5aMvs4eaEbcHvgOzWZfa
