### ISSUE TITLE
Block Value stat visible anywhere?

### ISSUE THREAD

**Issue by shaugen** [wowsims/sod#936]
**Is your feature request related to a problem? Please describe.**

I can't see Block Value or Defense anywyere in the gear screen.

**Describe the solution you'd like**

Please add Block Value and Defense to the stats list in the lower left corner.
It will help a lot.

**Describe alternatives you've considered**

**Additional context**

**Comment by kayla-glick** [comment]
Hey @shaugen 👋 What class/spec sim are you requesting this for?

**Comment by shaugen** [comment]
Warrior Protection Gladiator

**Comment by shaugen** [comment]
But all protection specs would like to see defense, I guess. Since 1 defense = 4 attack power for us (any defense over 300)

**Comment by kayla-glick** [comment]
I separated out the warrior sim into a DPS sim and a Tank sim. The tank sim has block, dodge, parry etc 😄 all of the tank stats
