### ISSUE TITLE
Port item sets by ID from Cata then update crafted item set bonuses

### ISSUE THREAD

**Issue by Accomp** [wowsims/sod#940]
**Describe the bug**
When equipping the 2-piece of Devilcore, the +10 fire resistance bonus is not being added to the stats listing in bottom left sheet.

**To Reproduce**
1. Add both Devilcore pieces.
2. View fire resistance value in stat module.
3. Remove one devilcore piece to break set.
4. Observe the +10 set bonus was not being applied.

**Expected behavior**
+10 fire resist stat bonus to be presented in state panel properly.

**Sim Links and Screenshots**
[Sim Link (Rogue)](https://wowsims.github.io/sod/rogue/#eJzj4nFgSmDMYGxgCpjAxOgkJcG4golxAxOjA+MFRsYHjIwBTBmMJxgZFzAxCjFIdbFzsQXkJFamFgkwStgosGmtYOTiFuh7ySvxkFujYaMUF4vA2V+8XOwCPUChbmsgY/4PXokea6CifqDIAnaNu1skgJwuIOcun8YUoA5ugYXfeSXu82lcAcpwCHS85NXY8kMSKNwLMfU2WMO7z7wS/ewaHT8lgWqWfufVaG+RBrL2AVkTgCwWgQ8/eIHkJ7DlU3/zSrzhAzK2fgczWATmfOc1UuVgFmDUYLQA+swD6KcCpgr2BkaWCYzMBxgZLzGycDAKMN5gZLXax8L1gIlhFNAUCN1gHGgn0Aq8YmJwEuFglGCyYFzBCExrAYwzGBkTGAsYvWQNDEyNjYwNDQxNTQ0NTHQNjIyNDUyNDIDA1MAwgCWCI4khi0mCseAE4w8mxpPQRMjhcBHKsnS4wcQ4i5GhiYlFiIkjRekAMydEIs5BEMLQc5CcNRMETtpbQkQu2CumgcE1e6MJzBw3mniFOHxSy1JzFMwMJOy1BllK1+h0oIo5amspMkdA6j913AEEhmCyYLmDZWb+h9aTIVftHaEyDhGMAACHfFQ=)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version 126

**Comment by kayla-glick** [comment]
For whatever dev takes a look at this, because a lot of the updated item sets have the same name we need to port setting up sets by set ID from the Cata site in order to properly support them. We then need to do a full pass at all of the crafted sets to make sure both versions are included

**Comment by kayla-glick** [comment]
Pushed up an update that adds item set IDs and updates the phase 4 crafted set bonuses
