### ISSUE TITLE
The timing of energy ticks should not change when Adrenaline Rush is used in SoD

### ISSUE THREAD

**Issue by thomgoertz** [wowsims/sod#949]
**Description:**
The SoD rogue tank sim assumes that Adrenaline Rush changes the timings and restore values of energy ticks:

- When Adrenaline Rush is activated, the sim instantly activates an energy tick that regenerates energy proportional to the amount of time since the last energy tick. (E.g.: upon activating AR 1.5 seconds after the previous energy tick, an energy tick instantly takes place that restores 15 energy = 1.5/2 * 20.)
- All subsequent energy ticks in the sim now take place in 2-second intervals after this new energy tick and restore 40 energy.
- Once Adrenaline Rush expires, the sim again instantly activates an energy tick that regenerates energy proportional to the amount of time since the last energy tick. (E.g.: when AR expires 0.5 seconds after the previous energy tick, an energy tick instantly takes place that restores 10 energy = 0.5/2 * 40.)
- Again, all subsequent energy ticks now take place in 2-second intervals after this new energy tick and restore 20 energy.

This is TBC behaviour. It's not how Adrenaline Rush and similar effects (like Evocation) function in vanilla/classic/SoD.

**Steps to reproduce the behaviour:**
1. In the tank rogue web sim for SoD, select a build/rotation that uses Adrenaline Rush. There's an unfinished, but sufficiently functional example build in the link below.
2. Go to the results tab and run a single iteration.
3. In the timeline tab, check the energy tick timings and restore values. Verify the faulty behaviour described above.

**Expected Behaviour:**
Energy ticks should never change their timing, and any energy tick that happens during Adrenaline Rush should restore exactly double the energy (40.4).

**Sim Link:**
```
https://wowsims.github.io/sod/tank_rogue/#eJztVE9IFGEUn/ftuPP5tlmmL6txLFi3qHFhdWZ1pZVgRyOS6LCHDnsKi4z+CElC2E3ESKNyiQ5lRZ7KIMvEjfAg0kkPkUbFRkEePGSXpENKEPVmdtdDHVPq0GOY773f+733vff4vg91zjQWYiZzWAsMAWQYjNAHrCmsw5BnODADkAN4ythx6GRdwKYAmmGQQQPTQEjGZUR/qu3wudYzGtd3h/yRB4ABbWRB1ecDZu9jA2Xt+TcVFe0hQYMJ8t1ZVvVZv3n9u07GfRdVzCtZ17hIxk3FvEZRAa2PjA9B89WYjlzrXVDNseVygh/lM1/yAobJ6FfMTNblTCyp5oWeCtJmPqvmSM8W2voLbS1r7164BUwtqXpPGSnZvCJrt5bUWJSDBibsok6bqcV2f6fSBXovYAZ8NJJJgJcgzQF8BFgE1jAh4xyT/suaisjB3y5hreQTk5qC7mFLQRpagA4c7A9ZVtyK1doxO0pabTwes2iNWzYtFmHxlJyGI9LJeab7cANyw48yp9sQVrAEfdFYxwpIt6IA2h24CRWDVH67KlyKhEatartDB7HHaMR6UYdaJMhlwRokNxSZbWEwvA5xFIjLv9aZzGP4ha8bJDcRQtwousQ+Yy/WiChujmwkCo6vBBWYKCIaZfddlSXDq8iqjsdEoaInpwpKtk1UGTtxa6SCuNo4qIJpJajw9+nQUVPOp7KL7QqTg7EdjYhOZHUc0CPL/O6C8SuzxojiNlGJajiApaNQGM1v/djFoQk08gOk16Z9CroAlhlMF+45d2YLWsLJMRiAslLPcvqd8oEbrrxNhvzPGM2Sp8KTvrxXOuSszyvVRdp0MpFHZpKVxzx5k4xlfDzXrQp+oPVsa1uo3tKTkX/sgTH7nFXJs2P4j/Joxo/VqYPE9v7t95zEidOL56cPvk42FjxOGn4CRN+5rw==
```

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: (don't know... most recent browser version on 30jul2024 at 11:00 UTC+2)

**Comment by kayla-glick** [comment]
Fixed by #964
