### ISSUE TITLE
Multidotting multiple targets does not seem to work (warlock sim)

### ISSUE THREAD

**Issue by hjelp200121** [wowsims/sod#955]
As i understand, the multidot feature should try to apply a dot to up to x (specified in the rotation) targets. E.g. if i have a fight with 3 targets and i set curse of agony to multidot all 3 targets, it should apply curse of agony to those three and then go further down the rotation chain.
What seems to happen is that in a fight with any amount of multidot targets more than one, the sim will use the entire runtime casting the multidot spell.

1. Go to https://wowsims.github.io/sod/warlock/#eJztVV1IVEEUvmfu3d3ZsavjaLFOUZum3jbWZq9d0Qh28yEievChB0EIEowKK2kh6i0WgwwqJYh+6IdeqgfDJOixfLBWqLSyMPBB6KUiQqjUfKlz764palBkPw+dh7lnzvnON2fmnJnLllDCiYJq2AUtkCZpOEL2tROoLQrBdQJdBBIwANAFm64QmAD0gtDk0CLmr2vecbjpAKehDWEauQQsh396Y4ZGC6x7JyQzeM+4yQJ8DE0XaxjlrWOmdWcghKiPaHqVaw0+cSefcTKca/ViCOUTb0yrEzGUv3xnWg9TEgEfMpwdZ4twMvzODJ0KWAMpF3133LQ6Wpei1j9pWidRM/hlXNTg7/vdpe+PmaF0AdOYzgd32auozoObSR3Uk0OFx8DXDuQK6NcBnoI2BIFR8KWBrH9ssBGi/ZffKuI1/O0U/pS8JVptXjVgmyUAW8+7Y1vC6xylbKdSxWxbxZRyolFHOcpWTgwHpWJ1ej00anse+UI6K2BU+plBR09CcYD5mB51kmwxC0qc0BMNVrCYMvRH7QpHMOlh+WS7+U3HGyEqZYxZoozlR/KoX5AtmvSYYsjkmgxBGrMmR5VK/PDW3T8RZDuZoLFGUU1BrmOrRTkTxZzldkOOINyHmfY2WMYcKpX0duH6RFguZyLCXV70e3tSFU7S1eid02D5RaksmY2oREQKFiHHBeSQ+nHQRNVUAgjVhd5tZFerVspLwDc3gRsNSG/JMsYjudkEkZyRqmStQHcPurmeCVF7k1NHS/GpEuWydJ6ofPTik8ZhOuj79Ldd+hnI71PiuzcTuFZGWbAb3FQepKQdznbKzVtLWaHHfHYWcwlWZ8WMkHlBaxBUPk8CBViIHiyEMRO8XC7zDlWf7oYYttC3Q82R043akoZDZ6Ate/drEhMERgicB+0qYYLiXwjCAQuKn/mDGcT2RH5GKUwUnT/nSl+8JmMZiK/c6cmLuN2u06GUKejWpoNNzeEqFYpH/rEn3GpLLAhPWecv8XD5ZWHyQIl5Y8u1RM3u/aNH+7Y9j2/MehL18L8kPyp/rCRfAWQP6xY=
Most of it is taken from the warlock discord with an additional target added by me.
2. Click on simulate 
3. View the cast results

Expected behavior:
Cast agony twice instead of once otherwise continue as normal

**Comment by InDebt** [comment]
The multidot ist working as intended. But I assume there's an error in the curse logic. Agony is removed from the first target when it's applied to the second target. Therefore, it will try to recast it again on the first target and cycles.
