### ISSUE TITLE
Feral Sapper Charge

### ISSUE THREAD

**Issue by mrt0mat0** [wowsims/sod#960]
**Is your feature request related to a problem? Please describe.**
It seems that the ferals don't have an option to drop sappers. you can macro it in to a power shift and @player so it happens instantly

**Describe the solution you'd like**
for engineering, you can select sappers when simming feral

**Describe alternatives you've considered**
add a feature for selecting what you add to powershift to better calculate?

**Additional context**
the argument against sappers for feral is it requires form. but you're also powershifting which takes you out of form. sapper has no gcd so it can be bound into your powershifting macro.

**Comment by kayla-glick** [comment]
This should be doable by adding something similar to this to the APL:
![image](https://github.com/user-attachments/assets/7e297bb0-d60a-41c6-b7a2-47ae040c9e3f)
