### ISSUE TITLE
Crash Report 885899254

### ISSUE THREAD

**Issue by lockdoomsayer** [wowsims/sod#961]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJzVVE1IVFEUfufOOPPmzrzp+RC5c7Uap4zbwMT8NOJoMC9XEi1mqsWsokSjREgSpFZZKREIiRSUm1wEhVmYUWC1mIJ+bFFhZrYQilpYpEmgDrqo895MY5tqkWSdxX3fOec73/vu491LmUy8RJAgVIJOamEPNJM2Ut9FoGYNg8sEBgjoMA6QICkYgPr9UAu9BDJAqogKmsSfUWpLNO090nBItbMtXru/D6hTHetW2FunuHjFQy3qzaPUrj66q7DeGLaunwXWWS3av3BMJqYV9s4t5uYYJkNTCptwi84Bo/MKOxfsYnHBQ2U1PaWIwXmDMzptCr8wkzFMTttFJsOQMzOriGPtJYhunQPRhciqTs8quC6mFTTQ3wHsk5va1Nt17EY1lkfmlPBa2aISAZVEh1qSIocdbcB7gaQBRkAaB2vVUyt9Q6T/Oc7c01fawu9Cm4SVtvC34iORalx41CABKeOwwbbSYDQYiYSiwWAwEkCMWThopFgLJSwpa53U+NrCLLSIyo02apXxUPlkiigQirZg1cHttEBOJ4Xdh4BaArGl6pOksOaqFS20OFc9sVMQn4MiDGze9IPGw6Sw5diRFs3KSZWkreYltNC/SrZqpE7iZrMiWs4NI5kFj+bilKMZefQkCNDW8TJa7C+SbZrjPhiUoXnGcYJC1HzBZKugWinn1O1zURo2Bvvfg7DxPNI2ysDLaYnfgyK0cYnh6CGGYB8K5p6ak2dtX8Ot55MPuGONoQhuatD0MPGZm52pHdhZjx3vTz1+Vy5H1q93Yoq5kCabQ3dwiOYwXlka54wqPid1hA3yg6QoyH9gTcEpR/5zND+GNoAMgR6Qugnhki9tcWT/ld16YRYU6Z6e80YMx2PZyvN42T4zxuLhLos8flzR5O0NrQ1N3oogi/v/sStLnNKXRWfD1T/SUfnX5fGBETLX5kt67MDBmY7hXS/jW3MdPQXfADuoxY0=

RNG Seed: 1701971046

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xe6060, 0x12300d0})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/shaman.(*Shaman).applyMaelstromWeapon.func2(0x2443040, 0x2c5fc20, 0x0, 0x1)
	/home/runner/work/sod/sod/sim/shaman/runes.go:321 +0x4
github.com/wowsims/sod/sim/core.(*Aura).SetStacks(0x2443040, 0x2c5fc20...

**Comment by kayla-glick** [comment]
Pushed up a fix for this
