### ISSUE TITLE
Biznik Scope Adding Hit to Melee Attacks

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/sod#962]
https://wowsims.github.io/sod/rogue/#eJztVltoHGUU3jMzuzt7NrOZ/F3L5G8q2zWUYSF1dnY3zUXMmlqI1TZb9WEJBa0kai9qcFG8IMSgWLWa1Bs0L0aKphREXaJCQFkCQlu8tKISaAstvlgpRRSb1Ar1zL+zm8kmVbF56IPnYTj/uXzn+s8MMlWKSaaUlXrgXhiScqMSdDcZcFCCDyXIwjGA0wA56UE4DNAD4xIwH59jGMjt3v7kwKO637gpFkh8ABjWXz2rGWfC5tBHHBX9qz80DOp7STTeTrq35zRjb6dZer2RDiMk/TFinpo06PASHU5FzDfIK6y/M6sZB4Lmd6RR9T1nNXNyznF4pYx8Qjic/00zRoLmnouNZPPurGa+8Nwq4j4nbpQ4RT//u0bPX0UCb17SjHMRYj6edZmJi5pxYoXdrMo6mNBGJfZQcU8Eh0AZBXkc5BLAtyDpMAP+jq8VPC35/qd/QZ2l/+rJfoJlzOOapp8lX7d2EGjpcpCn+zYIm1ZbViZlp5JWMpNJWukWy06lrIxtEWWsZE7Jq/f5ds6GDRkbMLjTj7J6SYsHUEHJKuB1qHLi1ZPjEA9hEP0tyXWZAkYxMAUyg0xcRVK3kMwAFuUMI/E6xCKQJcGYSoeP5fgW3Mg3YCtLY+iQ4qAdv9CITQmuyqx+GuqYpPsx4Ahj/ZziI2QwFCeEo4qkRudZdJT6n53sdn4bZtnNtbEq/IW0KWGMX49aPFyJ6Nx+rQgoYomjAHvrLtbH81cPZkfLfdKH9mkud3wfsG+AfwlYAvYZeH2f4U9jQ7y+BgMttg4jRQgLkV99OW8G3C5FphZIuZhOsoBpZiOL61fwqpuCkJDK6v48F4MSw9MTETXA5GHwlbudFhI/kzb5yshtBW+1NBcedJFZL9+M3Sxb0Y1Q2p7GiWbVwiexIVFPEgeejFBOWgVesWbbeB/2ss3egA6okVhJFeBUFbZa89LZB+azt6159Ft5N7az9RVk55UuAhWhcnScwQNHqzcmlPQtcCRqKcIe4wXcxvqwiXOvqyflf0LC1YlVpNSnQRMTCaon87F+U3Et7RUYFMHOPOzeN/JhW3kvbmQbBLC8APjv0YSDwqSn3IaszwhI+tKJSnawBxakTt1e3FOncZGjSlg9d9kl8HbOKWllIkpRQofABa9M2zWZeBaqlTzEd+F2do835J08t0THmll8iWRqE7lC5Go4m1u4ljVX+lBZjNTi5bGrPl8Anwb8FNgkeNN8D/gBcIG8K72V9WIHb1uUmhNWHVOcWX6yC9UiuJywm5m3c64EzfQ1xVdd7AQzaWOq61Szo97wKXclqpW1FkQd9FfDbuQteANbs9SEF0BUHAYPw5wEY+AblqhVan+8JIfKn5It2YYyE802ju136EhXe1lyrGvN/YJ+6LJHZXVmWGPqHQOPD+yOtVpGV+Ia+6MxX8wuC87a968KR+eXlycPoqR4Dk5k23c88svzR+7+vusWV5PNw1/Q5HsC

Remove and add scope and witness melee changing.  This should only be ranged hit and looking through code it appears to be coded as such for the ranged so not sure where the bug is being implemented.

![image](https://github.com/user-attachments/assets/012937f1-8b1a-47c5-8335-387c251a846e)

**Comment by kayla-glick** [comment]
Looks like the enchant override was adding +3 melee hit. I removed that
