### ISSUE TITLE
Aimed shot shares cooldown with Explosive shot

### ISSUE THREAD

**Issue by Hrstal** [wowsims/sod#970]
**Describe the bug**
Aimed Shot shares the same cooldown with Explosive Shot.

**To Reproduce**
1. Create new empty rotation in 'Rotation tab'
2. Set new action 'Cast Exsplosive Shot'
3. Set new action 'Cast Aimed Shot (Rank 6)'
4. Simulate
5. See the 'Results tab'

**Expected behavior**
Aimed shot should be cast after Explosive Shot.

**Sim Links and Screenshots**
[exported sim link](https://wowsims.github.io/sod/hunter/#eJztU89rE0EU3m822YwTV6aLh+22SMxBxkLLJmmkEWHHHqSIhxw85CRViESpNHgQvYkoWH9ALoL2FBBJLoFcBI+hIDQHpREtOWnUIo2gRjykWqROsvEvsP44+F3m+9578+bNm3lsDyWcRIggLqYgySzyKAOXSbpAUCWYjtoo95lEE2gBaZJBFUdyKIIsA0UCS3NehpiRnjt5KXueh+xDETJWAgvzzQ+mvRYWDyvDLMCffDNZiH9XpmJK+Za6pt0wROOzo8S7trKGxA0VGOZvlOhCVO70PC0lXu0SK1s2o/x12xRFxcJ8rd3PXOpveOvHPO7HPP9kiltXRxR70DXFTcUCfLNmMp3fPqfO//rFtFd3M03Rj6qCu8F4guqciN7lMUNyuBi6jmABpAi9CjwCNoAa8AwkohoQXAc6wMGnAdYi2n/8Vljr+Nsl/Cm8J9r00FRv8iTSyGAWOTWIR0di425yMhlzXTc5nkhMqjWedOMJN+Em03omcEo7O2rrFnOoY7AAVVNi7XSUYgYt34cw8stYGPRQyA2C+uDPUtkYsJRsEixCW8Ko5VDKjai23/d0vNhPMkOiNX2Hr07IIZ9MyOHFez3UvZRvWfH2nu5j1YsXdNq8Ylr0WPZCdi5ywLW9sX9sYMSC3JY8+yq/lIc7W9tTh4L/YPmSTJ2Z71yrH3/hHR54ZAY/AO4AkGs=)

**Comment by kayla-glick** [comment]
Pushed up a fix for this. Thanks for reporting it! Seems like it used to share a CD but no longer does and was never updated in the sim
