### ISSUE TITLE
Miss Metrics for AoE Skills Issues

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/sod#981]
When working in a multitarget environment the miss metrics for AoE skills appears incorrectly outside of the "All Targets" and "Target 1" choices.

![image](https://github.com/user-attachments/assets/68fd01c1-15bf-4195-8b5b-bff161bb3386)
![image](https://github.com/user-attachments/assets/d4e3c92c-b0af-4ffb-a800-017884d32c88)
![image](https://github.com/user-attachments/assets/dfdb47f4-6d84-4ab2-8a07-0a54534f51fd)
![image](https://github.com/user-attachments/assets/55a5b82d-c54f-4df0-bf78-a820f7eacc8d)

The overall damage and DPS calculations seem correct.

**Comment by 1337LutZ** [comment]
@sanguinerarogue Is this still the case with the updated Metrics?

**Comment by sanguinerarogue** [comment]
Yes, thank you for the ping this looks corrected now.  Closing.
