### ISSUE TITLE
Swipe (Cat) not giving Combo Points

### ISSUE THREAD

**Issue by Lexolaz** [wowsims/sod#982]
**Describe the bug**
When you use the APL to use Swipe as cat it doesn't reward combo points, which doesn't reflect how it works in game.

**To Reproduce**
1. Go to Rotation
2. Choose APL
3. Remove everything
4. Add 2 conditions 1 for Savage Roar if Savage Roar not active, and 2nd condition as if none cast Swipe
5. See error in results, both that it doesn't use Savage Roar and it doesn't show combo points on the timeline

**Expected behavior**
Swipe in Cat Form should add combo points like it does in the game

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/sod/feral_druid/#eJzj4uNgMmC0YHRgmsHEOIGJ0YlbgjGAKYJxA6NbBqMQg9Rpdi62gJzEytQiARYJGwVGrSWMXNwCL17zSlwx1/i5S5KLReDsL14udoGXr3glFlgC5dq+8UpcZNO49lIKyHkNVPiYT2PlZwkg5wmQc5dP4/9ySZARQPXz2TV2A2U4BJ684tX4ugsk/Aoo/IhbYwtYwyughvt8GtOAMhwC+77zakxokQaylgJZ365LczEL9OYC7X/3FWT/40+8Em/4uBiAAvt28xrJCTBqgLzFWMHewcg6gZFpASPTAUbGS4xMEow3GFmszrFwPWBiGAU0BUIvGAfaCfQCr5gYnIQEGCWYLBhXMAKTXQDjDEbGBEYvWVMDIDA1NjDUNQUxjQyMjYyNDIwMTQ11DU0DmCM4khiy7CSYuYS5OLLYuFg4gClfiZ2LlYtZ16JYSFJKnItXiZuLcxMjVE4KSgtxSXGA2T+6JQtOMP5gYjwJTc4cDhehLEuHG0yMsxgZVjGySbEIpCgwKh1g5oRIxTkIQhh6DpKzZoLASXtLiMgFe8U0MLhmbzSBmeNGE68Qh09qWWqOgpmBhL3WIMs1Gp0OVDFHbS1F5ghI/aeOO4DAEEwWLHewzMz/0Hoy5Kq9I1TGIYIRADwhhf0=)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 16.08.2024

**Comment by kayla-glick** [comment]
Hey @Lexolaz thanks for reporting this! I've added combo point generation to swipe as long as it lands on your primary target. It can also proc Blood Frenzy. I also updated the APL to cast swipe at 4+ targets (that was the threshold that seemed to make it more worth casting than Shred)
