### ISSUE TITLE
Hunter Mongoose Bite Uses Outdated Raptors Fury Value

### ISSUE THREAD

**Issue by darandin** [wowsims/sod#984]
Value should be updated to 0.15 to reflect recent buffs.  Code should also be refactored to use the common value accessible in runes.go

![image](https://github.com/user-attachments/assets/369b3efa-7efb-4ee9-9e54-29a4659a863a)

**Comment by kayla-glick** [comment]
Hey thanks for reporting this! I've made a fix and it's going out now
