### ISSUE TITLE
Mage Combustion + Fire Blast interaction with Overheat Rune

### ISSUE THREAD

**Issue by tom-price** [wowsims/sod#992]
**Is your feature request related to a problem? Please describe.**
On August 15th the interaction between Overheat, which guarantees 100% crit on Fire Blast, and Combustion, which increases your crit strike percentage until you have 3 fire spells crit, was changed. News post [here](https://www.wowhead.com/classic/news/spells-no-longer-reset-cooldown-after-boss-fight-season-of-discovery-hotfix-345898).

**Describe the solution you'd like**
I'd like the Fire Blasts cast while Overheat is runed to:
* not increase the stacks of combustion (which happens after each non-critical fire damage spell typically)
* not count the Fire Blast crit towards the 3 crits after which combustion falls off.

**Describe alternatives you've considered**
N/A

**Additional context**
Here we can see the tracked crits incrementing after the Fire Blast crit.
<img width="1003" alt="3 crits" src="https://github.com/user-attachments/assets/64fb96ba-9ffc-401a-91d2-cdc550fbf9c7">

**Comment by kayla-glick** [comment]
Oops forgot to close this out but I added this in 👍
